### ISSUE TITLE
run bin/azkaban-web-start.sh error

### ISSUE THREAD

**Issue by abigbigbird** [azkaban/azkaban#1020]
jdk version:1.8.0_121
azkaban version:3.20.0 and 2.5.0
I follow the Getting Started doc and use the two server mode,when i start the web server,got this error
`2017/04/26 20:15:04.395 +0800 ERROR [AzkabanWebServer] [Azkaban] Starting Jetty Azkaban Executor...
2017/04/26 20:15:04.411 +0800 INFO [AzkabanServer] [Azkaban] Loading azkaban settings file from ./bin/../conf
2017/04/26 20:15:04.412 +0800 INFO [AzkabanServer] [Azkaban] Loading azkaban properties file
2017/04/26 20:15:04.420 +0800 INFO [AzkabanWebServer] [Azkaban] Setting up Jetty Https Server with port:8443 and numThreads:25
2017/04/26 20:15:04.440 +0800 INFO [log] [Azkaban] Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
Exception in thread "main" java.lang.NullPointerException
	at azkaban.webapp.AzkabanWebServer.loadUserManager(AzkabanWebServer.java:221)
	at azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:181)
	at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:726)`

**Comment by diaowenyang** [comment]
@abigbigbird Have you fix it ? And how to fix it ?

**Comment by mvineza** [comment]
Please make sure you have the executors started before running the UI.
