### ISSUE TITLE
flow loop/ flow not found

### ISSUE THREAD

**Issue by maven2016** [azkaban/azkaban#1128]
Working with multiple executors, currently only one executor is running for testing purposes.
running a simple "hello-world" command
although the status of the flow is "Success"
i'm unable to view the "job logs" (it's blank).
the flow is visible in "Executing Flows" page (& db table)
after a few minutes when "Cleaning recently finished" runs, the loop stops and
i'm able to view the "job logs"

2017-05-28 15:26:37 INFO  ExecutorServlet:120 - User  has called action execute on 48
2017-05-28 15:26:37 INFO  FlowPreparer:111 - Project already cached. Skipping download. ProjectVersion{projectId=5, version=1, installedDir=projects/5.1}
2017-05-28 15:26:37 INFO  FlowPreparer:82 - Flow Preparation complete. [execid: 48, path: executions/48]
2017-05-28 15:26:37 INFO  FlowRunnerManager:558 - Configuring Azkaban metrics tracking for flow runner object
2017-05-28 15:26:37 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:26:37 DEBUG log:40 - EOF
2017-05-28 15:26:37 INFO  hello_world:278 - Assigned executor : ip-10-20-60-158.ec2.internal:12321
2017-05-28 15:26:37 INFO  hello_world:279 - Running execid:48 flow:hello_world project:5 version:1
2017-05-28 15:26:37 INFO  hello_world:292 - Update active reference
2017-05-28 15:26:37 INFO  hello_world:217 - Updating initial flow directory.
2017-05-28 15:26:37 INFO  hello_world:219 - Fetching job and shared properties.
2017-05-28 15:26:37 INFO  hello_world:379 - Starting flows
2017-05-28 15:26:37 INFO  hello_world:534 - Running flow 'hello_world'.
2017-05-28 15:26:37 INFO  hello_world:858 - Configuring Azkaban metrics tracking for jobrunner object
2017-05-28 15:26:37 INFO  hello_world:745 - Submitting job 'hello_world' to run.
2017-05-28 15:26:37 INFO  hello_world:278 - Created file appender for job hello_world
2017-05-28 15:26:37 INFO  hello_world:263 - Attached file appender for job hello_world
2017-05-28 15:26:37 DEBUG JmxJobMBeanManager:109 - *** got JOB_STARTED hello_world azkaban.execapp.JobRunner status: QUEUED
2017-05-28 15:26:37 INFO  StdOutErrRedirect:55 - Uploading flowId hello_world
2017-05-28 15:26:37 DEBUG JmxJobMBeanManager:109 - *** got JOB_STATUS_CHANGED hello_world azkaban.execapp.JobRunner status: RUNNING
2017-05-28 15:26:37 ERROR StdOutErrRedirect:55 - cwd=/opt/azkaban/executions/48
2017-05-28 15:26:37 ERROR StdOutErrRedirect:55 - output properties file=/opt/azkaban/executions/48/hello_world_output_1940518770192449850_tmp
2017-05-28 15:26:37 DEBUG JmxJobMBeanManager:109 - *** got JOB_FINISHED hello_world azkaban.execapp.JobRunner status: SUCCEEDED
2017-05-28 15:26:37 INFO  hello_world:1068 - Job null finished with status SUCCEEDED in 0 seconds
2017-05-28 15:26:37 INFO  hello_world:636 - Flow '' is set to SUCCEEDED in 0 seconds
2017-05-28 15:26:37 INFO  hello_world:493 - No attachment file for job hello_world written.
2017-05-28 15:26:37 INFO  hello_world:405 - Finishing up flow. Awaiting Termination
2017-05-28 15:26:37 INFO  hello_world:409 - Finished Flow
2017-05-28 15:26:37 INFO  hello_world:241 - Setting end time for flow 48 to 1495985197221
2017-05-28 15:26:37 INFO  FlowRunnerManager:633 - Flow 48 is finished. Adding it to recently finished flows list.
2017-05-28 15:26:37 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@1bec22e3
2017-05-28 15:26:37 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12
2017-05-28 15:26:37 DEBUG log:40 - session=null
2017-05-28 15:26:37 DEBUG log:40 - servlet=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:37 DEBUG log:40 - chain=null
2017-05-28 15:26:37 DEBUG log:40 - servlet holder=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:37 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:26:37 DEBUG log:40 - EOF
2017-05-28 15:26:37 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@61522dee
2017-05-28 15:26:37 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12
2017-05-28 15:26:37 DEBUG log:40 - session=null
2017-05-28 15:26:37 DEBUG log:40 - servlet=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:37 DEBUG log:40 - chain=null
2017-05-28 15:26:37 DEBUG log:40 - servlet holder=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:37 INFO  ExecutorServlet:120 - User  has called action log on 48
2017-05-28 15:26:37 ERROR ExecutorServlet:191 - Running flow 48 not found.
azkaban.executor.ExecutorManagerException: Running flow 48 not found.
	at azkaban.execapp.FlowRunnerManager.readFlowLogs(FlowRunnerManager.java:643)
	at azkaban.execapp.ExecutorServlet.handleFetchLogEvent(ExecutorServlet.java:188)
	at azkaban.execapp.ExecutorServlet.doGet(ExecutorServlet.java:125)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:322)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
2017-05-28 15:26:37 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:26:37 DEBUG log:40 - EOF
2017-05-28 15:26:38 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@14199946
2017-05-28 15:26:38 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12
2017-05-28 15:26:38 DEBUG log:40 - session=null
2017-05-28 15:26:38 DEBUG log:40 - servlet=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:38 DEBUG log:40 - chain=null
2017-05-28 15:26:38 DEBUG log:40 - servlet holder=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:38 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:26:38 DEBUG log:40 - EOF
2017-05-28 15:26:38 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@35355b4e
2017-05-28 15:26:38 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12
2017-05-28 15:26:38 DEBUG log:40 - session=null
2017-05-28 15:26:38 DEBUG log:40 - servlet=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:38 DEBUG log:40 - chain=null
2017-05-28 15:26:38 DEBUG log:40 - servlet holder=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:38 INFO  ExecutorServlet:120 - User  has called action log on 48
2017-05-28 15:26:38 ERROR ExecutorServlet:191 - Running flow 48 not found.
azkaban.executor.ExecutorManagerException: Running flow 48 not found.
	at azkaban.execapp.FlowRunnerManager.readFlowLogs(FlowRunnerManager.java:643)
	at azkaban.execapp.ExecutorServlet.handleFetchLogEvent(ExecutorServlet.java:188)
	at azkaban.execapp.ExecutorServlet.doGet(ExecutorServlet.java:125)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:322)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
2017-05-28 15:26:38 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:26:38 DEBUG log:40 - EOF
2017-05-28 15:26:38 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@b92e74c
2017-05-28 15:26:38 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12
2017-05-28 15:26:38 DEBUG log:40 - session=null
2017-05-28 15:26:38 DEBUG log:40 - servlet=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:38 DEBUG log:40 - chain=null
2017-05-28 15:26:38 DEBUG log:40 - servlet holder=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:38 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:26:38 DEBUG log:40 - EOF
2017-05-28 15:26:39 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@2a9ddb72
2017-05-28 15:26:39 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12
2017-05-28 15:26:39 DEBUG log:40 - session=null
2017-05-28 15:26:39 DEBUG log:40 - servlet=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:39 DEBUG log:40 - chain=null
2017-05-28 15:26:39 DEBUG log:40 - servlet holder=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:39 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:26:39 DEBUG log:40 - EOF
2017-05-28 15:26:39 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@b99948f
2017-05-28 15:26:39 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12
2017-05-28 15:26:39 DEBUG log:40 - session=null
2017-05-28 15:26:39 DEBUG log:40 - servlet=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:39 DEBUG log:40 - chain=null
2017-05-28 15:26:39 DEBUG log:40 - servlet holder=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:39 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:26:39 DEBUG log:40 - EOF
2017-05-28 15:26:40 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@4a6e13b9
2017-05-28 15:26:40 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12
2017-05-28 15:26:40 DEBUG log:40 - session=null
2017-05-28 15:26:40 DEBUG log:40 - servlet=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:40 DEBUG log:40 - chain=null
2017-05-28 15:26:40 DEBUG log:40 - servlet holder=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:26:40 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:26:40 DEBUG log:40 - EOF
2017-05-28 15:26:40 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@778e1c09
2017-05-28 15:26:40 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12

2017-05-28 15:28:39 DEBUG log:40 - REQUEST /executor on org.mortbay.jetty.HttpConnection@7008450c
2017-05-28 15:28:39 DEBUG log:40 - sessionManager=org.mortbay.jetty.servlet.HashSessionManager@77b52d12
2017-05-28 15:28:39 DEBUG log:40 - session=null
2017-05-28 15:28:39 DEBUG log:40 - servlet=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:28:39 DEBUG log:40 - chain=null
2017-05-28 15:28:39 DEBUG log:40 - servlet holder=azkaban.execapp.ExecutorServlet-748658608
2017-05-28 15:28:39 DEBUG log:40 - RESPONSE /executor  200
2017-05-28 15:28:39 DEBUG log:40 - EOF

2017-05-28 15:28:42 INFO  FlowRunnerManager:312 - # of executing flows: 0
2017-05-28 15:28:42 INFO  FlowRunnerManager:317 - Cleaning recently finished
2017-05-28 15:28:42 INFO  FlowRunnerManager:397 - Cleaning execution 48 from recently finished flows list.

**Comment by zwj-weijie** [comment]
@maven2016  Did you solved the question?how?thank you !

**Comment by hejiahaov** [comment]
Somebody solved the question?I have two server node,just one meet it.
