### ISSUE TITLE
Running azkaban-solo-server from in development mode

### ISSUE THREAD

**Issue by juhoautio** [azkaban/azkaban#1130]
Is there a standard way to quickly run azkaban-solo-server locally? Maybe even directly from IDEA?

I expect that it would be possible to run `azkaban.soloserver.AzkabanSingleServer`, maybe even without any args, and it would just work.

Do you see a way to have this kind of setup available in git so that solo server could run "out of the box" in IDEA?

What about `.less` files – could they be automatically compiled (if modified) to `.css` when running the server while developing?

----

I've used this kinda script "build-and-restart-azkaban.sh":

```sh
#!/bin/bash
if [ -f azkaban-solo-server/build/distributions/azkaban-solo-server-3.0.0/bin/azkaban-solo-shutdown.sh ]; then
    azkaban-solo-server/build/distributions/azkaban-solo-server-3.0.0/bin/azkaban-solo-shutdown.sh
fi
set -e
rm -rf azkaban-solo-server/build/distributions/azkaban-solo-server-3.0.0
./gradlew distTar
mv $(ls -t azkaban-solo-server/build/distributions/azkaban-solo-server-*gz | head -1) azkaban-solo-server/build/distributions/azkaban-solo-server-3.0.0.tar.gz
tar -xzf azkaban-solo-server/build/distributions/azkaban-solo-server-3.0.0.tar.gz -C azkaban-solo-server/build/distributions/
mv $(ls -dt azkaban-solo-server/build/distributions/*/ | head -1) azkaban-solo-server/build/distributions/azkaban-solo-server-3.0.0
cd azkaban-solo-server/build/distributions/azkaban-solo-server-3.0.0/
# fix joda-time version conflict for aws s3 library
rm lib/joda-time-2.0.jar
cp ~/.m2/repository/joda-time/joda-time/2.9.1/joda-time-2.9.1.jar lib/
bin/azkaban-solo-start.sh
```

**Comment by juhoautio** [comment]
@HappyRay shared this with me, but it wasn't yet enough for me to run the solo-server successfully:

> I can start solo server in Intellij.

<img width="1027" alt="199ed2d6-4205-11e7-9114-dedffa91513e" src="https://cloud.githubusercontent.com/assets/4446608/26550691/9a9ceb96-4487-11e7-8d41-0f6e69453c2c.png">

> Here is my property file
`azkaban/temp/conf/azkaban.properties`:

```sh
# Azkaban Personalization Settings
azkaban.name=Local
azkaban.label=My Local Azkaban
azkaban.color=#FF3601

# this assumes that this file is under a <AZ source root>/<dir>/conf directory
web.resource.dir=../azkaban-web-server/build/install/azkaban-web-server/web
default.timezone.id=America/Los_Angeles

# Azkaban UserManager class
user.manager.class=azkaban.user.XmlUserManager
user.manager.xml.file=conf/azkaban-users.xml

# Loader for projects
executor.global.properties=conf/global.properties
azkaban.project.dir=projects

azkaban.execution.dir=executions

# DB
database.sql.scripts.dir=../azkaban-db/src/main/sql
database.check.version=true
database.auto.update.tables=true

#mysql
database.type=mysql
mysql.port=3306
mysql.host=localhost
mysql.database=azkaban
mysql.numconnections=100

# h2 db
#database.type=h2
#h2.path=data/azkaban
#h2.create.tables=true

azkaban.jobtype.plugin.dir=plugins/jobtypes

# Velocity dev mode
#velocity.dev.mode=false
velocity.dev.mode=true

# Azkaban Jetty server properties. Ignored in tomcat
jetty.use.ssl=false
jetty.ssl.port=8043
jetty.maxThreads=25
jetty.port=8081

# Azkaban Executor settings
executor.maxThreads=50

executor.flow.threads=30

# mail settings
mail.sender=
mail.host=
job.failure.email=
job.success.email=

lockdown.create.projects=false


# JMX stats
jetty.connector.stats=true
executor.connector.stats=true

# uncomment to enable inmemory stats for azkaban
executor.metric.reports=true
executor.metric.milisecinterval.default=60000
```

**Comment by juhoautio** [comment]
So far I had to at least add these to get rid of some errors:

```sh
mysql.user=
mysql.password=
```

And change these paths:
```sh
user.manager.xml.file=../azkaban-solo-server/src/main/resources/conf/azkaban-users.xml
executor.global.properties=../azkaban-solo-server/src/main/resources/conf/global.properties
```

I'm getting this error in the console:

```
2017/05/29 16:04:43.453 +0300 INFO [AzkabanExecutorServer] [Azkaban] No value for property: jmx.attribute.processor.class was found
2017/05/29 16:04:43.453 +0300 INFO [log] [Azkaban] jetty-6.1.26
2017/05/29 16:04:43.474 +0300 INFO [log] [Azkaban] Started SocketConnector@0.0.0.0:58691
Exception in thread "main" 2017/05/29 16:04:43.508 +0300 INFO [AzkabanExecutorServer] [Azkaban] Started Executor Server on 192.168.184.228:58691
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, azkaban.executor.ExecutorManagerException: No active executor found
  at azkaban.executor.ExecutorManager.<init>(ExecutorManager.java:128)
  at azkaban.AzkabanCommonModule.configure(AzkabanCommonModule.java:83)
  while locating azkaban.executor.ExecutorManager
  at azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:186)
  at azkaban.webapp.AzkabanWebServerModule.configure(AzkabanWebServerModule.java:33)
  while locating azkaban.webapp.AzkabanWebServer
    for the 1st parameter of azkaban.soloserver.AzkabanSingleServer.<init>(AzkabanSingleServer.java:44)
  while locating azkaban.soloserver.AzkabanSingleServer

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at azkaban.soloserver.AzkabanSingleServer.main(AzkabanSingleServer.java:82)
Caused by: azkaban.executor.ExecutorManagerException: No active executor found
	at azkaban.executor.ExecutorManager.setupExecutors(ExecutorManager.java:221)
	at azkaban.executor.ExecutorManager.<init>(ExecutorManager.java:132)
	at azkaban.executor.ExecutorManager$$FastClassByGuice$$e1c1dfed.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at azkaban.ServiceProvider.getInstance(ServiceProvider.java:52)
	at azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:195)
	at azkaban.webapp.AzkabanWebServer$$FastClassByGuice$$81e0dd4a.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 2 more
```

**Comment by kunkun-tang** [comment]
@juhoautio You can specify an executor a port by configuration:
`executor.port=12321`

My Mysql always has only one active executor:

id | host | port | active
-----| --- |------- | -------------
1 | localhost | 12321 | 1

(select * from executors)

**Comment by juhoautio** [comment]
Wow, thanks @kunkun-tang, that did the trick. Indeed that's also present in `azkaban-solo-server/src/main/resources/conf/azkaban.properties`.

I wonder how the conf that @HappyRay uses works then.. @HappyRay: could you copy here your complete set of VM Options? It gets cut off in the screenshot.

**Comment by HappyRay** [comment]
Oh. I have other files under the temp/conf directory:

an empty global.properties

My own azkaban-users.xml
and 
azkaban.private.properties

# Optional Properties that are hidden to the executions
executor.port=12321
mysql.user=xxxx
mysql.password=xxxx

**Comment by juhoautio** [comment]
Clear then.

Do you see a way how this could be supported "out of the box", just by running the `AzkabanSingleServer` without having to set up additional conf?

And what about `.less` compilation in development mode?

**Comment by HappyRay** [comment]
It may be possible. Would you like to give it a try?

I typically run gradlew build manually to get new UI changes. You can also set up the IDE run config to run the build every time which will add overhead.

**Comment by juhoautio** [comment]
Yes, I can try. I'm just wondering which way to go.. Maybe something like this:
- When `AzkabanSingleServer` is executed without any args..
  - If running for the first time, copy some required conf files to `local/` (a new folder not managed by git)
  - This way user is able to make changes like DB conf without having dirty files on git staging area
  - So `local/` is added to `.gitignore`, by the way which already has this:

		# temp directory is ignored so that it can be used to store temporary files such as local testing configurations.
		temp/

    - But I would prefer `local/` over `temp/` for the conf, because maybe it's not really that temporary if you have set your db credentials there etc.. do you mind what the folder is called?
  - Then if `local/azkaban.properties` exists, run as if executed with `-conf local`
- Maybe this to auto-detect `.less` changes: https://github.com/houbie/lesscss-gradle-plugin#lesscdaemon-task
  - what do you think? It would need to be started manually, but could be setup so that you only need to run one command to start it.

**Comment by HappyRay** [comment]
Your plan sounds good to me. 

The plugin  https://github.com/houbie/lesscss-gradle-plugin#lesscdaemon-task README gives a warning and points to some alternatives. I hope it is fine to use. I am not too worried about it though. If it doesn't work, we can switch.  I wonder if one of the alternatives  https://github.com/bertramdev/less-asset-pipeline would work too. But I haven't read enough to know.

**Comment by juhoautio** [comment]
Roger that. I didn't really check that less plugin at all yet, so I didn't notice that it's discouraged. Going to try the suggested alternatives instead.

**Comment by juhoautio** [comment]
Implemented in https://github.com/azkaban/azkaban/pull/1423

**Comment by abti** [comment]
Just stumbled upon this. It was quite useful to get me going on Idea. Thanks for doing it @juhoautio
