### ISSUE TITLE
The test azkaban.execapp.FlowRunnerTest2#testRetryOnFailure is flaky

### ISSUE THREAD

**Issue by HappyRay** [azkaban/azkaban#1155]
The travis build on the master failed with the following error:

https://travis-ci.org/azkaban/azkaban/builds
https://travis-ci.org/azkaban/azkaban/builds/239316403

azkaban.execapp.FlowRunnerTest2 > testRetryOnFailure FAILED

java.lang.AssertionError: Wrong status for [jobb:innerFlow] expected:<SKIPPED> but was:<DISABLED>

    at org.junit.Assert.fail(Assert.java:88)

    at org.junit.Assert.failNotEquals(Assert.java:834)

    at org.junit.Assert.assertEquals(Assert.java:118)

    at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:137)

    at azkaban.execapp.FlowRunnerTest2.testRetryOnFailure(FlowRunnerTest2.java:661)
Looks like the test is still flaky.

related to  #1129

**Comment by HappyRay** [comment]
Another failure when running locally.

Create temp dir
2017/06/04 10:20:37.812 -0700 INFO [main] [JobTypeManager] Loading plugin default job types
2017/06/04 10:20:39.871 -0700 INFO [main] [JmxJobMBeanManager] Initializing azkaban.execapp.jmx.JmxJobMBeanManager
2017/06/04 10:20:39.906 -0700 INFO [main] [FlowRunnerTest2] Adding test1.properties
2017/06/04 10:20:39.907 -0700 INFO [main] [FlowRunnerTest2] Adding test2.properties
2017/06/04 10:20:41.706 -0700 INFO [Thread-1] [jobf] Running execid:101 flow:jobf project:1 version:-1
2017/06/04 10:20:41.721 -0700 INFO [FlowRunner-exec-101] [jobf] Update active reference
2017/06/04 10:20:41.722 -0700 INFO [FlowRunner-exec-101] [jobf] Updating initial flow directory.
2017/06/04 10:20:41.722 -0700 INFO [FlowRunner-exec-101] [jobf] Fetching job and shared properties.
2017/06/04 10:20:41.731 -0700 INFO [FlowRunner-exec-101] [jobf] Starting flows
2017/06/04 10:20:41.790 -0700 INFO [FlowRunner-exec-101] [jobf] Running flow 'jobf'.
ExecutableFlow: jobf RUNNING
ExecutableNode: joba1 QUEUED
ExecutableFlow: jobb READY
ExecutableNode: jobb:innerFlow READY
ExecutableNode: jobb:innerJobB READY
ExecutableNode: jobb:innerJobA READY
ExecutableNode: jobb:innerJobC READY
ExecutableNode: joba READY
ExecutableFlow: jobd READY
ExecutableNode: jobd:innerJobA READY
ExecutableNode: jobd:innerFlow2 READY
ExecutableNode: jobc READY
ExecutableNode: jobf READY
ExecutableNode: jobe READY
Teardown temp dir
2017/06/04 10:20:42.212 -0700 INFO [FlowRunner-exec-101] [jobf] Configuring Azkaban metrics tracking for jobrunner object
2017/06/04 10:20:42.216 -0700 INFO [FlowRunner-exec-101] [jobf] Submitting job 'joba1' to run.

java.lang.AssertionError: Wrong status for [joba] 
Expected :RUNNING
Actual   :READY
 <Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:137)
	at azkaban.execapp.FlowRunnerTest2.testPauseFailFinishAll(FlowRunnerTest2.java:994)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by HappyRay** [comment]
Another random failure 
see #1157

**Comment by juhoautio** [comment]
Thanks for gathering the logs & stack traces. I ran `FlowRunnerTest2` 100 times in a row locally and got 1 failure, so should be possible to catch at least something.

**Comment by juhoautio** [comment]
@HappyRay, this issue can be closed.

**Comment by HappyRay** [comment]
Fixed by #1162 #1158

**Comment by juhoautio** [comment]
Thanks. https://github.com/azkaban/azkaban/pull/1159 was also needed to fix.
