### ISSUE TITLE
ci build failure again in FlowRunnerTest

### ISSUE THREAD

**Issue by HappyRay** [azkaban/azkaban#1217]
see https://travis-ci.org/azkaban/azkaban/builds/242197329?utm_source=email&utm_medium=notification

azkaban.execapp.FlowRunnerTest > exec1Disabled FAILED
    java.lang.AssertionError: Flow didn't reach expected status
        at org.junit.Assert.fail(Assert.java:88)
        at azkaban.execapp.FlowRunnerTestBase.waitFlowRunner(FlowRunnerTestBase.java:52)
        at azkaban.execapp.FlowRunnerTestBase.assertThreadShutDown(FlowRunnerTestBase.java:29)
        at azkaban.execapp.FlowRunnerTest.exec1Disabled(FlowRunnerTest.java:144)
74 tests completed, 1 failed, 22 skipped
:azkaban-exec-server:test FAILED

**Comment by juhoautio** [comment]
I'll try to figure out why this could happen.

**Comment by juhoautio** [comment]
Oh quite clear, that `FlowRunnerTestBase.waitFlowRunner` where it failed still only had 100 x 10ms max wait. Changing it to 1000 x 10 ms.

**Comment by juhoautio** [comment]
Fix: https://github.com/azkaban/azkaban/pull/1220
