### ISSUE TITLE
Velocity could not be initialized!

### ISSUE THREAD

**Issue by realman129942** [azkaban/azkaban#1271]
azkaban.webapp.servlet.PageRenderException: java.lang.RuntimeException: Velocity could not be initialized!
        at azkaban.webapp.servlet.Page.render(Page.java:64)
        at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.handleLogin(LoginAbstractAzkabanServlet.java:271)
        at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.handleLogin(LoginAbstractAzkabanServlet.java:261)
        at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.doGet(LoginAbstractAzkabanServlet.java:131)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at org.mortbay.jetty.security.SslSocketConnector$SslConnection.run(SslSocketConnector.java:713)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.lang.RuntimeException: Velocity could not be initialized!
        at org.apache.velocity.runtime.RuntimeInstance.requireInitialization(RuntimeInstance.java:307)
        at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1531)
        at org.apache.velocity.app.VelocityEngine.mergeTemplate(VelocityEngine.java:343)
        at azkaban.webapp.servlet.Page.render(Page.java:62)
        ... 19 more
Caused by: java.lang.RuntimeException: JarResourceLoader : JAR path must start with jar: -> see java.net.JarURLConnection for information
        at org.apache.velocity.runtime.resource.loader.JarResourceLoader.loadJar(JarResourceLoader.java:143)
        at org.apache.velocity.runtime.resource.loader.JarResourceLoader.init(JarResourceLoader.java:118)
        at org.apache.velocity.runtime.resource.ResourceManagerImpl.initialize(ResourceManagerImpl.java:143)
        at org.apache.velocity.runtime.RuntimeInstance.initializeResourceManager(RuntimeInstance.java:730)
        at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:263)
        at org.apache.velocity.runtime.RuntimeInstance.requireInitialization(RuntimeInstance.java:302)

**Comment by helpxin** [comment]
I found the same problem .My project is run field after i add plugins dir to the properties.

**Comment by yichao0803** [comment]
> I found the same problem .My project is run field after i add plugins dir to the properties.

I encountered the same problem. After performing the following operations, the system can run normally
1. Copy the `azkaban-solo-server/plugins` directory to the `azkaban-web-server` directory
2. Add `azkaban.jobtype.plugin.dir=/usr/local/azkaban/azkaban-web-server/plugins/jobtypes` in `azkaban-web-server/conf/azkaban.properties`
3. Start web `./bin/start-web.sh`
