### ISSUE TITLE
Fix flaky test

### ISSUE THREAD

**Issue by suvodeep-pyne** [azkaban/azkaban#1389]
This test is flaky and failing a lot of times. Example: https://travis-ci.org/azkaban/azkaban/builds/268055504

```
azkaban.execapp.JobRunnerTest > testDelayedExecutionCancelledJob FAILED
    java.lang.AssertionError: expected:<2> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at azkaban.execapp.JobRunnerTest.testDelayedExecutionCancelledJob(JobRunnerTest.java:313)
```

**Comment by reallocf** [comment]
:pray:

**Comment by HappyRay** [comment]
@juhoautio any idea?

**Comment by HappyRay** [comment]
Master failed with
the following error too today
https://travis-ci.org/azkaban/azkaban/builds/268499837?utm_source=email&utm_medium=notification

azkaban.execapp.FlowRunnerTest2 > testCancelOnFailure FAILED
    java.lang.AssertionError: Wrong status for [jobb:innerJobB] expected:<RUNNING> but was:<READY>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:117)
        at azkaban.execapp.FlowRunnerTest2.testCancelOnFailure(FlowRunnerTest2.java:576)

**Comment by juhoautio** [comment]
1. JobRunnerTest#testDelayedExecutionCancelledJob
   - It might help to make the sleep longer before that assertion, for example 1 s -> 2 s. Any way I'm not sure if this will help.. What I know though is that it constantly fails with a similar-looking same error if the sleep is removed altogether.
   - Better yet, that assertion could be changed to a "polling assert" with a, say, 10 s timeout.
2. FlowRunnerTest2#testCancelOnFailure, that seems really strange to me.. I can't really imagine how that could happen. Makes me wonder, could it even be a real bug, not just a flaky test..

**Comment by HappyRay** [comment]
Another failure today:

azkaban.execapp.FlowRunnerTest2 > testRetryOnFailure FAILED
    java.lang.AssertionError: Wrong status for [jobb:innerJobB] expected:<RUNNING> but was:<READY>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:117)
        at azkaban.execapp.FlowRunnerTest2.testRetryOnFailure(FlowRunnerTest2.java:647)
75 tests completed, 2 failed, 22 skipped

**Comment by HappyRay** [comment]
Thanks @juhoautio 
Do you think we should ignore these tests for now until the problem is fixed?

**Comment by juhoautio** [comment]
If possible at all, could you try to explore if it would be possible to keep the full test output in case of a failed test on Travis? That would make it so much easier to debug why a test failed. When running these locally I never get failures even if I run the tests 1000 times :)

Ignoring "for now" would probably mean that there's no way to find the fix any way, so it would be the same as ignoring permanently.

And it's really sad if the tests have to be ignored for good, because who's going to remember to temporarily remove the `@Ignore` annotation when making changes to related classes..

**Comment by suvodeep-pyne** [comment]
> If possible at all, could you try to explore if it would be possible to
keep the full test output in case of a failed test on Travis?

Try rerunning the build link I shared a few times. I don't think Travis
saves the build logs. However, it seems pretty frequent and should be easy
to capture.

> Ignoring "for now" would probably mean that there's no way to find the
fix anyway, so it would be the same as ignoring permanently.
I agree. But we need to solve the problem of build failing intermittently.
It is pretty annoying.
So either we find a quick fix, or we need to disable it. That's the reason
I filed an issue so that this doesn't get lost.

Regards
Suvodeep

**Comment by HappyRay** [comment]
@juhoautio you asked if there is a standard way to do poll and wait in tests. I found this today. https://michaeltamm.github.io/junit-toolbox/com/googlecode/junittoolbox/PollingWait.html Do you think this is going to be useful in AZ tests?

**Comment by HappyRay** [comment]
@juhoautio Yes, I found it hard to debug flaky tests that only fail on Travis too. Unfortunately, I have not found a good solution to see full test output in Travis. Let me try the --info flag to see if it will work.

I understand and agree with your concerns. A flaky test is a big drain on productivity. I hope that the problem can be debugged in a PR or personal clone while the main line has the flaky tests ignored.

**Comment by HappyRay** [comment]
I would like to refactor the code to make tests easier to write and maintain in the long term.

**Comment by juhoautio** [comment]
@HappyRay wrote:

> https://michaeltamm.github.io/junit-toolbox/com/googlecode/junittoolbox/PollingWait.html

Maybe I'm missing the point, but the usage pattern that I was looking for would be simple as:

```java
assertThat(timeout(10L, TimeUnit.SECONDS), node.getStatus(), is(Status.SUCCESS));
```

I've seen this kinda thing somewhere, maybe Hamcrest..

This kind of pattern is most likely implemented as a loop that has a simple 10ms sleep or such, which is not 100% optimal. Instead I've used wait+notify pattern in some tests (in Azkaban) to let them run as quickly as possible. For the case at hand there's no way to wait for actual condition without modifying the non-test code, so I think the best solution is to loop with a short sleep, making the "polling assert" useful.

**Comment by juhoautio** [comment]
> I hope that the problem can be debugged in a PR

Yeah that makes sense to me as well. As long as the failure is not _too_ rare :)

**Comment by juhoautio** [comment]
Bottom line, I really like the idea of ignoring the tests in `master` and then actively trying to debug what's actually happening on Travis. Capturing the output would be really good, and I guess new builds can be triggered simply by closing & reopening an existing PR(?).

**Comment by HappyRay** [comment]
> so I think the best solution is to loop with a short sleep, making the "polling assert" useful.
Sounds reasonable to me.
Do you mind giving it a try?

**Comment by HappyRay** [comment]
> and I guess new builds can be triggered simply by closing & reopening an existing PR(?).

I think so. I remember I may have tried it.

**Comment by HappyRay** [comment]
Here is another library that may help with testing asynchronous systems
https://github.com/awaitility/awaitility

**Comment by juhoautio** [comment]
I can see from history that you haven't ignored any test cases yet:
- https://github.com/azkaban/azkaban/commits/master/azkaban-exec-server/src/test/java/azkaban/execapp/JobRunnerTest.java
- https://github.com/azkaban/azkaban/commits/master/azkaban-exec-server/src/test/java/azkaban/execapp/FlowRunnerTest2.java

I was looking at a recently failed `master` build and found these:

## FlowRunnerTest > exec1Normal FAILED

> Failed to copy full contents from '../test/execution-test-data/exectest1/job2.job' to 'build/tmp/_AzkabanTestDir_1504050231923/job2.job'

Huh?

```
azkaban.execapp.FlowRunnerTest > exec1Normal FAILED
    java.io.IOException: Failed to copy full contents from '../test/execution-test-data/exectest1/job2.job' to 'build/tmp/_AzkabanTestDir_1504050231923/job2.job'
        at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1157)
        at org.apache.commons.io.FileUtils.doCopyDirectory(FileUtils.java:1428)
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1389)
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261)
        at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230)
        at azkaban.execapp.FlowRunnerTest.prepareExecDir(FlowRunnerTest.java:320)
        at azkaban.execapp.FlowRunnerTest.createFlowRunner(FlowRunnerTest.java:393)
        at azkaban.execapp.FlowRunnerTest.createFlowRunner(FlowRunnerTest.java:387)
        at azkaban.execapp.FlowRunnerTest.exec1Normal(FlowRunnerTest.java:102)
```

##  FlowRunnerTest2 > testPauseFailKill: NPE in Arrays.sort

The test itself didn't fail, though. Never seen this before, but seems like this should be easy to fix.

```
azkaban.execapp.FlowRunnerTest2 > testPauseFailKill STANDARD_OUT
    Create temp dir
    2017/08/29 23:43:51.235 +0000 ERROR [JobRunner-innerJobC-107] [JobRunner] Unexpected exception
    java.lang.NullPointerException
    	at java.util.Arrays.sort(Arrays.java:1438)
    	at azkaban.execapp.JobRunner.finalizeLogFile(JobRunner.java:516)
    	at azkaban.execapp.JobRunner.doRun(JobRunner.java:614)
    	at azkaban.execapp.JobRunner.run(JobRunner.java:552)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:748)
    2017/08/29 23:43:51.235 +0000 INFO [Test worker] [JobTypeManager] Loading plugin default job types
    2017/08/29 23:43:51.239 +0000 INFO [JobRunner-jobc-107] [MockExecutorLoader] Uploaded log for [jobc]:[107]:
    29-08-2017 23:43:51 UTC jobc INFO - Starting job jobc at 1504050231175
    29-08-2017 23:43:51 UTC jobc INFO - azkaban.webserver.url property was not set
    29-08-2017 23:43:51 UTC jobc INFO - job JVM args: -Dazkaban.flowid=jobf -Dazkaban.execid=107 -Dazkaban.jobid=jobc
    29-08-2017 23:43:51 UTC jobc INFO - Building test job executor. 
    29-08-2017 23:43:51 UTC jobc ERROR - Kill has been called.
    29-08-2017 23:43:51 UTC jobc INFO - Killing job
    29-08-2017 23:43:51 UTC jobc ERROR - Job run killed!
    java.lang.RuntimeException: Forced failure of jobc
    	at azkaban.executor.InteractiveTestJob.run(InteractiveTestJob.java:113)
    	at azkaban.execapp.JobRunner.runJob(JobRunner.java:748)
    	at azkaban.execapp.JobRunner.doRun(JobRunner.java:591)
    	at azkaban.execapp.JobRunner.run(JobRunner.java:552)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:748)
    29-08-2017 23:43:51 UTC jobc ERROR - Forced failure of jobc cause: null
    29-08-2017 23:43:51 UTC jobc INFO - Finishing job jobc at 1504050231223 with status KILLED
    2017/08/29 23:43:51.241 +0000 INFO [JobRunner-jobc-107] [jobf] No attachment file for job jobc written.
    2017/08/29 23:43:51.244 +0000 INFO [Test worker] [JmxJobMBeanManager] Initializing azkaban.execapp.jmx.JmxJobMBeanManager
    2017/08/29 23:43:51.245 +0000 INFO [Test worker] [FlowRunnerTest2] Adding test1.properties
    2017/08/29 23:43:51.245 +0000 INFO [Test worker] [FlowRunnerTest2] Adding test2.properties
    2017/08/29 23:43:51.242 +0000 ERROR [JobRunner-innerJobB-107] [JobRunner] Unexpected exception
    java.lang.NullPointerException
    	at java.util.Arrays.sort(Arrays.java:1438)
    	at azkaban.execapp.JobRunner.finalizeLogFile(JobRunner.java:516)
    	at azkaban.execapp.JobRunner.doRun(JobRunner.java:614)
    	at azkaban.execapp.JobRunner.run(JobRunner.java:552)
```

I wonder if there's an easier way to get a list of _failed tests_ from Travis. Any idea? Like getting an HTML test report or something? The best I could think of is this:
1.  Download raw log from Travis
1. Search with regex ` > [a-zA-Z0-9]* FAILED`

:D

**Comment by HappyRay** [comment]
@juhoautio Thanks for looking into these issues.
We haven't disabled these tests since I made some changes to the build and the tests have not failed since.

Your suggestions all seem reasonable.

No, I haven't found a way to download the html based test report from Travis.

**Comment by juhoautio** [comment]
Here's for that `FlowRunnerTest > exec1Normal` bug: https://github.com/azkaban/azkaban/pull/1417

**Comment by juhoautio** [comment]
Could someone edit the issue description to include this:

1. Download raw log from Travis
1. Search with regex `> [a-zA-Z0-9]* FAILED`

**Comment by HappyRay** [comment]
Done. Thanks

**Comment by juhoautio** [comment]
Some fix PRs submitted as seen above ^

These two I haven't analyzed yet, but the problems in them could be something quite similar to https://github.com/azkaban/azkaban/pull/1439:

```
azkaban.execapp.FlowRunnerTest2 > testCancelOnFailure FAILED
java.lang.AssertionError: Wrong status for [jobb:innerJobB] expected: but was:
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:117)
at azkaban.execapp.FlowRunnerTest2.testCancelOnFailure(FlowRunnerTest2.java:576)
```

```
azkaban.execapp.FlowRunnerTest2 > testRetryOnFailure FAILED
java.lang.AssertionError: Wrong status for [jobb:innerJobB] expected: but was:
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:118)
at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:117)
at azkaban.execapp.FlowRunnerTest2.testRetryOnFailure(FlowRunnerTest2.java:647)
75 tests completed, 2 failed, 22 skipped
```

**Comment by juhoautio** [comment]
Maybe pointless to investigate those 2 without test logs.

I suggest closing this issue and creating new tickets for any further test failures when they occur. When creating an issue, save the full "raw log" from the failed Travis build as a public github gist and add link to that in the issue description.
