### ISSUE TITLE
Not permitted to proxy as 'azkaban' through Azkaban

### ISSUE THREAD

**Issue by lhcg** [azkaban/azkaban#1390]
@HappyRay @ kunkun-tang
I get  this issue
```
azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'
	at azkaban.utils.Props.getString(Props.java:426)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:234)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:748)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:591)
	at azkaban.execapp.JobRunner.run(JobRunner.java:552)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
25-08-2017 18:20:14 CST foo ERROR - Missing required property 'azkaban.native.lib' cause: null
```

From the doc http://azkaban.github.io/azkaban/docs/latest/
Execute-As-User
With a new security enhancement in Azkaban 3.0, Azkaban jobs can now run as the submit user or the user.to.proxy of the flow by default. This ensures that Azkaban takes advantage of the Linux permission security mechanism, and operationally this simplifies resource monitoring and visibility. Set up this behavior by doing the following:-

Execute.as.user is set to true by default. In case needed, it can also be configured to false in azkaban-plugin’s commonprivate.properties
Configure azkaban.native.lib= to the place where you are going to put the compiled execute-as-user.c file (see below)
Generate an executable on the Azkaban box for azkaban-common/src/main/c/execute-as-user.c. it should be named execute-as-user Below is a sample approach
scp ./azkaban-common/src/main/c/execute-as-user.c onto the Azkaban box
run: gcc execute-as-user.c -o execute-as-user
run: chown root execute-as-user (you might need root privilege)
run: chmod 6050 execute-as-user (you might need root privilege)

**I have done in exec-server  by step, while in the {azkban-exec-server-3.33.0}/plugins/jobtypes**

then I get other issue:

```
java.lang.RuntimeException: Not permitted to proxy as 'azkaban' through Azkaban
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:240)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:748)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:591)
	at azkaban.execapp.JobRunner.run(JobRunner.java:552)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
25-08-2017 20:58:20 CST foo ERROR - Not permitted to proxy as 'azkaban' through Azkaban cause: null
```
So where is the problem? thx!

**Comment by lhcg** [comment]
@HappyRay 
@kunkun-tang

**Comment by kunkun-tang** [comment]
azkaban/jobExecutor/ProcessJob.java:226
@lhcg Please check the above code.  The two names, including `root` and `azkaban` are blacklisted. You should give another name a try.

**Comment by prokod** [comment]
How will you guys suggest us to do parameters passing between jobs then ? 
Right now I am facing an issue where a job that should write to JOB_OUTPUT_PROP_FILE and is being executed by a user other then `azkaban` is failing on permission to write the json file inside the execution dir which is owned by `azkaban` user.

**Comment by HappyRay** [comment]
We haven't seen this permission issue.  #1292 and #1325 may be related. 
cc @reallocf

**Comment by prokod** [comment]
@HappyRay @reallocf Just wanted to let you know that I was able to kinda fix that: The issue was we had copied project directories from azkaban 3.0.0 to azkaban 3.34.0 and this triggered the permission issue. Once we had a clean installation and a new deployment of one the previous failing projects we did not observe the permissions issue anymore.
This leaves me with one open issue which is how we should migrate the projects from 3.0.0 to recent version. It seemed to us that when trying to use 3.0.0 maintained DB with recent Azakaban web and exec there is some error message popping up when it tries to load the project to the exec from DB. We will try it soon and I will update whether this is true enough.

**Comment by HappyRay** [comment]
@prokod There are some DB schema changes. Please take a look at azkaban-db/src/main/sql/upgrade.3.20.0.to.3.22.0.sql for example. Also take a look at the changes made to the sql directory azkaban-db/src/main/sql

**Comment by prokod** [comment]
Hi @HappyRay so my previous statement that it works as expected was an incorrect one.
It appears I had set `execute.as.user` to false and this is why I did not have issues with the specific workflow I was testing.
When I reinstated `execute.as.user=true` then some of the directories under the execution are created with `user.to.proxy` user as owner and then `azkaban` user cannot write to those directories for instance:
```
07-09-2017 16:24:46 CEST preprocessing-hourly-forward ERROR - Could not open log file in executions/75/forwardFlow for job preprocessing-hourly-forward_calcCheck
java.io.FileNotFoundException: /opt/azkaban-exec-server-3.34.0/executions/75/forwardFlow/_job.75.preprocessing-hourly-forward_calcCheck.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:213)
	at java.io.FileOutputStream.&lt;init&gt;(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.&lt;init&gt;(FileAppender.java:110)
	at org.apache.log4j.RollingFileAppender.&lt;init&gt;(RollingFileAppender.java:79)
	at azkaban.execapp.JobRunner.createFileAppender(JobRunner.java:317)
	at azkaban.execapp.JobRunner.createLogger(JobRunner.java:266)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:569)
	at azkaban.execapp.JobRunner.run(JobRunner.java:552)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
In this example `forwardFlow` dir owner is same as user.to.proxy` which is different then `azkaban` user.
Any ideas how to resolve that?

**Comment by HappyRay** [comment]
@reallocf should have fixed this. He can share more details.

**Comment by reallocf** [comment]
Hey @prokod!

A couple thoughts. First, if you're coming from 3.0.0, I'd suggest upgrading to 3.30.1 which is our most recent stable release. 3.32.2 should also be good - we've been running it here in production for almost a month now and it will likely be marked as a stable build soon. We're only now releasing 3.34.0 so there might be additional bugs other than the one that might be here.

Now for your problems with execute-as-user, could you please share an example of a flow that is failing with your setup? Between 3.32.2 and 3.34.0 we updated the execute-as-user.c file and it's possible that something regressed.

Thanks and sorry for the delay! :smiley:

**Comment by prokod** [comment]
So here is the state of things:
* In Azkaban 3.34.0 we get a permission denied error between jobs (looking at the `flowLog` tab for the execution) and the details are in my last comment.
* In Azkaban 3.30.1 and 3.32.2 we do not see the above error, it passes this stage but within the job it fails on the following line:

```
echo "{\"param.doRun\": \"$DO_RUN\", \"param.input.partitions\": \"$INPUT_PARTITIONS\", \"param.spark.app.sessionLookAheadCalc\": \"$SESSION_LOOK_AHEAD_CALC\"}" > $JOB_OUTPUT_PROP_FILE
```

with the following error

```
08-09-2017 09:25:40 CEST preprocessing-hourly-forward_calcCheck INFO - {"param.doRun": "false", "param.input.partitions": "450", "param.spark.app.sessionLookAheadCalc": "true"}
08-09-2017 09:25:40 CEST preprocessing-hourly-forward_calcCheck INFO - /opt/azkaban-exec-server-3.32.2/executions/77/forwardFlow/../scripts/calcCheck.sh: line 286: /opt/azkaban-exec-server-3.32.2/executions/77/forwardFlow/preprocessing-hourly-forward_calcCheck_output_4944073578545338712_tmp: Permission denied
08-09-2017 09:25:40 CEST preprocessing-hourly-forward_calcCheck INFO - Process completed unsuccessfully in 7 seconds.
```

Btw, we are running Azkaban on CentOS 6

**Comment by prokod** [comment]
An example project is here:
[preprocessing-hourly_2.10_cdh5-0.11.9-SNAPSHOT-issue-1390.zip](https://github.com/azkaban/azkaban/files/1288173/preprocessing-hourly_2.10_cdh5-0.11.9-SNAPSHOT-issue-1390.zip)
This is  a stripped down one with only first two jobs, the second fails on our 3.30.1/3.32.2 installations

**Comment by reallocf** [comment]
@prokod that's interesting. I'm not seeing the same behavior when I try to run your job on our testing cluster here.

How is your execute-as-user executable permissioned?

**Comment by prokod** [comment]
It is according to Azkaban 3 doc (I hope):
`chmod 6050`
ownership `root:azkaban`

**Comment by reallocf** [comment]
Yes, that's the proper permissioning. Hmm, I'm not totally sure what's happening in your environment @prokod. I'm not familiar with the nuances of CentOS 6 - we're running our production instances on Redhat and I'm not sure if there's any substantive differences that could be the culprit there.

I'm working now on a fix on top of 3.34.0 that should make execute-as-user work as expected going forward. For now, I'd suggest running with execute.as.user=false unless you can figure out a workaround in your particular environment. My fix should be out in 3.35.0 or 3.36.0, so sometime later this month. Hopefully you can fully upgrade and turn execute-as-user on then.

Sorry that it's not working as expected for you out of the box!

**Comment by HappyRay** [comment]
@reallocf what's your proposed change?

**Comment by reallocf** [comment]
The fix I'm working on has to do with changing the permissions of the JOB_OUTPUT_PROP_FILE and JOB_PROP_FILE so they can be written to via the new execute-as-user executable. Because these files have been generated by the Azkaban process, they need to be updated to allow read/write access for the user.

Luckily, I can leverage some of the code I wrote for updating the permissions of the /executions/<exec_id> directory so it shouldn't be too much new work. Expect a PR in the next few days (as long as oncall doesn't take too much time).

**Comment by HappyRay** [comment]
Got it. Thanks. 
Shall we hold off the current deployment and patch the release so that we don't break the users that rely on this feature? What do you recommend?

**Comment by HappyRay** [comment]
Do we have an integration test for this feature yet?

**Comment by reallocf** [comment]
We do not need to hold off on current deployment - because we haven't upgraded the execute-as-user executable on any cluster except Yugioh, there won't be a problem.

**Comment by reallocf** [comment]
I'm also working on an integration test to ensure we don't regress in the ability to properly access this file in the future.

Question: @HappyRay do you know of any ways to unit test things like this? I haven't been able to think of any great way to test thing like this that are so reliant on the filesystem.

**Comment by lijixiang123** [comment]
@lhcg i have the same issue as you ,are you sovled it? can you tail me the detail methon?thx

**Comment by lijixiang123** [comment]
@lhcg hi! i had solved this issue, modify the ProcessJob.java 204 line transfer ture for false
final boolean isExecuteAsUser = this.sysProps.getBoolean(EXECUTE_AS_USER, false);
in  this  azkaban-common-0.1.0-SNAPSHOT.jar

**Comment by prokod** [comment]
The permission-ing approach taken in this project has a hidden assumption which is a crucial one! The user azkaban-exec service is running under (usually `azkaban`) should have `umask 002` which means that by default created file/dir will have also write permission set.

**Comment by zlessa** [comment]
See   https://blog.csdn.net/zhang527836447/article/details/99602022

By default, Azkaban does not allow root and Azkaban to perform jobs as proxy users.
