### ISSUE TITLE
Error writing initial node properties: SQLException: Duplicate entry

### ISSUE THREAD

**Issue by armisael** [azkaban/azkaban#1521]
When the same subflow is included twice, an exception is thrown on execution time.

Try with [this simple project](https://github.com/azkaban/azkaban/files/1348866/_project.zip), execute the `main` flow.

It throws:
```
ERROR - Error writing initial node properties
azkaban.executor.ExecutorManagerException: Error writing job echo
	at azkaban.executor.ExecutionJobDao.uploadExecutableNode(ExecutionJobDao.java:76)
	at azkaban.executor.JdbcExecutorLoader.uploadExecutableNode(JdbcExecutorLoader.java:182)
	at azkaban.execapp.JobRunner.uploadExecutableNode(JobRunner.java:625)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:581)
	at azkaban.execapp.JobRunner.run(JobRunner.java:552)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Duplicate entry '50006-echo-0' for key 'PRIMARY' Query: INSERT INTO execution_jobs (exec_id, project_id, version, flow_id, job_id, start_time, end_time, status, input_params, attempt) VALUES (?,?,?,?,?,?,?,?,?,?) Parameters: [50006, 18, 1, main,do-echo2:echo, echo, 1506947208767, -1, 110, [...], 0]
	at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:363)
	at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:490)
	at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:456)
	at azkaban.db.DatabaseOperator.update(DatabaseOperator.java:112)
	at azkaban.executor.ExecutionJobDao.uploadExecutableNode(ExecutionJobDao.java:71)
	... 9 more
```

The flow succeeds on azkaban 2.5.

**Comment by kunkun-tang** [comment]
#1523 will fix this problem. Thanks.
