### ISSUE TITLE
A job killed by job-level-SLA is not triggered to retry

### ISSUE THREAD

**Issue by forteph** [azkaban/azkaban#1551]
If I set SLA option for a job to be killed after a certain amount of time, Azkaban do not retry that job after killing it even though 'retries=2' is set in .job file.

Does anyone know why?

**Comment by chengren311** [comment]
hi, did the job get killed without retry? 
Can you share:
1. Screeshot of the SLA setting for that job
2. Job logs when the job was being killed.
3. job properties

**Comment by forteph** [comment]
[Screenshots]
![cap 2017-11-06 13-18-33-182](https://user-images.githubusercontent.com/619487/32425448-8eb8afde-c2f6-11e7-886c-412790aac041.jpg)
![cap 2017-11-06 13-19-41-139](https://user-images.githubusercontent.com/619487/32425449-8efb8444-c2f6-11e7-96e1-50a1843ea5cb.jpg)

[Logs]
06-11-2017 13:22:40 KST [JOB_NAME] ERROR - Kill has been called.
06-11-2017 13:22:45 KST [JOB_NAME] INFO - Process completed unsuccessfully in 125 seconds.
06-11-2017 13:22:45 KST [JOB_NAME] ERROR - Job run failed!
java.lang.RuntimeException: azkaban.jobExecutor.utils.process.ProcessFailureException
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:165)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:590)
	at azkaban.execapp.JobRunner.run(JobRunner.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: azkaban.jobExecutor.utils.process.ProcessFailureException
	at azkaban.jobExecutor.utils.process.AzkabanProcess.run(AzkabanProcess.java:131)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:159)
	... 7 more
[TIME] [JOB_NAME] ERROR - azkaban.jobExecutor.utils.process.ProcessFailureException cause: azkaban.jobExecutor.utils.process.ProcessFailureException
[TIME] [JOB_NAME] INFO - Finishing job [JOB_NAME] attempt: 0 at 1509942165182 with status KILLED


In fact, I tested setting SLA rule for only 1 job out of 4 parallel jobs, but it ended up killing all 4 jobs at the same time not just retrying SLA-set-job, which caused the whole flow end with 'Killed' status.

**Comment by chengren311** [comment]
Which AZ version are your running? Seems you are running pretty old version.

**Comment by forteph** [comment]
It's 3.1.0, however, I was noticed same thing happened in version 3.30.1. I don't think it's a version issue.
