### ISSUE TITLE
azkaban-3.36.0 error

### ISSUE THREAD

**Issue by diaowenyang** [azkaban/azkaban#1563]
HI:
  I get azkaban-3.36.0.zip and ./gradlew distTar -x test .
  And I start azkaban-web-server-0.1.0-SNAPSHOT/bin/azkaban-web-start.sh
 error follows :
2017-11-17 13:35:31 INFO  AzkabanServer:111 - Loading azkaban properties file
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - Exception in thread "main" 
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at java.lang.Class.getDeclaredMethods0(Native Method)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at java.lang.Class.getDeclaredMethods(Class.java:1975)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.ProviderMethodsModule.getProviderMethods(ProviderMethodsModule.java:132)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.ProviderMethodsModule.configure(ProviderMethodsModule.java:123)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:349)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.spi.Elements.getElements(Elements.java:110)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.Guice.createInjector(Guice.java:99)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.Guice.createInjector(Guice.java:73)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at com.google.inject.Guice.createInjector(Guice.java:62)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:209)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2017-11-17 13:35:31 ERROR StdOutErrRedirect:55 - 	... 14 more

**Comment by Ralnoc** [comment]
Make sure you are running the start command in the azkaban-web-server-0.1.0-SNAPSHOT directory.
