### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by dave-r12** [azkaban/azkaban#1614]
Hey, I wanted to try out azkaban and am attempting to build from source. Unfortunately I'm seeing test failures. I haven't spent time debugging them and wanted to see if there was something I was missing.
 
I'm running: `./gradlew clean build installDist`

And here is the test failures that I see:
```
azkaban.executor.ExecutorDaoTest > classMethod FAILED
    java.sql.SQLException: Table "EXECUTION_LOGS" already exists; SQL statement:
    CREATE TABLE execution_logs (
      exec_id     INT NOT NULL,
      name        VARCHAR(128),
      attempt     INT,
      enc_type    TINYINT,
      start_byte  INT,
      end_byte    INT,
      log         LONGBLOB,
      upload_time BIGINT,
      PRIMARY KEY (exec_id, name, attempt, start_byte)
    ) [42101-193] Query: CREATE TABLE execution_logs (
      exec_id     INT NOT NULL,
      name        VARCHAR(128),
      attempt     INT,
      enc_type    TINYINT,
      start_byte  INT,
      end_byte    INT,
      log         LONGBLOB,
      upload_time BIGINT,
      PRIMARY KEY (exec_id, name, attempt, start_byte)
    ) Parameters: []
        at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:363)
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:490)
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:376)
        at azkaban.db.DatabaseSetup.runTableScripts(DatabaseSetup.java:102)
        at azkaban.db.DatabaseSetup.createTables(DatabaseSetup.java:82)
        at azkaban.db.DatabaseSetup.updateDatabase(DatabaseSetup.java:57)
        at azkaban.test.Utils.initTestDB(Utils.java:36)
        at azkaban.executor.ExecutorDaoTest.setUp(ExecutorDaoTest.java:40)

azkaban.executor.ExecutorDaoTest > classMethod FAILED
    java.lang.NullPointerException
        at azkaban.executor.ExecutorDaoTest.destroyDB(ExecutorDaoTest.java:46)

azkaban.executor.ExecutionFlowDaoTest > classMethod FAILED
    java.sql.SQLException: Table "EXECUTION_LOGS" already exists; SQL statement:
    CREATE TABLE execution_logs (
      exec_id     INT NOT NULL,
      name        VARCHAR(128),
      attempt     INT,
      enc_type    TINYINT,
      start_byte  INT,
      end_byte    INT,
      log         LONGBLOB,
      upload_time BIGINT,
      PRIMARY KEY (exec_id, name, attempt, start_byte)
    ) [42101-193] Query: CREATE TABLE execution_logs (
      exec_id     INT NOT NULL,
      name        VARCHAR(128),
      attempt     INT,
      enc_type    TINYINT,
      start_byte  INT,
      end_byte    INT,
      log         LONGBLOB,
      upload_time BIGINT,
      PRIMARY KEY (exec_id, name, attempt, start_byte)
    ) Parameters: []
        at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:363)
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:490)
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:376)
        at azkaban.db.DatabaseSetup.runTableScripts(DatabaseSetup.java:102)
        at azkaban.db.DatabaseSetup.createTables(DatabaseSetup.java:82)
        at azkaban.db.DatabaseSetup.updateDatabase(DatabaseSetup.java:57)
        at azkaban.test.Utils.initTestDB(Utils.java:36)
        at azkaban.executor.ExecutionFlowDaoTest.setUp(ExecutionFlowDaoTest.java:56)

azkaban.executor.ExecutionFlowDaoTest > classMethod FAILED
    java.lang.NullPointerException
        at azkaban.executor.ExecutionFlowDaoTest.destroyDB(ExecutionFlowDaoTest.java:62)
```

**Comment by rschmidtz** [comment]
Same here, I'm trying to install the solo server version using Ubuntu 16.06 on AWS and when I run:

`cd azkaban; ./gradlew build installDist`

The build fails with the following exceptions:

`> Task :azkaban-common:test

azkaban.project.JdbcProjectImplTest > classMethod FAILED
    java.sql.SQLException: Table "EXECUTION_LOGS" already exists; SQL statement:
    CREATE TABLE execution_logs (
      exec_id     INT NOT NULL,
      name        VARCHAR(128),
      attempt     INT,
      enc_type    TINYINT,
      start_byte  INT,
      end_byte    INT,
      log         LONGBLOB,
      upload_time BIGINT,
      PRIMARY KEY (exec_id, name, attempt, start_byte)
    ) [42101-193] Query: CREATE TABLE execution_logs (
      exec_id     INT NOT NULL,
      name        VARCHAR(128),
      attempt     INT,
      enc_type    TINYINT,
      start_byte  INT,
      end_byte    INT,
      log         LONGBLOB,
      upload_time BIGINT,
      PRIMARY KEY (exec_id, name, attempt, start_byte)
    ) Parameters: []
        at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:363)
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:490)
        at org.apache.commons.dbutils.QueryRunner.update(QueryRunner.java:376)
        at azkaban.db.DatabaseSetup.runTableScripts(DatabaseSetup.java:102)
        at azkaban.db.DatabaseSetup.createTables(DatabaseSetup.java:82)
        at azkaban.db.DatabaseSetup.updateDatabase(DatabaseSetup.java:57)
        at azkaban.test.Utils.initTestDB(Utils.java:36)
        at azkaban.project.JdbcProjectImplTest.setUp(JdbcProjectImplTest.java:63)

azkaban.project.JdbcProjectImplTest > classMethod FAILED
    java.lang.NullPointerException
        at azkaban.project.JdbcProjectImplTest.destroyDB(JdbcProjectImplTest.java:69)

293 tests completed, 2 failed, 18 skipped


FAILURE: Build failed with an exception.
`

**Comment by HappyRay** [comment]
@kunkun-tang any idea?

**Comment by kunkun-tang** [comment]
Hi @dave-r12 @rschmidtz , we tried but can not reproduce this issue in our laptops. Would you mind run the below command to try a single test?
```
./gradlew :azkaban-common:test --tests azkaban.executor.ExecutorDaoTest
```

**Comment by kunkun-tang** [comment]
The possible cause is the test h2 database was not completely shut down and new jdbc test still can file the tables, for some reason.

**Comment by rschmidtz** [comment]
hi @kunkun-tang 

the command:

`./gradlew :azkaban-common:test --tests azkaban.executor.ExecutorDaoTest`

returns:

`Parallel execution with configuration on demand is an incubating feature.
Build cache is an incubating feature.

BUILD SUCCESSFUL in 5s
17 actionable tasks: 1 executed, 16 up-to-date
`

**Comment by kunkun-tang** [comment]
Thanks @rschmidtz .

As gradle output mentioned, 

> Build cache is an incubating feature.

If all azkaban JDBC tests are running simultaneously, we should run into this issue, reported by the users. The possible fix might be to ignore existing tables in  **azkaban.db.DatabaseSetup**

**Comment by HappyRay** [comment]
The message referenced above is standard gradle message. Are you sure it is gradle not our test that is the problem?

**Comment by zhpngpeng** [comment]
hey , i'm a student . i try to build this project local and i hope i could get some help here .

**Comment by kunkun-tang** [comment]
@HappyRay I didn't say it is a gradle problem. What I suspected is that tests running simultaneously could cause this issue. Every individual test run looks fine. So I would suggest ignoring table creation if table exists.

**Comment by HappyRay** [comment]
I thought all the DBs in these tests are created in memory independent of each other. Is it not the case?

**Comment by HappyRay** [comment]
How come travis never reported this issue to my knowledge?

**Comment by dave-r12** [comment]
I cloned and built the project on a fresh CentOS 7 host and it was successful. I'm running macOS on my laptop so there seems to be a difference between the 2.

**Comment by dave-r12** [comment]
I think I might have a lead here.. One difference I noticed is that on my local machine `JdbcTriggerImplTest` runs prior to `azkaban.executor.ExecutorDaoTest`. It appears it never closes the database. ExecutorDaoTest attemps to reuse the existing database and fails running the inserts.

If I add this to JdbcTriggerImplTest everything seems to pass:
```java
  @AfterClass
  public static void shutdown() {
    try {
      dataSource.close();
    } catch (SQLException e) {
      e.printStackTrace();
    }
  }
```

It also appers `AzkabanConnectionPoolTest` might be leaking it's connection as well.

I wasn't able to find an easy way to run tests in specific order via gradle.

**Comment by HappyRay** [comment]
@dave-r12 
Thanks!

> I wasn't able to find an easy way to run tests in specific order via gradle.

You shouldn't have to. And I would recommend against that as long-term fix to fix issues in the tests.

Ideally, tests should be independent of each other. If your theory is confirmed, I suggest we find a way to break this dependency. 

Sure, each test should do its best to release resources. In unit tests, however, wouldn't it be easier if tests are independent and the resources are automatically released when the test processes end? 

@kunkun-tang 
any comment?

**Comment by HappyRay** [comment]
@kunkun-tang in

public class JdbcTriggerImplTest {

  public static AzkabanDataSource dataSource = new AzkabanConnectionPoolTest.EmbeddedH2BasicDataSource();
Why does the dataSource field need to be static?
https://github.com/HappyRay/azkaban/blob/5ec24676202eba45355eb5e331c15556c8b5e274/azkaban-common/src/test/java/azkaban/trigger/JdbcTriggerImplTest.java#L46

**Comment by dave-r12** [comment]
> You shouldn't have to. And I would recommend against that as long-term fix to fix issues in the tests.

Ahh right, I agree. I was just mentioning that in hopes you could also reproduce the issue.

**Comment by kunkun-tang** [comment]
@HappyRay I think you are right, we should not need a static dependency for DataSource.
