### ISSUE TITLE
azkaban soloserver com.google.inject.ProvisionException: Unable to provision

### ISSUE THREAD

**Issue by ismailsimsek** [azkaban/azkaban#1640]
getting following error with 3.42.0 

azkaban.server.schedule.enable_quartz=true

```
2018/02/14 18:18:42.444 +0100 INFO [ExecJettyServerModule] [Azkaban] Jetty connector name: 0.0.0.0:12321, default header buffer size: 4096
2018/02/14 18:18:42.445 +0100 INFO [ExecJettyServerModule] [Azkaban] Jetty connector name: 0.0.0.0:12321, (if) new header buffer size: 4096
Exception in thread "main" com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, org.quartz.SchedulerConfigException: Thread count must be > 0
  at azkaban.scheduler.QuartzScheduler.<init>(QuartzScheduler.java:53)
  at azkaban.scheduler.QuartzScheduler.class(QuartzScheduler.java:49)
  while locating azkaban.scheduler.QuartzScheduler
    for the 11th parameter of azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:164)
  at azkaban.webapp.AzkabanWebServer.class(AzkabanWebServer.java:121)
  while locating azkaban.webapp.AzkabanWebServer
    for the 1st parameter of azkaban.soloserver.AzkabanSingleServer.<init>(AzkabanSingleServer.java:48)
  while locating azkaban.soloserver.AzkabanSingleServer

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at azkaban.soloserver.AzkabanSingleServer.main(AzkabanSingleServer.java:83)
Caused by: org.quartz.SchedulerConfigException: Thread count must be > 0
	at org.quartz.simpl.SimpleThreadPool.initialize(SimpleThreadPool.java:242)
	at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1288)
	at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1519)
	at azkaban.scheduler.QuartzScheduler.<init>(QuartzScheduler.java:59)
	at azkaban.scheduler.QuartzScheduler$$FastClassByGuice$$fb613eff.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 2 more
2018/02/14 18:19:42.439 +0100 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
```

**Comment by ismailsimsek** [comment]
shutdown  exception 

```
2018/02/14 18:30:42.727 +0100 ERROR [AzkabanWebServer] [Azkaban] Exception while shutting down quartz scheduler.
java.lang.NullPointerException
	at azkaban.scheduler.QuartzScheduler.shutdown(QuartzScheduler.java:105)
	at azkaban.webapp.AzkabanWebServer$1.run(AzkabanWebServer.java:239)
2018/02/14 18:30:42.729 +0100 INFO [AzkabanWebServer] [Azkaban] logging top memory consumer
```

**Comment by vblvbl** [comment]
How to solve the problem I have the same problem

**Comment by chengren311** [comment]
@kunkun-tang seems they are lacking required quartz properties in azkaban property file. Do you want to add doc for that?

**Comment by kunkun-tang** [comment]
Hi @vblvbl @ismailsimsek , quartz feature is under development. Are you looking for something new? Why do you want to enable quartz?

**Comment by ismailsimsek** [comment]
Hi @kunkun-tang  i did azkaban migration from 3.0 and i was testing new features locally, i thought it might be useful to post the exception message. we are not using this feature at the moment,  i believe this can be closed if its being addressed with new development.
