### ISSUE TITLE
3.45.2 build failed (1 test failed)

### ISSUE THREAD

**Issue by wilson-lauw** [azkaban/azkaban#1725]
Here is the output:

./gradlew build
Parallel execution with configuration on demand is an incubating feature.
Build cache is an incubating feature.

> Task :az-hadoop-jobtype-plugin:compileTestJava
Note: /home/traveloka/workspace/azkaban/az-hadoop-jobtype-plugin/src/test/java/azkaban/jobtype/TestHadoopJobUtilsFilterCommands.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :azkaban-common:test

azkaban.metric.MetricManagerTest > managerEmitterHandlingTest FAILED
    java.lang.AssertionError: Failed to report metric expected:<1> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at azkaban.metric.MetricManagerTest.managerEmitterHandlingTest(MetricManagerTest.java:92)

323 tests completed, 1 failed, 22 skipped

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':azkaban-common:test'.
> There were failing tests. See the report at: file:///home/traveloka/workspace/azkaban/azkaban-common/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
66 actionable tasks: 43 executed, 23 from cache

**Comment by juhoautio** [comment]
Seems to be my fault, caused by https://github.com/azkaban/azkaban/pull/1662. I must've missed synchronizing something.

**Comment by juhoautio** [comment]
It seems that the actual issue was leaking DateTimeUtils tweaks from other tests, see fix PR at https://github.com/azkaban/azkaban/pull/1735
