### ISSUE TITLE
Start azkaban exec server got error ERROR MySQLDataSource:103

### ISSUE THREAD

**Issue by FrommyMind** [azkaban/azkaban#1736]
In my conf/azkaban.properties the mysql configuration info as below.
database.type=mysql
mysql.port=3306
mysql.host=dnode04
mysql.database=azkaban
mysql.user=azkaban
mysql.password=password
mysql.numconnections=100

but when I try start azkaban exec server , I got error 
2018-04-17 10:39:13 ERROR MySQLDataSource:103 - Failed to find write-enabled DB connection. Wait 15 seconds and retry. No.Attempt = 1
java.sql.SQLException: Cannot create PoolableConnectionFactory (Access denied for user '**azkaban'@'dnode02**' (using password: YES))
        at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:2294)
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:2039)
        at azkaban.db.MySQLDataSource.getConnection(MySQLDataSource.java:76)
        at org.apache.commons.dbutils.AbstractQueryRunner.prepareConnection(AbstractQueryRunner.java:175)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:286)
        at azkaban.db.DatabaseOperator.query(DatabaseOperator.java:68)
        at azkaban.executor.ExecutorDao.fetchExecutor(ExecutorDao.java:63)
        at azkaban.executor.JdbcExecutorLoader.fetchExecutor(JdbcExecutorLoader.java:273)
        at azkaban.execapp.AzkabanExecutorServer.insertExecutorEntryIntoDB(AzkabanExecutorServer.java:265)
        at azkaban.execapp.AzkabanExecutorServer.start(AzkabanExecutorServer.java:243)
        at azkaban.execapp.AzkabanExecutorServer.launch(AzkabanExecutorServer.java:153)
        at azkaban.execapp.AzkabanExecutorServer.main(AzkabanExecutorServer.java:149)

It try to use dnode02 which my azkanban exec server installed on .

Yes,  I have start azkaban exec server with the configuration mysql.host=localhost, but even I modified the properties, It doesn't work.

**Comment by kunkun-tang** [comment]
please type `host localhost`, and let me know what it returns.

**Comment by RoryLiuwenxuan** [comment]
This error is azkaban can't communicate with mysql, Even if you set user:azkaban can remote login already.
I got this erro too when I installed mysql by yum.
change DB to maria-db fix it.

step-1
vi /etc/yum.repos.d/MariaDB.repo
#MariaDB.repo
       [mariadb]
       name = MariaDB
       baseurl =http://yum.mariadb.org/10.2/centos7-amd64
       gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
       gpgcheck=1
step-2
linux shell>yum install MariaDB-server MariaDB-client -y
linux shell>systemctl start mariadb
linux shell>systemctl enable mariadb
step-3
linux shell>mysql
mysql> CREATE USER'azkaban'@'％'IDENTIFIED BY 'azkaban';
mysql> GRANT SELECT,INSERT,UPDATE,DELETE ONazkaban.* to 'azkaban'@'%' WITH GRANT OPTION;
mysql> use azkaban
step-4
mysql> source/software/azkaban-master/azkaban-db/build/sql/create-all-sql-0.1.0-SNAPSHOT.sql
mysql> insert into executors(host,port)values("ip1 or hostname1",12321);
mysql> insert into executors(host,port)values("ip2 or hostname2",12321);

**step-5(important)**
mysql> update executos set active=1;

now ,restart azkaban-web-server and azkaban-executor-server.
Wish you success.

You can refer to the installation part of DB in my microblog.
https://mp.csdn.net/postedit/79944117

**Comment by RoryLiuwenxuan** [comment]
can you login mysql by execut “mysql -hyourIP -uazkabanUser -pazkabanPassWord”,if you can’t,please try my way. 
A few minutes of trying to change a chance of success.
good luck

**Comment by kunkun-tang** [comment]
There must be something wrong with the database connection.  Are you able to see any errors from Mysql Server logs?

**Comment by li-afaris** [comment]
Hi @RoryLiuwenxuan,

Quick question, did you remember to run `flush privileges` after adding the azkaban user to mariadb?  It's usually required when updating grant statements to flush the internal caches.  More info can be found here: https://mariadb.com/kb/en/library/flush/

Thanks

**Comment by porthunt** [comment]
Happened to me recently. I was using MySQL engine 8.0.15, changed to 5.7.21 and it works now.

**Comment by dgqypl** [comment]
> Happened to me recently. I was using MySQL engine 8.0.15, changed to 5.7.21 and it works now.

you can go to the directory `azkaban/azkaban-exec-server/build/install/azkaban-exec-server/lib`, delete the `mysql-connector-java-5.1.28.jar` and add the `mysql-connector-java-8.0.22.jar`, then restart exec server process, it works! try it out.

**Comment by SoYou1669** [comment]
> > Happened to me recently. I was using MySQL engine 8.0.15, changed to 5.7.21 and it works now.
> 
> you can go to the directory `azkaban/azkaban-exec-server/build/install/azkaban-exec-server/lib`, delete the `mysql-connector-java-5.1.28.jar` and add the `mysql-connector-java-8.0.22.jar`, then restart exec server process, it works! try it out.

I used your method and it work  successfully
