### ISSUE TITLE
a flow execution status stays at "PREPARING"

### ISSUE THREAD

**Issue by gao634209276** [azkaban/azkaban#1805]
version: 3.43.0 
mode: Multiple Executor Mode
mutiple executor config use default:
azkaban.use.multiple.executors=true
azkaban.executorselector.filters=StaticRemainingFlowSize,MinimumFreeMemory,CpuStatus
azkaban.executorselector.comparator.NumberOfAssignedFlowComparator=1
azkaban.executorselector.comparator.Memory=1
azkaban.executorselector.comparator.LastDispatched=1
azkaban.executorselector.comparator.CpuUsage=1

It was normally scheduled for two months, This case has never happened, but yesterday a flow scheduled failed with status 'PREPARING', the webserver logs:
```
2018/06/17 10:00:15.600 +0800 INFO [TriggerManager] Doing trigger actions Execute flow <a_flow> from project <a_project> for Trigger Id: 17, Description: Trigger from SimpleTimeTrigger with trigger condition of BasicTimeChecker_1.eval() and expire condition of EndTimeChecker_1.eval(), Execute flow adver from project <a_project>
2018/06/17 10:00:15.600 +0800 INFO [ExecuteFlowAction] Invoking flow <a_project>.<a_flow>
2018/06/17 10:00:15.600 +0800 INFO [ExecutorManager] Submitting execution flow <a_flow> by <user>
2018/06/17 10:00:15.619 +0800 INFO [ExecutionFlowDao] Flow given <a_flow> given id 353
2018/06/17 10:00:15.638 +0800 INFO [ExecuteFlowAction] Invoked flow <a_project>.<a_flow>
2018/06/17 10:00:15.638 +0800 INFO [Condition] Done resetting checkers. The next check time will be 2018-06-18T10:00:00.000+08:00
2018/06/17 10:00:15.638 +0800 INFO [JdbcTriggerImpl] Updating trigger 17 into db.
2018/06/17 10:00:15.646 +0800 INFO [TriggerManager] Doing trigger actions Execute flow <b_flow> from project <b_project> for Trigger Id: 29, Description: Trigger from SimpleTimeTrigger with trigger condition of BasicTimeChecker_1.eval() and expire condition of EndTimeChecker_1.eval(), Execute flow  <b_flow> from project <b_project>
2018/06/17 10:00:15.646 +0800 INFO [ExecuteFlowAction] Invoking flow <b_project>.<b_flow>
2018/06/17 10:00:15.646 +0800 INFO [ExecutorManager] Submitting execution flow <b_project> by <user>
2018/06/17 10:00:15.652 +0800 INFO [ExecutorManager] Successfully refreshed executor:<exec_hostname>:12321 (id: 7) with executor info : ExecutorInfo{remainingMemoryPercent=83.06233109982398, remainingMemoryInMB=53512, remainingFlowCapacity=30, numberOfAssignedFlows=0, lastDispatchedTime=1529195415672, cpuUsage=1.08}
2018/06/17 10:00:15.652 +0800 INFO [ExecutorManager] Using dispatcher for execution id :353
2018/06/17 10:00:15.663 +0800 INFO [ExecutionFlowDao] Flow given <b_flow> given id 354
2018/06/17 10:00:15.679 +0800 INFO [ExecuteFlowAction] Invoked flow <b_project>.<b_flow>
2018/06/17 10:00:15.679 +0800 INFO [Condition] Done resetting checkers. The next check time will be 2018-06-18T10:00:00.000+08:00
2018/06/17 10:00:15.679 +0800 INFO [JdbcTriggerImpl] Updating trigger 29 into db.
2018/06/17 10:00:15.720 +0800 INFO [ExecutorManager] Successfully dispatched exec 353 with error count 0
2018/06/17 10:00:15.720 +0800 INFO [ExecutorManager] Using dispatcher for execution id :354
2018/06/17 10:00:15.745 +0800 ERROR [ExecutorManager] Rolling back executor assignment for execution id:354
2018/06/17 10:00:15.794 +0800 WARN [ExecutorManager] Executor <exec_hostname>:12321 (id: 7) responded with exception for exec: 354
2018/06/17 10:00:15.794 +0800 INFO [ExecutorManager] Reached handleDispatchExceptionCase stage for exec 354 with error count 0
2018/06/17 10:00:15.794 +0800 ERROR [ExecutorManager] Failed to process queued flow
2018/06/17 10:00:15.799 +0800 ERROR [ExecutorManager] QueueProcessorThread Interrupted. Probably to shut down.
2018/06/17 10:22:11.024 +0800 INFO [ExecutorManager] Cleaning old logs from execution_logs
2018/06/17 10:22:11.024 +0800 INFO [ExecutorManager] Cleaning old log files before 2018-03-25T10:22:11.024+08:00
2018/06/17 10:22:11.149 +0800 INFO [ExecutorManager] Cleaned up 0 log entries.
2018/06/17 10:22:11.149 +0800 INFO [ExecutorManager] log clean up time: 0 seconds.
```

executor server log that:

```
2018/06/17 10:00:15.651 +0800 INFO [ServerStatisticsServlet] System load : 1.08
2018/06/17 10:00:15.695 +0800 INFO [ExecutorServlet] User  has called action execute on 353
2018/06/17 10:00:15.700 +0800 INFO [FlowPreparer] Project already cached. Skipping download. ProjectVersion{projectId=22, version=1, installedDir=projects/22.1}
2018/06/17 10:00:15.720 +0800 INFO [FlowPreparer] Flow Preparation complete. [execid: 353, path: executions/353]
2018/06/17 10:00:15.720 +0800 INFO [FlowRunnerManager] Configuring Azkaban metrics tracking for flow runner object
2018/06/17 10:00:15.721 +0800 INFO [<flow_a>] Assigned executor : <exec_hostname>:12321
2018/06/17 10:00:15.722 +0800 INFO [<flow_a>] Running execid:353 flow:<flow_a> project:22 version:1
2018/06/17 10:00:15.722 +0800 INFO [<flow_a>] Updating initial flow directory.
2018/06/17 10:00:15.730 +0800 INFO [<flow_a>] Fetching job and shared properties.
2018/06/17 10:00:15.734 +0800 INFO [<flow_a>] Starting flows
2018/06/17 10:00:15.734 +0800 INFO [<flow_a>] Running flow '<flow_a>'.
2018/06/17 10:00:15.734 +0800 INFO [ExecutorServlet] User  has called action execute on 354
2018/06/17 10:00:15.739 +0800 WARN [JdbcProjectImpl] Project 22 version 1 property <custom_properties> is empty.
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] azkaban.executor.ExecutorManagerException: Error loading flow with exec 354
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at azkaban.execapp.FlowRunnerManager.submitFlow(FlowRunnerManager.java:324)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at azkaban.execapp.ExecutorServlet.handleAjaxExecute(ExecutorServlet.java:276)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at azkaban.execapp.ExecutorServlet.doGet(ExecutorServlet.java:124)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.Server.handle(Server.java:326)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
2018/06/17 10:00:15.745 +0800 ERROR [StdOutErrRedirect] 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
2018/06/17 10:00:15.745 +0800 ERROR [ExecutorServlet] Error loading flow with exec 354
2018/06/17 10:00:15.763 +0800 INFO [<flow_a>] Configuring Azkaban metrics tracking for jobrunner object
2018/06/17 10:00:15.763 +0800 INFO [<flow_a>] Submitting job '<job_of_flow_a>' to run.
2018/06/17 10:00:15.764 +0800 INFO [<flow_a>] Created file appender for job <job_of_flow_a>
2018/06/17 10:00:15.765 +0800 INFO [<flow_a>] Attached file appender for job <job_of_flow_a>
2018/06/17 10:00:15.765 +0800 INFO [ExecutorDao] Uploading flowId <flow_a>
2018/06/17 10:00:15.772 +0800 INFO [<flow_a>] Job Started: <job_of_flow_a>
```

I read some issue of 'PREPARING' error, but I cannot confirm whether it is the same case. help me !

**Comment by gao634209276** [comment]
And I have two issues at this case:
It's hard to find reason with this wrong message. can azkaban log more information? 
when the scheduling error, why can't send an alarm or try again ?

**Comment by abha10** [comment]
Could be a memory related issue.
Check issue #610. Might help. 
Basically it says to remove 'MinimumFreeMemory' filter from azkaban.properties file.

**Comment by yichao0803** [comment]
> Could be a memory related issue.
> Check issue #610. Might help.
> Basically it says to remove 'MinimumFreeMemory' filter from azkaban.properties file.

I encountered the same problem. After performing the following operations, the system can run normally:
In the `azkaban-web-server/conf/azkaban.properties` configuration file, delete `MinimumFreeMemory` in `azkaban.executorselector.filters`
Reference link:
[https://azkaban.readthedocs.io/en/latest/configuration.html?highlight=MinimumFreeMemory#multiple-executor-mode-parameters](https://azkaban.readthedocs.io/en/latest/configuration.html?highlight=MinimumFreeMemory#multiple-executor-mode-parameters)
