### ISSUE TITLE
Job type 'java' is unrecognized. 

### ISSUE THREAD

**Issue by aiwotantan** [azkaban/azkaban#1838]
06-07-2018 15:08:57 CST MondayJob INFO - Starting job MondayJob at 1530860937324
06-07-2018 15:08:57 CST MondayJob INFO - azkaban.webserver.url property was not set
06-07-2018 15:08:57 CST MondayJob INFO - job JVM args: -Dazkaban.flowid=TuesdayJob -Dazkaban.execid=126 -Dazkaban.jobid=MondayJob -Duser.timezone=Asia/Shanghai
06-07-2018 15:08:57 CST MondayJob INFO - user.to.proxy property was not set, defaulting to submit user azkaban
06-07-2018 15:08:57 CST MondayJob INFO - Building java job executor. 
06-07-2018 15:08:57 CST MondayJob ERROR - Failed to build job executor for job MondayJobJob type 'java' is unrecognized. Could not construct job[{azkaban.job.id: MondayJob, azkaban.job.attempt: 0, classpath: ${param.classpath}, method.run: run, type: java, dependencies: , azkaban.job.attachment.file: /data/azkaban/executions/126/bigdata_java_job/_job.126.MondayJob.attach, working.dir: /data/azkaban/executions/126/bigdata_java_job, job.class: jobs.MondayJob, jvm.args: -Dazkaban.flowid=TuesdayJob -Dazkaban.execid=126 -Dazkaban.jobid=MondayJob -Duser.timezone=Asia/Shanghai, user.to.proxy: azkaban, main.args: ${indexDay}, azkaban.job.outnodes: TuesdayJob, azkaban.job.metadata.file: _job.126.MondayJob.meta, azkaban.memory.check: true, azkaban.job.innodes: ,  parent = {azkaban.flow.start.milliseconds: 151, azkaban.flow.start.year: 2018, azkaban.flow.start.timezone: Asia/Shanghai, azkaban.flow.projectid: 16, azkaban.flow.start.second: 57, azkaban.flow.submituser: azkaban, azkaban.flow.projectversion: 3, azkaban.flow.start.minute: 08, azkaban.flow.execid: 126, azkaban.flow.projectname: bigdata, azkaban.flow.start.month: 07, azkaban.flow.start.hour: 15, azkaban.flow.uuid: f72ac387-db99-40ee-a8e2-1c4dab1845b4, azkaban.flow.flowid: TuesdayJob, azkaban.flow.start.day: 06, azkaban.flow.projectlastchangedby: azkaban, azkaban.flow.projectlastchangeddate: 1530860077990, azkaban.flow.start.timestamp: 2018-07-06T15:08:57.151+08:00,  parent = {param.creationUser: dengzs, param.classpath: ./lib/*, }}}] of type[java].
06-07-2018 15:08:57 CST MondayJob ERROR - Failed to build job type
azkaban.jobtype.JobTypeManagerException: Failed to build job executor for job MondayJob
	at azkaban.jobtype.JobTypeManager.buildJobExecutor(JobTypeManager.java:363)
	at azkaban.execapp.JobRunner.prepareJob(JobRunner.java:700)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:594)
	at azkaban.execapp.JobRunner.run(JobRunner.java:561)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: azkaban.jobExecutor.utils.JobExecutionException: Job type 'java' is unrecognized. Could not construct job[{azkaban.job.id: MondayJob, azkaban.job.attempt: 0, classpath: ${param.classpath}, method.run: run, type: java, dependencies: , azkaban.job.attachment.file: /data/azkaban/executions/126/bigdata_java_job/_job.126.MondayJob.attach, working.dir: /data/azkaban/executions/126/bigdata_java_job, job.class: jobs.MondayJob, jvm.args: -Dazkaban.flowid=TuesdayJob -Dazkaban.execid=126 -Dazkaban.jobid=MondayJob -Duser.timezone=Asia/Shanghai, user.to.proxy: azkaban, main.args: ${indexDay}, azkaban.job.outnodes: TuesdayJob, azkaban.job.metadata.file: _job.126.MondayJob.meta, azkaban.memory.check: true, azkaban.job.innodes: ,  parent = {azkaban.flow.start.milliseconds: 151, azkaban.flow.start.year: 2018, azkaban.flow.start.timezone: Asia/Shanghai, azkaban.flow.projectid: 16, azkaban.flow.start.second: 57, azkaban.flow.submituser: azkaban, azkaban.flow.projectversion: 3, azkaban.flow.start.minute: 08, azkaban.flow.execid: 126, azkaban.flow.projectname: bigdata, azkaban.flow.start.month: 07, azkaban.flow.start.hour: 15, azkaban.flow.uuid: f72ac387-db99-40ee-a8e2-1c4dab1845b4, azkaban.flow.flowid: TuesdayJob, azkaban.flow.start.day: 06, azkaban.flow.projectlastchangedby: azkaban, azkaban.flow.projectlastchangeddate: 1530860077990, azkaban.flow.start.timestamp: 2018-07-06T15:08:57.151+08:00,  parent = {param.creationUser: dengzs, param.classpath: ./lib/*, }}}] of type[java].
	at azkaban.jobtype.JobTypeManager.buildJobExecutor(JobTypeManager.java:324)
	... 8 more
06-07-2018 15:08:57 CST MondayJob ERROR - Job run failed preparing the job.
06-07-2018 15:08:57 CST MondayJob INFO - Finishing job MondayJob at 1530860937380 with status FAILED

**Comment by aiwotantan** [comment]
good good study,day day up!

**Comment by yangzhixiao** [comment]
@aiwotantan your English is very six !!!

**Comment by happyapple668** [comment]
six six six

**Comment by kezhenxu94** [comment]
@aiwotantan use `javaprocess` instead

**Comment by Ganx** [comment]
> @aiwotantan use `javaprocess` instead

demo??

**Comment by EEGHT** [comment]
@aiwotantan old tie,six six six
