### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration

### ISSUE THREAD

**Issue by yangzhixiao** [azkaban/azkaban#1853]
2018/07/16 13:21:33.119 +0800 INFO [test] [Azkaban] Job Started: task
2018/07/16 13:22:19.972 +0800 ERROR [HadoopConfigurationInjector] [Azkaban] Encountered error while preparing the Hadoop configuration resource file
java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
	at azkaban.jobtype.HadoopConfigurationInjector.prepareResourcesToInject(HadoopConfigurationInjector.java:88)
	at azkaban.jobtype.HadoopHiveJob.run(HadoopHiveJob.java:84)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:784)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:600)
	at azkaban.execapp.JobRunner.run(JobRunner.java:561)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more

**Comment by chris9692** [comment]
The cause of this error might be in bin/internal/internal-start-executor.sh. I was able to make it work with following tweaks. 

if [ "$HADOOP_HOME" != "" ]; then
        echo "Using Hadoop from $HADOOP_HOME"
        #CLASSPATH=$CLASSPATH:$HADOOP_HOME/conf:$HADOOP_HOME/*
_CLASSPATH=$CLASSPATH:$HADOOP_HOME/conf:$HADOOP_HOME/*:$HADOOP_HOME/share/hadoop/common/*:$HADOOP_HOME/share/hadoop/common/lib/*:$HADOOP_HOME/share/hadoop/hdfs/*:$HADOOP_HOME/share/hadoop/hdfs/lib/*:$HADOOP_HOME/share/hadoop/yarn/*:$HADOOP_HOME/share/hadoop/yarn/lib/*:$HADOOP_HOME/share/hadoop/mapreduce/*:$HADOOP_HOME/share/hadoop/mapreduce/lib/*_
        JAVA_LIB_PATH="-Djava.library.path=$HADOOP_HOME/lib/native/Linux-amd64-64"
else
        echo "Error: HADOOP_HOME is not set. Hadoop job types will not run properly."
fi

**Comment by bigdogdog** [comment]
I encountered a similar error while starting the azkaban web-server. 
Then I solved the problem by these following operations:
1. open azkaban-common/build.gradle
2. change "compileOnly" to "compile" for hadoop related packages
3. rebuild packages by ./gradlew build -x test

It seems that the compileOnly command didn't add the dependency while building and caused the error.
Hope it will be helpful.
