### ISSUE TITLE
ERROR happens while using condition parameter 

### ISSUE THREAD

**Issue by huaxuehuaxue** [azkaban/azkaban#1897]
@jamiesjc  any idea about this? 

07-08-2018 09:23:06 CST conditional_flow1 ERROR - Invalid expression.
javax.script.ScriptException: &lt;eval&gt;:1:1 Expected ; but found {
${jobA:azkaban.server.name} == 'bar'
 ^ in &lt;eval&gt; at line number 1 at column number 1
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at azkaban.execapp.FlowRunner.evaluateExpression(FlowRunner.java:989)
	at azkaban.execapp.FlowRunner.isConditionOnRuntimeVariableMet(FlowRunner.java:948)
	at azkaban.execapp.FlowRunner.getImpliedStatus(FlowRunner.java:905)
	at azkaban.execapp.FlowRunner.runReadyJob(FlowRunner.java:572)
	at azkaban.execapp.FlowRunner.progressGraph(FlowRunner.java:524)
	at azkaban.execapp.FlowRunner.runFlow(FlowRunner.java:422)
	at azkaban.execapp.FlowRunner.run(FlowRunner.java:249)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: jdk.nashorn.internal.runtime.ParserException: &lt;eval&gt;:1:1 Expected ; but found {
${jobA:azkaban.server.name} == 'bar'
 ^
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:294)
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:279)
	at jdk.nashorn.internal.parser.AbstractParser.expectDontAdvance(AbstractParser.java:350)
	at jdk.nashorn.internal.parser.AbstractParser.expect(AbstractParser.java:337)
	at jdk.nashorn.internal.parser.Parser.endOfLine(Parser.java:3372)
	at jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1160)
	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:967)
	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
	at jdk.nashorn.internal.parser.Parser.program(Parser.java:709)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:283)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
	... 16 more
07-08-2018 09:23:06 CST conditional_flow1 INFO - Cancelling 'jobC' due to prior errors.

**Comment by jamiesjc** [comment]
Hi @huaxuehuaxue, thanks for trying out this new feature.
Is it the test case `runFlowOnJobPropsCondition`? I'm not able to reproduce the same error locally. How often do you see this and did you see it on the latest master?
It would be great if you could provide me more logs so that I can debug this issue. Thanks!

**Comment by huaxuehuaxue** [comment]
Hi @jamiesjc , thanks for replying. I followed this instruction page:  https://github.com/azkaban/azkaban/pull/1825          , and I am using exactly the same example  as below:
################################start#####################
nodes:
 - name: JobA
   type: command
   config:
     command: echo {"param1":"1"} > $JOB_OUTPUT_PROP_FILE 

 - name: JobB
   type: command
   config:
     command: echo {"param2":"6"} > $JOB_OUTPUT_PROP_FILE 

 - name: JobC
   type: command
   dependsOn:
     - JobA
     - JobB
   config:
     command: echo “This is JobC.”
   condition: ${JobA:param1} == 1 && ${JobB:param2} > 5
################################end#####################
I checked the code related while running , I found out the reason why "JobC" cancelled on my MAC is "command: echo {"param2":"6"} > $JOB_OUTPUT_PROP_FILE " didn't work out.  here is the log:
![2018-08-08 08 56 48](https://user-images.githubusercontent.com/6133248/43810259-46ae28e2-9ae9-11e8-8879-301231da4b07.png)


and the further reason is: there is nothing execution tmp file.

**Comment by jamiesjc** [comment]
Hi @huaxuehuaxue, you can put the command `echo {"param1":"1"} > $JOB_OUTPUT_PROP_FILE` inside a shell script e.g., write_to_props.sh and change the original command section to `command: bash ./write_to_props.sh`. For the command job, it seems the redirect output function is not implemented in our process builder currently. So I would suggest using the shell script instead. I'll modify the documentation as well. I've attached a sample zip as well. 
[write_to_output.zip](https://github.com/azkaban/azkaban/files/2271492/write_to_output.zip)
Let me know if you see any other issue. Thanks again for trying out this new feature!
