### ISSUE TITLE
Error when Building Azkaban

### ISSUE THREAD

**Issue by AndresJWC** [azkaban/azkaban#1900]
I was following the installation instructions and but when doing the second step:
Build Azkaban and create an installation: run cd azkaban; ./gradlew build installDist

But I get the following message 
* What went wrong:
A problem occurred configuring project ':az-exec-util'.
> Exception thrown while executing model rule: NativeBinaryRules#assignTools(Nat
iveBinarySpec, NativeToolChainRegistryInternal, ProjectLayout)
   > java.lang.NullPointerException (no error message)

I have been googloing but I havent been able to find anything useful 

I ran the stacktrace option but didn't get anything that I feel could help 
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring pro
ject ':az-exec-util'.
        at org.gradle.execution.TaskNameResolver.discoverTasks(TaskNameResolver.
java:100)
        at org.gradle.execution.TaskNameResolver.access$100(TaskNameResolver.jav
a:32)
        at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult
.collect(TaskNameResolver.java:171)
        at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult
.collect(TaskNameResolver.java:181)
        at org.gradle.execution.TaskNameResolver$MultiProjectTaskSelectionResult
.collectTasks(TaskNameResolver.java:166)
        at org.gradle.execution.TaskNameResolver.selectWithName(TaskNameResolver
.java:55)
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:103)

        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:81)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(Com
mandLineTaskParser.java:42)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.config
ure(TaskNameResolvingBuildConfigurationAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configur
e(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$0
00(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.procee
d(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(Defau
ltTasksBuildExecutionAction.java:44)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configur
e(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$0
00(DefaultBuildConfigurationActionExecuter.java:25)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.procee
d(DefaultBuildConfigurationActionExecuter.java:54)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.co
nfigure(ExcludedTaskFilteringBuildConfigurationAction.java:47)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.configur
e(DefaultBuildConfigurationActionExecuter.java:48)
        at org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(D
efaultBuildConfigurationActionExecuter.java:36)
        at org.gradle.initialization.DefaultGradleLauncher$CalculateTaskGraph.ru
n(DefaultGradleLauncher.java:286)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu
ildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu
ildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(De
faultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:110)
        at org.gradle.initialization.DefaultGradleLauncher.constructTaskGraph(De
faultGradleLauncher.java:181)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:136)
        at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultG
radleLauncher.java:115)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBui
ldController.java:78)
        at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBui
ldController.java:75)
        at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultW
orkerLeaseService.java:152)
        at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBu
ildController.java:100)
        at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildC
ontroller.java:75)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
cuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
ctionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(
ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(R
unAsBuildOperationBuildActionRunner.java:43)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu
ildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBu
ildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(De
faultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:110)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(Run
AsBuildOperationBuildActionRunner.java:40)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.ru
n(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:49)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:32)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(Bu
ildTreeScopeBuildActionExecuter.java:39)
        at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(Bu
ildTreeScopeBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.ex
ecute(ContinuousBuildActionExecuter.java:80)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.ex
ecute(ContinuousBuildActionExecuter.java:53)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter
.execute(ServicesSetupBuildActionExecuter.java:57)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter
.execute(ServicesSetupBuildActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.
execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.
execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildAct
ionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
        at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildAct
ionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecu
ter.execute(StartParamsValidatingActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecu
ter.execute(StartParamsValidatingActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExe
cuter.execute(SessionFailureReportingActionExecuter.java:59)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExe
cuter.execute(SessionFailureReportingActionExecuter.java:44)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execu
te(SetupLoggingActionExecuter.java:45)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execu
te(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBu
ild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(
WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute
(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.
execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
ardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
ardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For
wardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogA
ndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien
t.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu
ild(EstablishBuildEnvironment.java:82)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:122)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.
run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(Daemon
StateCoordinator.java:295)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecu
torImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnabl
e.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.model.internal.core.ModelRuleExecutionException: Exception
 thrown while executing model rule: NativeBinaryRules#assignTools(NativeBinarySp
ec, NativeToolChainRegistryInternal, ProjectLayout)
        at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(De
faultModelRegistry.java:490)
        at org.gradle.model.internal.registry.DefaultModelRegistry.access$700(De
faultModelRegistry.java:71)
        at org.gradle.model.internal.registry.DefaultModelRegistry$RunModelActio
n.apply(DefaultModelRegistry.java:1184)
        at org.gradle.model.internal.registry.DefaultModelRegistry.transitionTo(
DefaultModelRegistry.java:390)
        at org.gradle.model.internal.registry.DefaultModelRegistry.transition(De
faultModelRegistry.java:469)
        at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrMayb
eLater(DefaultModelRegistry.java:233)
        at org.gradle.model.internal.registry.DefaultModelRegistry.atStateOrLate
r(DefaultModelRegistry.java:220)
        at org.gradle.api.internal.tasks.DefaultTaskContainer.discoverTasks(Defa
ultTaskContainer.java:229)
        at org.gradle.execution.TaskNameResolver.discoverTasks(TaskNameResolver.
java:98)
        ... 87 more
Caused by: java.lang.NullPointerException
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLi
neToolVersionLocator.readInstall(CommandLineToolVersionLocator.java:131)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLi
neToolVersionLocator.parseJson(CommandLineToolVersionLocator.java:99)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.CommandLi
neToolVersionLocator.locateInstalls(CommandLineToolVersionLocator.java:60)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.version.AbstractV
isualStudioVersionLocator.getVisualStudioInstalls(AbstractVisualStudioVersionLoc
ator.java:32)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.DefaultVisualStud
ioLocator.locateInstallsWith(DefaultVisualStudioLocator.java:117)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.DefaultVisualStud
ioLocator.initializeVisualStudioInstalls(DefaultVisualStudioLocator.java:102)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.DefaultVisualStud
ioLocator.determineDefaultInstall(DefaultVisualStudioLocator.java:226)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.DefaultVisualStud
ioLocator.locateDefaultVisualStudioInstall(DefaultVisualStudioLocator.java:97)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.VisualCppToolChai
n.checkAvailable(VisualCppToolChain.java:165)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.VisualCppToolChai
n.getAvailability(VisualCppToolChain.java:153)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.VisualCppToolChai
n.select(VisualCppToolChain.java:116)
        at org.gradle.nativeplatform.toolchain.internal.msvcpp.VisualCppToolChai
n.select(VisualCppToolChain.java:144)
        at org.gradle.nativeplatform.toolchain.internal.DefaultNativeToolChainRe
gistry.getForPlatform(DefaultNativeToolChainRegistry.java:76)
        at org.gradle.nativeplatform.toolchain.internal.DefaultNativeToolChainRe
gistry.getForPlatform(DefaultNativeToolChainRegistry.java:70)
        at org.gradle.nativeplatform.toolchain.internal.DefaultNativeToolChainRe
gistry.getForPlatform(DefaultNativeToolChainRegistry.java:33)
        at org.gradle.nativeplatform.internal.configure.NativeBinaryRules.toolCh
ainFor(NativeBinaryRules.java:120)
        at org.gradle.nativeplatform.internal.configure.NativeBinaryRules.assign
ToolsToNativeBinary(NativeBinaryRules.java:44)
        at org.gradle.nativeplatform.internal.configure.NativeBinaryRules.assign
Tools(NativeBinaryRules.java:39)
        at org.gradle.nativeplatform.internal.configure.NativeBinaryRules.assign
Tools(NativeBinaryRules.java:34)
        at org.gradle.model.internal.method.WeaklyTypeReferencingMethod.invoke(W
eaklyTypeReferencingMethod.java:100)
        at org.gradle.model.internal.inspect.DefaultModelRuleInvoker.invoke(Defa
ultModelRuleInvoker.java:36)
        at org.gradle.model.internal.inspect.MethodBackedModelAction.execute(Met
hodBackedModelAction.java:45)
        at org.gradle.model.internal.inspect.AbstractMethodRuleAction.execute(Ab
stractMethodRuleAction.java:48)
        at org.gradle.model.internal.inspect.ModelRuleExtractor$DefaultExtracted
RuleSource$ContextualizedModelAction.execute(ModelRuleExtractor.java:515)
        at org.gradle.model.internal.registry.DefaultModelRegistry$4.run(Default
ModelRegistry.java:485)
        at org.gradle.model.internal.registry.RuleContext.run(RuleContext.java:4
2)
        at org.gradle.model.internal.registry.DefaultModelRegistry.fireAction(De
faultModelRegistry.java:482)
        ... 95 more

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

Any help would be much appretiated.

Thanks.
Regards

**Comment by subash247** [comment]
gradlew build installDist
juz run this command alone

**Comment by geetha-rangaswamaiah** [comment]
Hi @AndresJWC, is this issue resolved? I'm also facing the same issue.

**Comment by sadanspace** [comment]
Hi @geetha-rangaswamaiah 

on Windows. 

I used the following command.
```
gradlew.bat build installDist --debug
```
Print out the following information.
The reason is that VS2019 was not installed successfully before, **my solution is to uninstall VS2019** and then it will execute normally.
```
11:55:09.004 [DEBUG] [org.gradle.nativeplatform.toolchain.internal.msvcpp.version.DefaultVisualCppMetadataProvider] The MSVC version file at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt either does not exist or is not a file.  Cannot determine the MSVC version for this installation.
```

**Comment by LennyLzy** [comment]
Ask for the same problem.
A problem occurred configuring project ':az-exec-util'. Exception thrown while executing model rule: NativeBinaryRules#assignTools(Nat iveBinarySpec, NativeToolChainRegistryInternal, ProjectLayout) java.lang.NullPointerException (no error message)
When do not include the 'az-exec-util' module in setting.gradle will build successful

**Comment by LennyLzy** [comment]
Ask for the same problem.
A problem occurred configuring project ':az-exec-util'. Exception thrown while executing model rule: NativeBinaryRules#assignTools(Nat iveBinarySpec, NativeToolChainRegistryInternal, ProjectLayout) java.lang.NullPointerException (no error message)
Can not build the project with idea in windows,but can build successful when exclude 'az-exec-util' in setting.gradle.
