### ISSUE TITLE
Azkaban unable to get scheduled flow triggers NPE

### ISSUE THREAD

**Issue by shangwen** [azkaban/azkaban#1917]
version: azkaban-3.51.1
```
2018/08/12 19:18:07.067 +0800 ERROR [FlowTriggerScheduler] [Azkaban] unable to get scheduled flow triggers
java.lang.NullPointerException
        at azkaban.flowtrigger.quartz.FlowTriggerScheduler.getScheduledFlowTriggerJobs(FlowTriggerScheduler.java:132)
        at azkaban.webapp.servlet.FlowTriggerServlet.handlePage(FlowTriggerServlet.java:140)
        at azkaban.webapp.servlet.FlowTriggerServlet.handleGet(FlowTriggerServlet.java:55)
        at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.doGet(LoginAbstractAzkabanServlet.java:123)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by chengren311** [comment]
@shangwen thanks for reporting this issue. Sorry for the confusion, we are publishing more document around flow trigger feature. Are you trying to use flow trigger feature?

**Comment by juhoautio** [comment]
I also saw this in the logs after upgrading to latest version.

To me it seems like this ERROR is always printed if you open a page that includes showing flow triggers BUT you haven't configured quartz scheduler:
https://github.com/azkaban/azkaban/blob/master/azkaban-web-server/src/main/java/azkaban/flowtrigger/quartz/FlowTriggerScheduler.java#L132

That property is `azkaban.server.schedule.enable_quartz`
https://github.com/azkaban/azkaban/blob/master/az-core/src/main/java/azkaban/Constants.java#L206
..which defaults to false:
https://github.com/azkaban/azkaban/search?q=ENABLE_QUARTZ&unscoped_q=ENABLE_QUARTZ

In my opinion it's wrong to fail loading exceptionally like that. As long as it's possible to not have quartz enabled, that should be properly checked & handled.

**Comment by fwantastic** [comment]
I'm also seeing the same error. The new 'Flow Trigger Schedule' page or http://localhost:8081/flowtrigger throws the NPE when running azkaban without modifying any properties after cloning from github.

**Comment by dmvieira** [comment]
I see same error

**Comment by dmvieira** [comment]
We solved here following these steps to enable kafka:

- Add to azkaban.properties it:
```
azkaban.server.schedule.enable_quartz=true
azkaban.dependency.plugin.dir=plugins/dependency

org.quartz.dataSource.quartzDS.driver = com.mysql.jdbc.Driver
org.quartz.dataSource.quartzDS.URL = jdbc:mysql://your_mysql_host:3306/your_mysql_database
org.quartz.dataSource.quartzDS.user = your_mysql_user
org.quartz.dataSource.quartzDS.password = your_mysql_password
org.quartz.threadPool.threadCount = 3
```

- Create a folder called kafka inside plugins/dependency folder

- Add to kafka folder dependency.properties file as specified here: https://azkaban.readthedocs.io/en/latest/eventTrigger.html#event-based-trigger-plugin-configuration
  - you need to build kafka-event-trigger and  az-flow-trigger-dependency-plugin jars
  - kafka-event-trigger and  az-flow-trigger-dependency-plugin jars should be inside classpath specified

- Follow steps here: https://azkaban.readthedocs.io/en/latest/eventTrigger.html

I hope it helps ;)

**Comment by jackjianguo** [comment]
I'm also seeing the same error. I checked the memory and found that there was not enough. I solved here following
AZKABAN_OPTS="-Xmx1G" in bin/internal/internal-start-executor.sh

**Comment by llj1226** [comment]
alter    web-server conf/azkaban.properties 
# execute Host filter configuration, remove MinimumFreeMemory
insted：azkaban.executorselector.filters=StaticRemainingFlowSize,CpuStatus

**Comment by elonlo** [comment]
I also see same error..... how to solve？

**Comment by robertlees** [comment]
> alter web-server conf/azkaban.properties
> 
> # execute Host filter configuration, remove MinimumFreeMemory
> insted：azkaban.executorselector.filters=StaticRemainingFlowSize,CpuStatus

this works for me, thanks!

**Comment by 77954309** [comment]
> > 更改Web服务器conf / azkaban.properties
> > # 执行主机过滤器配置，删除MinimumFreeMemory
> > 插入：azkaban.executorselector.filters = StaticRemainingFlowSize，CpuStatus
> 
> 这对我有用，谢谢！

This way is useless for me
