### ISSUE TITLE
Flaky test FlowRunnerTestYaml

### ISSUE THREAD

**Issue by juhoautio** [azkaban/azkaban#1921]
This PR merge build had 1 test failure: https://travis-ci.org/azkaban/azkaban/builds/415808148?utm_source=github_status&utm_medium=notification

I searched full Travis log with regex ` > \w* FAILED` and found this:

```
azkaban.execapp.FlowRunnerTestYaml > testKillBasicFlowWithoutEndNode STANDARD_ERROR
    testJob: jobB SUCCEEDED
    testJob: jobA SUCCEEDED
    testJob: jobC SUCCEEDED
    ExecutableFlow: basic_flow KILLED
    ExecutableNode: jobB SUCCEEDED
    ExecutableNode: jobA SUCCEEDED
    ExecutableNode: jobC SUCCEEDED

azkaban.execapp.FlowRunnerTestYaml > testKillBasicFlowWithoutEndNode FAILED
    java.lang.AssertionError: Wrong status for [jobC] expected:<KILLED> but was:<SUCCEEDED>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:133)
        at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:138)
        at azkaban.execapp.FlowRunnerTestYaml.testKillBasicFlowWithoutEndNode(FlowRunnerTestYaml.java:69)
```

`FlowRunnerTestYaml` should be stabilized.

Also, it would be nice to rename the test file/class to `FlowRunnerYamlTest`? To have the usual `*Test` suffix, right?

**Comment by HappyRay** [comment]
> Also, it would be nice to rename the test file/class to FlowRunnerYamlTest? To have the usual *Test suffix, right?

Make sense to me. @jamiesjc is there any reason not to follow the standard test class naming convention?

**Comment by jamiesjc** [comment]
@HappyRay @juhoautio 
Yes, I agree. It should be renamed to FlowRunnerYamlTest.
For this flaky test, I remembered fixing it before by extending the job runtime of jobC because the kill sometimes takes a long time. https://github.com/azkaban/azkaban/pull/1847
 I haven't seen this failure for a long time so I thought it was fixed. But anyway, thanks for pointing out this failure. Do you think we should extend the time more or any other better idea?

**Comment by juhoautio** [comment]
Actually, my proposed fix makes another test FlowRunnerTestYaml#testBasicFlowWithoutEndNode fail. But that test has a problem of its own. It currently always takes > 2s because jobC sleeps the full 2 seconds.

Test shouldn't contain any fixed sleeps. A case like testBasicFlowWithoutEndNode should be handled like this:
- let the job start but make it go into Object.wait until notified
- assert that job status is running
- notify the job allowing it to return
- assert that job status is succeeded

This is exactly how InteractiveTestJob is used in other tests. Especially `InteractiveTestJob#succeedJob`. You can find many usages in other tests.

**Comment by HappyRay** [comment]
I agree sleep in tests should be avoided as much as we can.

**Comment by jamiesjc** [comment]
@juhoautio @HappyRay 
Thanks for the comments. I've submitted a PR (https://github.com/azkaban/azkaban/pull/1923) to address those concerns.

**Comment by juhoautio** [comment]
@jamiesjc Was this supposed to have been fixed? Issue is still open?

My other PR failed with this error again, but I realized that maybe it's because I haven't rebased that code for a long time.

**Comment by juhoautio** [comment]
Aha, it still happens after rebasing:

https://travis-ci.org/azkaban/azkaban/builds/425279202?utm_source=github_status&utm_medium=notification

```
azkaban.execapp.FlowRunnerYamlTest > testKillBasicFlowWithoutEndNode STANDARD_ERROR
    testJob: jobB SUCCEEDED
    testJob: jobA SUCCEEDED
    testJob: jobC RUNNING
    ExecutableFlow: basic_flow KILLING
    ExecutableNode: jobB SUCCEEDED
    ExecutableNode: jobA SUCCEEDED
    ExecutableNode: jobC RUNNING

azkaban.execapp.FlowRunnerYamlTest > testKillBasicFlowWithoutEndNode FAILED
    java.lang.AssertionError: Wrong status for [jobC] expected:<KILLED> but was:<RUNNING>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:133)
        at azkaban.execapp.FlowRunnerTestBase.assertStatus(FlowRunnerTestBase.java:138)
        at azkaban.execapp.FlowRunnerYamlTest.testKillBasicFlowWithoutEndNode(FlowRunnerYamlTest.java:69)
```

When I run this test locally it succeeds.

**Comment by jamiesjc** [comment]
@juhoautio Thanks for reporting this issue. When killing happens, jobC was not even added to activeJobRunners even though it was already submitted. We've seen this race condition in killing flows before and it would take much effort to completely fix it. I would disable this test for now to unblock the travis build. With the new DAG engine design, we should not see this kind of issue again. 

```
2018/09/06 14:02:37.544 +0000 INFO [FlowRunner-exec-116] [basic_flow] Submitting job 'jobC' to run.
    2018/09/06 14:02:37.540 +0000 INFO [Test worker] [basic_flow] Kill has been called on flow 116
    2018/09/06 14:02:37.544 +0000 INFO [Test worker] [basic_flow] Killing 0 jobs.
    2018/09/06 14:02:37.545 +0000 INFO [JobRunner-jobC-116] [basic_flow] Created file appender for job jobC
    2018/09/06 14:02:37.545 +0000 INFO [JobRunner-jobC-116] [basic_flow] Attached file appender for job jobC
    2018/09/06 14:02:37.545 +0000 INFO [JobRunner-jobC-116] [basic_flow] Job Started: jobC
```

**Comment by juhoautio** [comment]
Oh, do you mean that there is this kind of bug in the runtime code (not a testing problem then)? Disabling the test sounds like a solution 👍

**Comment by jamiesjc** [comment]
I think so. I remembered seeing a similar issue before in #1311.
