### ISSUE TITLE
Executor ID changes when restarting executor, destroying flows with setExecutor enabled

### ISSUE THREAD

**Issue by steverding** [azkaban/azkaban#1969]
We have some flows, which are pinned to a single executor via setting "setExecutor=ID" in the flow parameters. 
When we restart the executor node, the executor id changes. This destroys all the flows, that are pinned to this node.

Can we make the executor id fixed ? Or is it possible to pin jobs to a single executor node via another property than executors.id ? Maybe executors.host ?

**Comment by chengren311** [comment]
valid concern. Executor host plus port is preferred IMO, are you interested in contributing a PR?

**Comment by steverding** [comment]
Hi,
sorry, i am not a programmer, I just found out, that this is a problem when using azkaban.

Mit freundlichen Grüßen
Kai Steverding
eBusiness
IT-Betrieb

T: +49 (251) 7000-02
F: +49 (251) 7000-3999
E: Kai.Steverding@gws.ms<mailto:Kai.Steverding@gws.ms>
I: www.gws.ms<http://www.gws.ms> | www.erpsystem.de<http://www.erpsystem.de>

[https://www.gws.ms/upload/public/email/gr_youtube-square.jpg]<https://www.youtube.com/user/gwsmuenster>  [https://www.gws.ms/upload/public/email/gr_facebook.jpg] <https://de-de.facebook.com/gws.muenster/>   [https://www.gws.ms/upload/public/email/gr_twitter-square.jpg] <https://twitter.com/GWS_Muenster>   [https://www.gws.ms/upload/public/email/gr_xing-square.jpg] <https://www.xing.com/company/gws-gesellschaft-fuer-warenwirtschaftssyteme-mbh>   [https://www.gws.ms/upload/public/email/gr_linkedin.jpg] <https://www.linkedin.com/company/10153750/>
GWS Gesellschaft für Warenwirtschafts-Systeme mbH
Willy-Brandt-Weg 1 - 48155 Münster
Standorte: Münster, München, Nürnberg, Leonberg, Isernhagen, Hamburg
Geschäftsführer: Dipl. Ökonom Udo Lorenz, Dipl.-Ing. Georg Mersmann
Sitz: Münster (Westf.); Amtsgericht Münster HRB 3844
[https://www.gws.ms/upload/public/email/leaf.jpg] SAVE PAPER - THINK BEFORE YOU PRINT.

[Was ist Digitalisierung?]<http://erpsystem.de/digitalisierung-handel/>

Von: Cheng Ren <notifications@github.com>
Gesendet: Mittwoch, 10. Oktober 2018 06:30
An: azkaban/azkaban <azkaban@noreply.github.com>
Cc: Steverding, Kai <Kai.Steverding@gws.ms>; Author <author@noreply.github.com>
Betreff: Re: [azkaban/azkaban] Executor ID changes when restarting executor, destroying flows with setExecutor enabled (#1969)


valid concern. Executor host plus port is preferred IMO, are you interested in contributing a PR?

**Comment by jaihind213** [comment]
hi i have create a pull request for this issue. Kindly request to review.
https://github.com/azkaban/azkaban/pull/2265

The User can now provide alternate value for 'useExecutor' flow parameter. The value will be in the format '<azkaban_executor_host>:>executor_port>'. example: 'localhost:9001'. so if restart occurs and executor id changes, the flow can still be bound using this format.

**Comment by jaihind213** [comment]
@burgerkingeater kindly request you to review pr

**Comment by twoyang0917** [comment]
@burgerkingeater  @jaihind213 

the worse thing is when one executor restarted. webserver have to be restarted too, otherwise it can not assign task to this executor any more.

```
2019/07/09 15:41:54.307 +0800 INFO [ExecutorManager] [Azkaban] Using dispatcher for execution id :12
2019/07/09 15:41:54.319 +0800 WARN [ExecutorManager] [Azkaban] Executor localhost:12321 (id: 15), active=true responded with exception for exec: 12
azkaban.executor.ExecutorManagerException: Failed to assign non-existent executor Id: 15 to execution : 12
        at azkaban.executor.AssignExecutorDao.assignExecutor(AssignExecutorDao.java:43)
        at azkaban.executor.JdbcExecutorLoader.assignExecutor(JdbcExecutorLoader.java:329)
        at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1048)
        at azkaban.executor.ExecutorManager.access$600(ExecutorManager.java:65)
        at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1282)
        at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1254)
        at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1192)
2019/07/09 15:41:54.319 +0800 INFO [ExecutorManager] [Azkaban] Failed dispatch attempt for exec 12 with error count 0
2019/07/09 15:41:55.320 +0800 ERROR [ExecutorManager] [Azkaban] Failed to dispatch queued execution demo because reached azkaban.maxDispatchingErrors (tried 1 executors)
```

It's disaster for multi-executor deployment which aim to high availability.

**Comment by jaihind213** [comment]
hi @twoyang0917 

this pr is about allowing user to specify "host:port" as value to useExecutor parameter instead of executor id.

on restart, id will change but value of "host:port" will remain unchanged and hence useExecutor will continue to work.

this should solve your problem. correct me if i am worng

**Comment by twoyang0917** [comment]
@jaihind213  your pr is a nice fix for those event triggers to call the api to execute workflow. 
but what about those tasks base on the scheduler built in webserver. 

think about that, one executor crashed, then we start it up and activate it. but the executor's id changed and webserver don't know it, it's still unavailable for the whole system.

you may say why we don't restart webserver directly after we started the executor up and activate it. but actually make sure executor alive should be done by some daemon protect process automatically in those HA cases. So how to notify webserver to restart itself. does that  effect other running tasks or scheduling. there are too many things need to be considered when we want to put it on production environment that need HA.

**Comment by steverding** [comment]
Would it be possible to get this into a flow definition file ? 
We are working on monitoring azkaban and its scheduling mechanism. With multiple executors, we need a way to get monitoring flows scheduled on each executor to check if the executor node is working and to check if the scheduler is working. 
We could schedule the jobs via the API with the useexecutor parameter, but this would not check if the scheduler part of azkaban is working
