### ISSUE TITLE
Build Failure Issue

### ISSUE THREAD

**Issue by shrimalmadhur** [azkaban/azkaban#2015]
My build is failing with this error on Mac OSX mojave. Java 9.0.4

./gradlew build installDist
Parallel execution with configuration on demand is an incubating feature.

> Task :azkaban-web-server:restliTemplateGenerator FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: javax/annotation/Generated
        at com.linkedin.pegasus.generator.CodeGenerator.annotate(CodeGenerator.java:97)
        at com.linkedin.pegasus.generator.DataTemplateGenerator.registerGeneratedClass(DataTemplateGenerator.java:367)
        at com.linkedin.pegasus.generator.DataTemplateGenerator.generateRecord(DataTemplateGenerator.java:1103)
        at com.linkedin.pegasus.generator.DataTemplateGenerator.generateNamedSchema(DataTemplateGenerator.java:668)
        at com.linkedin.pegasus.generator.DataTemplateGenerator.processSchema(DataTemplateGenerator.java:453)
        at com.linkedin.pegasus.generator.DataTemplateGenerator.handleSchema(DataTemplateGenerator.java:322)
        at com.linkedin.data.schema.generator.AbstractGenerator.parseFile(AbstractGenerator.java:197)
        at com.linkedin.pegasus.generator.DataTemplateGenerator.parseFile(DataTemplateGenerator.java:295)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.parseFile(PegasusDataTemplateGenerator.java:121)
        at com.linkedin.data.schema.generator.AbstractGenerator.parseSources(AbstractGenerator.java:128)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.generate(PegasusDataTemplateGenerator.java:89)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.run(PegasusDataTemplateGenerator.java:68)
        at com.linkedin.pegasus.generator.PegasusDataTemplateGenerator.main(PegasusDataTemplateGenerator.java:52)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 13 more

> Task :azkaban-common:compileJava FAILED
/Users/madhur.shrimal/azkaban/azkaban-common/src/main/java/azkaban/project/validator/ValidatorClassLoader.java:14: warning: JarURLConnection is internal proprietary API and may be removed in a future release
import sun.net.www.protocol.jar.JarURLConnection;
                               ^
error: warnings found and -Werror specified
1 error
1 warning

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':azkaban-web-server:restliTemplateGenerator'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':azkaban-common:compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
49 actionable tasks: 3 executed, 46 up-to-date

**Comment by jblion** [comment]
Hi, 
here is the fix for the file /Users/madhur.shrimal/azkaban/azkaban-common/src/main/java/azkaban/project/validator/ValidatorClassLoader.java: 
```
//import sun.net.www.protocol.jar.JarURLConnection;
import java.net.JarURLConnection;
```
