### ISSUE TITLE
Flaky test ExecutorManagerTest.testDispatchFailed

### ISSUE THREAD

**Issue by jamiesjc** [azkaban/azkaban#2064]
Hi @juhoautio, Can you take a look at below flaky test? I've seen it failed several times during travis build, but not able to reproduce it locally. Thanks!

```
azkaban.executor.ExecutorManagerTest > testDispatchFailed FAILED
    Wanted but not invoked:
    alerter.alertOnError(
        azkaban.executor.ExecutableFlow@7b304398,
        "Failed to dispatch queued execution derived-member-data because reached azkaban.maxDispatchingErrors (tried 2 executors)",
        contains("Mocked dispatch exception")
    );
    -> at azkaban.executor.ExecutorManagerTest.testDispatchFailed(ExecutorManagerTest.java:348)
    Actually, there were zero interactions with this mock.
        at azkaban.executor.ExecutorManagerTest.testDispatchFailed(ExecutorManagerTest.java:348)
```

**Comment by juhoautio** [comment]
@jamiesjc is this test going to become obsolete after the "AZNewDispatchingLogic"? If yes, I would disable or delete this test to stabilize the travis builds.

**Comment by jamiesjc** [comment]
Yes, it will become obsolete if we switch to the new dispatching logic.
