### ISSUE TITLE
azkaban.executor.ExecutorManagerException: java.io.IOException: executor became inactive before setting up the flow 8

### ISSUE THREAD

**Issue by BodhiFlower** [azkaban/azkaban#2145]
This error is reported for all tasks performed, including the official example. The database executor is active. What is the reason for this。
The details of the error are as follows：
2019/03/09 10:02:42.736 +0800 INFO [ExecutorManager] [Azkaban] Using dispatcher for execution id :8
2019/03/09 10:02:42.943 +0800 ERROR [ExecutorManager] [Azkaban] Rolling back executor assignment for execution id:8
azkaban.executor.ExecutorManagerException: java.io.IOException: executor became inactive before setting up the flow 8
	at azkaban.executor.ExecutorApiGateway.callWithExecutionId(ExecutorApiGateway.java:80)
	at azkaban.executor.ExecutorApiGateway.callWithExecutable(ExecutorApiGateway.java:43)
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1113)
	at azkaban.executor.ExecutorManager.access$600(ExecutorManager.java:73)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1344)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1316)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1254)
Caused by: java.io.IOException: executor became inactive before setting up the flow 8
	at azkaban.executor.ExecutorApiGateway.callForJsonObjectMap(ExecutorApiGateway.java:108)
	at azkaban.executor.ExecutorApiGateway.callWithExecutionId(ExecutorApiGateway.java:78)
	... 6 more
2019/03/09 10:02:42.951 +0800 WARN [ExecutorManager] [Azkaban] Executor node154:42491 (id: 3), active=true responded with exception for exec: 8
azkaban.executor.ExecutorManagerException: azkaban.executor.ExecutorManagerException: java.io.IOException: executor became inactive before setting up the flow 8
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1119)
	at azkaban.executor.ExecutorManager.access$600(ExecutorManager.java:73)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1344)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1316)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1254)
Caused by: azkaban.executor.ExecutorManagerException: java.io.IOException: executor became inactive before setting up the flow 8
	at azkaban.executor.ExecutorApiGateway.callWithExecutionId(ExecutorApiGateway.java:80)
	at azkaban.executor.ExecutorApiGateway.callWithExecutable(ExecutorApiGateway.java:43)
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1113)
	... 4 more
Caused by: java.io.IOException: executor became inactive before setting up the flow 8
	at azkaban.executor.ExecutorApiGateway.callForJsonObjectMap(ExecutorApiGateway.java:108)
	at azkaban.executor.ExecutorApiGateway.callWithExecutionId(ExecutorApiGateway.java:78)
	... 6 more

**Comment by xiangtao** [comment]
maybe executor  is down

**Comment by xiaohui0318** [comment]
Take a look at the startup log to see if the executor is really alive, and judging from the error messages, the connection did time out when web connection exec was reconfirmed after the selection

**Comment by BodhiFlower** [comment]
> 
> 
> Take a look at the startup log to see if the executor is really alive, and judging from the error messages, the connection did time out when web connection exec was reconfirmed after the selection



> 
> 
> maybe executor is down

The problem was solved temporarily, but not in a reasonable way:

I had no intention of trying to process the request: http://node151:12321/executor? Activate action=activate this address so that all my tasks can run as normal.

I tried again and again, but the error was not resolved when the execution port was not fixed.

Is this because something is not configured properly?

**Comment by xiaohui0318** [comment]
Is the log level debug or info?

**Comment by BodhiFlower** [comment]
> 
> 
> Is the log level debug or info?

INFO

**Comment by lecterqian** [comment]
property active in class FlowRunnerManager is false default, there should be true by some way, it confuse me ,too

**Comment by FsecureSamiTikka** [comment]
We had this problem. We run in ECS with one container called azkaban-webserver and another called azkaban-executor. In our db there is only one executor named "azkaban-executor". We suspect during upgrade the old azkaban-executor must have marked the executor inactive in database.

As a workaround we changed our container entrypoint to start azkaban-executor and then call `curl http://localhost:port/executor?action=activate` to make sure the new executor is active.

**Comment by technologyMz** [comment]
你好! 解决了吗?

**Comment by technologyMz** [comment]
> > Take a look at the startup log to see if the executor is really alive, and judging from the error messages, the connection did time out when web connection exec was reconfirmed after the selection
> 
> > maybe executor is down
> 
> The problem was solved temporarily, but not in a reasonable way:
> 
> I had no intention of trying to process the request: http://node151:12321/executor? Activate action=activate this address so that all my tasks can run as normal.
> 
> I tried again and again, but the error was not resolved when the execution port was not fixed.
> 
> Is this because something is not configured properly?



> > Take a look at the startup log to see if the executor is really alive, and judging from the error messages, the connection did time out when web connection exec was reconfirmed after the selection
> 
> > maybe executor is down
> 
> The problem was solved temporarily, but not in a reasonable way:
> 
> I had no intention of trying to process the request: http://node151:12321/executor? Activate action=activate this address so that all my tasks can run as normal.
> 
> I tried again and again, but the error was not resolved when the execution port was not fixed.
> 
> Is this because something is not configured properly?

你好! 找着原因了吗? 怎么解决的呢, 方便说下吗?

**Comment by xukaide77** [comment]
do request by this
curl http://${executorHost}:${executorPort}/executor?action=activate

**Comment by wuyue92tree** [comment]
I also got this error, because I don't active executor node by call `curl http://${executorHost}:${executorPort}/executor?action=activate`.

I did this, add executor node from the table `executors`, this make me got the error.

call `curl http://${executorHost}:${executorPort}/executor?action=activate` is work.

**Comment by dgarg20** [comment]
I also got the error but the issue was in DB where the executors config lies. It has canonical hostname instead of The IP address and web node was not able to communicate with the executor node.
there is a configuration in executor *azkaban.server.hostname* If it is not set the executor register itself with canonical hostname(hotname -f). and for this there should be the host entry mapping in web node  fopr the executor node *<hostname -i> <hostname-f>*. If the above config is set the executor registers itself with the provided value of in config *zkaban.server.hostname*
