### ISSUE TITLE
Flaky test XmlUserManagerTest > testAutoReload

### ISSUE THREAD

**Issue by juhoautio** [azkaban/azkaban#2220]
From https://travis-ci.org/azkaban/azkaban/builds/524621558?utm_source=github_status&utm_medium=notification:
```
azkaban.user.XmlUserManagerTest > testAutoReload STANDARD_OUT
    The config did not reload in 60 seconds

azkaban.user.XmlUserManagerTest > testAutoReload FAILED
    java.lang.AssertionError: The config did not reload in 60 seconds
        at org.junit.Assert.fail(Assert.java:88)
        at azkaban.user.XmlUserManagerTest.testAutoReload(XmlUserManagerTest.java:164)

azkaban.user.XmlUserManagerTest > testAutoReload STANDARD_OUT
    2019/04/25 19:05:01.439 +0000 INFO [XmlUserManager] Loading user user0
    2019/04/25 19:05:01.440 +0000 INFO [XmlUserManager] Loading user user1

azkaban.user.XmlUserManagerTest > testAutoReload STANDARD_OUT
    2019/04/25 19:05:01.447 +0000 INFO [XmlUserManager] Loading user user2
    2019/04/25 19:05:01.448 +0000 INFO [XmlUserManager] Loading user user3
    2019/04/25 19:05:01.448 +0000 INFO [XmlUserManager] Loading user user4
    2019/04/25 19:05:01.449 +0000 INFO [XmlUserManager] Loading user user5
    2019/04/25 19:05:01.450 +0000 INFO [XmlUserManager] Loading user user6
    2019/04/25 19:05:01.451 +0000 INFO [XmlUserManager] Loading user user7
    2019/04/25 19:05:01.451 +0000 INFO [XmlUserManager] Loading user user8
    2019/04/25 19:05:01.451 +0000 INFO [XmlUserManager] Loading user user9
    2019/04/25 19:05:01.486 +0000 INFO [UserUtils] Starting configuration watching thread.
    File modification time = 2019-04-25T19:04:37Z
    2019/04/25 19:05:01.508 +0000 INFO [UserUtils] Modification detected, reloading config file /home/travis/build/azkaban/azkaban/azkaban-common/build/resources/test/test-conf/azkaban-users-test1.xml

azkaban.user.XmlUserManagerTest > testAutoReload STANDARD_ERROR
    [Fatal Error] :-1:-1: Premature end of file.

azkaban.user.XmlUserManagerTest > testAutoReload STANDARD_OUT
    File modification time after write = 2019-04-25T19:05:01Z
```
(interestingly the stdout is scattered in different places around the Travis log, but this should be all :))

I also checked https://travis-ci.org/azkaban/azkaban/builds/521538129?utm_source=github_status&utm_medium=notification and it also failed for the same test.

There's also an open issue about XmlUserManagerTest from 2015 :)
https://github.com/azkaban/azkaban/issues/535 – but maybe that can be closed.

**Comment by juhoautio** [comment]
It looks like the test is also modifying a build-generated file (`azkaban-common/build/resources/test/test-conf/azkaban-users-test1.xml`). Even though test has a finally block to "revert the contents", this shouldn't be done IMHO. Instead, a copy of the file should be made to a temporary folder or something.

**Comment by juhoautio** [comment]
@djaiswal83 what to you think about these things, and closing https://github.com/azkaban/azkaban/issues/535?

**Comment by juhoautio** [comment]
@djaiswal83 @burgerkingeater what's up? XmlUserManagerTest takes 30s, which is mostly sleeping. Has something changed, I though the idea is to keep the tests quick and _not_ add any Thread.sleep in them.

**Comment by djaiswal83** [comment]
@juhoautio I changed the sensitivity to SensitivityWatchEventModifier.MEDIUM which polls every 30 seconds which is causing the test to take 30 seconds to run. The idea is to not poll too much as config changes dont happen often, moreover, a change need not reflect immediately. This change is in setupWatch() in UserUtils.java
The test has no control on this hence it takes 30 seconds.

**Comment by juhoautio** [comment]
@djaiswal83 plz check https://github.com/azkaban/azkaban/pull/2240

**Comment by juhoautio** [comment]
This test failed again (https://github.com/azkaban/azkaban/pull/3034#issuecomment-1014854031). How about my suggestion above to use LOW instead of MEDIUM?
