### ISSUE TITLE
Unable start azkaban-solo-server

### ISSUE THREAD

**Issue by nighttiger1990** [azkaban/azkaban#2260]
I got  same issue  when run ./start-solo.sh on MacOS Mojave 10.14.5 and Centos 7
```
Error: HADOOP_HOME is not set. Hadoop job types will not run properly.
CLASSPATH: :./internal/../../lib/*:./internal/../../extlib/*
Listening for transport dt_socket at address: 5005
2019/05/30 17:46:39.124 +0700 INFO [AzkabanWebServer] [Azkaban] Starting Azkaban Server
2019/05/30 17:46:39.216 +0700 INFO [AzkabanServer] [Azkaban] Loading azkaban settings file from ./internal/../../conf
2019/05/30 17:46:39.217 +0700 INFO [AzkabanServer] [Azkaban] Loading azkaban properties file
2019/05/30 17:46:39.227 +0700 INFO [AzkabanDatabaseUpdater] [Azkaban] Use scripting directory sql
2019/05/30 17:46:39.228 +0700 INFO [AzkabanDatabaseUpdater] [Azkaban] Will auto update any changes.
2019/05/30 17:46:39.254 +0700 INFO [DataSourceUtils] [Azkaban] h2 DB path: /Users/macos/Desktop/Project/Java/azkaban/azkaban-solo-server/build/install/azkaban-solo-server/bin/./h2
2019/05/30 17:46:39.336 +0700 INFO [AzkabanDatabaseSetup] [Azkaban] Searching for installed tables
2019/05/30 17:46:40.210 +0700 INFO [AzkabanDatabaseSetup] [Azkaban] Searching for table versions in the properties table
2019/05/30 17:46:40.265 +0700 INFO [AzkabanDatabaseUpdater] [Azkaban] Everything looks up to date.
2019/05/30 17:46:41.925 +0700 INFO [log] [Azkaban] Logging to org.slf4j.impl.Log4jLoggerAdapter(org.mortbay.log) via org.mortbay.log.Slf4jLog
2019/05/30 17:46:41.926 +0700 INFO [WebServerProvider] [Azkaban] Setting up connector with stats on: true
2019/05/30 17:46:41.931 +0700 INFO [WebServerProvider] [Azkaban] Starting server on port: 8081 # Max threads: 25
2019/05/30 17:46:42.058 +0700 WARN [StorageCleaner] [Azkaban] Project cleanup disabled. All artifacts will be stored.
2019/05/30 17:46:42.060 +0700 INFO [AzkabanProjectLoader] [Azkaban] Using temp dir: /Users/macos/Desktop/Project/Java/azkaban/azkaban-solo-server/build/install/azkaban-solo-server/bin/temp
2019/05/30 17:46:42.061 +0700 INFO [AzkabanProjectLoader] [Azkaban] Project version retention is set to 3
2019/05/30 17:46:42.066 +0700 WARN [XmlValidatorManager] [Azkaban] Validator directory validators does not exist or is not a directory.
2019/05/30 17:46:42.067 +0700 WARN [XmlValidatorManager] [Azkaban] Azkaban properties file does not contain the key project.validators.xml.file
2019/05/30 17:46:42.067 +0700 INFO [ProjectManager] [Azkaban] Loading active projects.
2019/05/30 17:46:42.125 +0700 INFO [ProjectManager] [Azkaban] Loading flows from active projects.
2019/05/30 17:46:42.126 +0700 INFO [ProjectManager] [Azkaban] Loading whitelisted projects.
2019/05/30 17:46:42.126 +0700 INFO [ProjectManager] [Azkaban] ProjectManager instance created.
2019/05/30 17:46:42.312 +0700 INFO [TriggerManager] [Azkaban] TriggerManager loaded.
2019/05/30 17:46:42.320 +0700 INFO [AzkabanWebServerModule] [Azkaban] Loading user manager class azkaban.user.XmlUserManager
2019/05/30 17:46:42.320 +0700 ERROR [AzkabanWebServerModule] [Azkaban] Could not instantiate UserManager azkaban.user.XmlUserManager
2019/05/30 17:46:42.444 +0700 INFO [AzkabanExecServerModule] [Azkaban] Event reporter is not enabled
2019/05/30 17:46:42.445 +0700 INFO [FlowRunnerManager] [Azkaban] Execution dir retention set to 60000 ms
2019/05/30 17:46:42.445 +0700 INFO [FlowRunnerManager] [Azkaban] useNewThreadPool: false
2019/05/30 17:46:42.453 +0700 INFO [JobTypeManager] [Azkaban] Loading plugin default job types
2019/05/30 17:46:42.459 +0700 INFO [JobTypeManager] [Azkaban] Job type plugin directory set. Loading extra job types from plugins/jobtypes
2019/05/30 17:46:42.459 +0700 INFO [JobTypeManager] [Azkaban] Common plugin job props file plugins/jobtypes/common.properties not found. Using only globals props
2019/05/30 17:46:42.460 +0700 INFO [JobTypeManager] [Azkaban] Common plugin load props file plugins/jobtypes/commonprivate.properties found. Attempt to load.
2019/05/30 17:46:42.467 +0700 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
2019/05/30 17:46:42.467 +0700 INFO [FlowRunnerManager] [Azkaban] Cleaning recently finished
2019/05/30 17:46:42.467 +0700 INFO [FlowRunnerManager] [Azkaban] Cleaning old execution dirs
2019/05/30 17:46:42.470 +0700 INFO [ExecJettyServerModule] [Azkaban] Setting up connector with stats on: true
2019/05/30 17:46:42.471 +0700 INFO [ExecJettyServerModule] [Azkaban] Jetty connector name: 0.0.0.0:12321, default header buffer size: 4096
2019/05/30 17:46:42.472 +0700 INFO [ExecJettyServerModule] [Azkaban] Jetty connector name: 0.0.0.0:12321, (if) new header buffer size: 4096
2019/05/30 17:46:42.555 +0700 ERROR [AzkabanWebServer] [Azkaban] Failed to start single server. Shutting down.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: java.lang.NoSuchMethodException: azkaban.user.XmlUserManager.<init>(azkaban.utils.Props)
  at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:94)
  at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:94)
  while locating azkaban.user.UserManager
    for the 8th parameter of azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:163)
  at azkaban.webapp.AzkabanWebServer.class(AzkabanWebServer.java:121)
  while locating azkaban.webapp.AzkabanWebServer
    for the 1st parameter of azkaban.soloserver.AzkabanSingleServer.<init>(AzkabanSingleServer.java:51)
  while locating azkaban.soloserver.AzkabanSingleServer

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at azkaban.soloserver.AzkabanSingleServer.start(AzkabanSingleServer.java:105)
	at azkaban.soloserver.AzkabanSingleServer.main(AzkabanSingleServer.java:58)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: azkaban.user.XmlUserManager.<init>(azkaban.utils.Props)
	at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:103)
	at azkaban.webapp.AzkabanWebServerModule$$FastClassByGuice$$2f44d056.invoke(<generated>)
	at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
	at com.google.inject.internal.ProviderMethod$Factory.provision(ProviderMethod.java:401)
	at com.google.inject.internal.ProviderMethod$Factory.get(ProviderMethod.java:376)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	... 3 more
Caused by: java.lang.NoSuchMethodException: azkaban.user.XmlUserManager.<init>(azkaban.utils.Props)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:99)
	... 30 more

```

**Comment by djaiswal83** [comment]
Fixed in https://github.com/azkaban/azkaban/pull/2258
