### ISSUE TITLE
azkaban-solo-server 执行mapreduce任务成功后，报处理异常

### ISSUE THREAD

**Issue by xiaoma0105** [azkaban/azkaban#2297]
30-07-2019 21:00:22 CST stats-day-goods INFO - 	File System Counters
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of bytes read=37543076
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of bytes written=38209854
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of read operations=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of large read operations=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of write operations=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 	Map-Reduce Framework
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Combine input records=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Combine output records=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Reduce input groups=336
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Reduce shuffle bytes=193594
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Reduce input records=1858
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Reduce output records=336
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Spilled Records=1858
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Shuffled Maps =1
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Failed Shuffles=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Merged Map outputs=1
30-07-2019 21:00:22 CST stats-day-goods INFO - 		GC time elapsed (ms)=19
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Total committed heap usage (bytes)=336068608
30-07-2019 21:00:22 CST stats-day-goods INFO - 	Shuffle Errors
30-07-2019 21:00:22 CST stats-day-goods INFO - 		BAD_ID=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		CONNECTION=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		IO_ERROR=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		WRONG_LENGTH=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		WRONG_MAP=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		WRONG_REDUCE=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 	File Output Format Counters 
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Bytes Written=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 19/07/30 21:00:22 INFO mapred.LocalJobRunner: Finishing task: attempt_local1270432337_0001_r_000000_0
30-07-2019 21:00:22 CST stats-day-goods INFO - 19/07/30 21:00:22 INFO mapred.LocalJobRunner: reduce task executor complete.
30-07-2019 21:00:22 CST stats-day-goods INFO - 19/07/30 21:00:22 WARN output.FileOutputCommitter: Output Path is null in commitJob()
30-07-2019 21:00:22 CST stats-day-goods INFO - 19/07/30 21:00:22 INFO mapreduce.Job:  map 100% reduce 100%
30-07-2019 21:00:22 CST stats-day-goods INFO - 19/07/30 21:00:22 INFO mapreduce.Job: Job job_local1270432337_0001 completed successfully
30-07-2019 21:00:22 CST stats-day-goods INFO - 19/07/30 21:00:22 INFO mapreduce.Job: Counters: 43
30-07-2019 21:00:22 CST stats-day-goods INFO - 	File System Counters
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of bytes read=74698932
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of bytes written=76226114
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of read operations=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of large read operations=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		FILE: Number of write operations=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 	Map-Reduce Framework
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Map input records=583
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Map output records=1858
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Map output bytes=189872
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Map output materialized bytes=193594
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Input split bytes=156
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Combine input records=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Combine output records=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Reduce input groups=336
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Reduce shuffle bytes=193594
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Reduce input records=1858
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Reduce output records=336
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Spilled Records=3716
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Shuffled Maps =1
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Failed Shuffles=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Merged Map outputs=1
30-07-2019 21:00:22 CST stats-day-goods INFO - 		GC time elapsed (ms)=24
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Total committed heap usage (bytes)=672137216
30-07-2019 21:00:22 CST stats-day-goods INFO - 	HBase Counters
30-07-2019 21:00:22 CST stats-day-goods INFO - 		BYTES_IN_REMOTE_RESULTS=2784975
30-07-2019 21:00:22 CST stats-day-goods INFO - 		BYTES_IN_RESULTS=2784975
30-07-2019 21:00:22 CST stats-day-goods INFO - 		MILLIS_BETWEEN_NEXTS=609
30-07-2019 21:00:22 CST stats-day-goods INFO - 		NOT_SERVING_REGION_EXCEPTION=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		NUM_SCANNER_RESTARTS=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		NUM_SCAN_RESULTS_STALE=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		REGIONS_SCANNED=1
30-07-2019 21:00:22 CST stats-day-goods INFO - 		REMOTE_RPC_CALLS=2
30-07-2019 21:00:22 CST stats-day-goods INFO - 		REMOTE_RPC_RETRIES=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		ROWS_FILTERED=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		ROWS_SCANNED=583
30-07-2019 21:00:22 CST stats-day-goods INFO - 		RPC_CALLS=2
30-07-2019 21:00:22 CST stats-day-goods INFO - 		RPC_RETRIES=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 	Shuffle Errors
30-07-2019 21:00:22 CST stats-day-goods INFO - 		BAD_ID=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		CONNECTION=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		IO_ERROR=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		WRONG_LENGTH=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		WRONG_MAP=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 		WRONG_REDUCE=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 	File Input Format Counters 
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Bytes Read=0
30-07-2019 21:00:22 CST stats-day-goods INFO - 	File Output Format Counters 
30-07-2019 21:00:22 CST stats-day-goods INFO - 		Bytes Written=0
30-07-2019 21:00:23 CST stats-day-goods INFO - Process completed **unsuccessfully** in 13 seconds.
30-07-2019 21:00:23 CST stats-day-goods ERROR - Job run failed!
java.lang.RuntimeException: azkaban.jobExecutor.utils.process.ProcessFailureException: Process exited with code 1
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:305)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:787)
	at azkaban.execapp.JobRunner.doRun(JobRunner.java:602)
	at azkaban.execapp.JobRunner.run(JobRunner.java:563)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: azkaban.jobExecutor.utils.process.ProcessFailureException: Process exited with code 1
	at azkaban.jobExecutor.utils.process.AzkabanProcess.run(AzkabanProcess.java:125)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:297)
	... 8 more
30-07-2019 21:00:23 CST stats-day-goods ERROR - azkaban.jobExecutor.utils.process.ProcessFailureException: Process exited with code 1 cause: azkaban.jobExecutor.utils.process.ProcessFailureException: Process exited with code 1
30-07-2019 21:00:23 CST stats-day-goods INFO - Finishing job stats-day-goods at 1564491623154 with status FAILED

**Comment by xiaoma0105** [comment]
shell命令执行返回值为1，导致任务执行完成报unsuccessfully
