### ISSUE TITLE
azkaban.executor.ExecutorManagerException: Running flow 4 not found.

### ISSUE THREAD

**Issue by 1007827412** [azkaban/azkaban#2333]
In multiple mode ,executor throw this error,What is the reason for this?
azkaban.executor.ExecutorManagerException: Running flow 4 not found.
	at azkaban.execapp.FlowRunnerManager.readFlowLogs(FlowRunnerManager.java:591)
	at azkaban.execapp.ExecutorServlet.handleFetchLogEvent(ExecutorServlet.java:195)
	at azkaban.execapp.ExecutorServlet.handleRequest(ExecutorServlet.java:132)
	at azkaban.execapp.ExecutorServlet.doPost(ExecutorServlet.java:93)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
2019/09/17 10:18:53.410 +0800 INFO [ExecutorServlet] [Azkaban] User  has called action log on 4
2019/09/17 10:18:53.410 +0800 ERROR [ExecutorServlet] [Azkaban] Running flow 4 not found.
azkaban.executor.ExecutorManagerException: Running flow 4 not found.
	at azkaban.execapp.FlowRunnerManager.readFlowLogs(FlowRunnerManager.java:591)
	at azkaban.execapp.ExecutorServlet.handleFetchLogEvent(ExecutorServlet.java:195)
	at azkaban.execapp.ExecutorServlet.handleRequest(ExecutorServlet.java:132)
	at azkaban.execapp.ExecutorServlet.doPost(ExecutorServlet.java:93)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by LongStockingPipi** [comment]
I am also

**Comment by gadekuoen** [comment]
I am also
