### ISSUE TITLE
flow run failed with tips : flow has already running

### ISSUE THREAD

**Issue by peaksnail** [azkaban/azkaban#2487]
hi team

my flow run failed with tips : flow has already running , but there is no flow is running 

error log

```
2020/04/06 10:00:26.569 +0800 INFO [ExecutorManager] [Azkaban] Submitting execution flow business by abacus
2020/04/06 10:00:26.569 +0800 ERROR [TriggerManager] [Azkaban] Failed to do action Execute flow business from project business for Trigger Id: 1, Description:
 Trigger from SimpleTimeTrigger with trigger condition of BasicTimeChecker_1.eval() and expire condition of EndTimeChecker_1.eval(), Execute flow business fro
m project business
java.lang.RuntimeException: azkaban.executor.ExecutorManagerException: Flow business is already running. Skipping execution.
        at azkaban.trigger.builtin.ExecuteFlowAction.doAction(ExecuteFlowAction.java:232)
        at azkaban.trigger.TriggerManager$TriggerScannerThread.onTriggerTrigger(TriggerManager.java:363)
        at azkaban.trigger.TriggerManager$TriggerScannerThread.checkAllTriggers(TriggerManager.java:343)
        at azkaban.trigger.TriggerManager$TriggerScannerThread.run(TriggerManager.java:297)
Caused by: azkaban.executor.ExecutorManagerException: Flow business is already running. Skipping execution.
        at azkaban.executor.ExecutorManager.submitExecutableFlow(ExecutorManager.java:1111)
        at azkaban.trigger.builtin.ExecuteFlowAction.doAction(ExecuteFlowAction.java:229)
        ... 3 more
```

**Comment by djaiswal83** [comment]
It could be that the flow is in inconsistent state. If you have access to the underlying db, check if there is any execution of this flow in table "execution_flows". If so, what is its state. Regardless, set it to 60 or 70 so that it is finalized.

**Comment by peaksnail** [comment]
thanks, I will check 

I have many flows,  and suddenly they run failed with the same reason, what causes ?

It will be ok when I restart the server.
