### ISSUE TITLE
HDFS Viewer Plugin (2.1) java.lang.NoClassDefFoundError: org/apache/hadoop/security/AccessControlException

### ISSUE THREAD

**Issue by patricioe** [azkaban/azkaban#25]
Ran into this exception when trying to set up the hdfs viewer. 

Version: Azkaban 2.1 (web server, executor and plugin)

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/security/AccessControlException
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2389)
    at java.lang.Class.getConstructor0(Class.java:2699)
    at java.lang.Class.getConstructor(Class.java:1657)
    at azkaban.webapp.AzkabanWebServer.loadViewerPlugins(AzkabanWebServer.java:585)
    at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:446)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.security.AccessControlException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 6 more

**Comment by revoorunischal** [comment]
Download the appropriate  jar from https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-common for hadoop versions 2.x  and above and add to lib folder of viewer hdfs
