### ISSUE TITLE
 Java heap space</pre></p><h3>Caused by:</h3><pre>java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by linlinnj** [azkaban/azkaban#2662]
version: 3.78
os: CentOS7.4/24C/256G
Deployment mode: web and exec  on the same machine.

It has been running for more than half a year. Yesterday, it suddenly reported the following exception.
-------------------------------------------------------------------------
2020/12/02 14:06:11.514 +0800 INFO [ExecuteFlowAction] [Server] Invoked flow airmt-file-updateNmmsLog_7.basic
2020/12/02 14:06:11.514 +0800 INFO [Condition] [Server] Done resetting checkers. The next check time will be 2020-12-02T14:07:00.000+08:00
2020/12/02 14:06:11.514 +0800 INFO [JdbcTriggerImpl] [Server] Updating trigger 352 into db.
2020/12/02 14:06:45.388 +0800 ERROR [RestfulApiClient] [Server] unable to parse response as the response status is 500
2020/12/02 14:06:45.388 +0800 ERROR [ExecutorManager] [Server] Rolling back executor assignment for execution id:4087964
azkaban.executor.ExecutorManagerException: org.apache.http.client.HttpResponseException: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 Java heap space</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /executor. Reason:
<pre>    Java heap space</pre></p><h3>Caused by:</h3><pre>java.lang.OutOfMemoryError: Java heap space
	at java.util.Hashtable.rehash(Hashtable.java:402)
	at java.util.Hashtable.addEntry(Hashtable.java:426)
	at java.util.Hashtable.put(Hashtable.java:477)
	at org.apache.log4j.Hierarchy.getLogger(Hierarchy.java:277)
	at org.apache.log4j.Hierarchy.getLogger(Hierarchy.java:247)
	at org.apache.log4j.LogManager.getLogger(LogManager.java:228)
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at azkaban.execapp.FlowRunner.createLogger(FlowRunner.java:362)
	at azkaban.execapp.FlowRunner.&lt;init&gt;(FlowRunner.java:201)
	at azkaban.execapp.FlowRunner.&lt;init&gt;(FlowRunner.java:165)
	at azkaban.execapp.FlowRunnerManager.createFlowRunner(FlowRunnerManager.java:449)
	at azkaban.execapp.FlowRunnerManager.submitFlow(FlowRunnerManager.java:347)
	at azkaban.execapp.ExecutorServlet.handleAjaxExecute(ExecutorServlet.java:288)
	at azkaban.execapp.ExecutorServlet.handleRequest(ExecutorServlet.java:136)
	at azkaban.execapp.ExecutorServlet.doPost(ExecutorServlet.java:93)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
</pre>
<hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>

	at azkaban.executor.ExecutorApiGateway.callWithExecutionId(ExecutorApiGateway.java:80)
	at azkaban.executor.ExecutorApiGateway.callWithExecutable(ExecutorApiGateway.java:43)
	at azkaban.executor.ExecutorManager.dispatch(ExecutorManager.java:1080)
	at azkaban.executor.ExecutorManager.access$600(ExecutorManager.java:69)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.selectExecutorAndDispatchFlow(ExecutorManager.java:1311)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.processQueuedFlows(ExecutorManager.java:1283)
	at azkaban.executor.ExecutorManager$QueueProcessorThread.run(ExecutorManager.java:1221)
Caused by: org.apache.http.client.HttpResponseException: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 Java heap space</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /executor. Reason:
<pre>    Java heap space</pre></p><h3>Caused by:</h3><pre>java.lang.OutOfMemoryError: Java heap space
	at java.util.Hashtable.rehash(Hashtable.java:402)
	at java.util.Hashtable.addEntry(Hashtable.java:426)
	at java.util.Hashtable.put(Hashtable.java:477)
	at org.apache.log4j.Hierarchy.getLogger(Hierarchy.java:277)
	at org.apache.log4j.Hierarchy.getLogger(Hierarchy.java:247)
	at org.apache.log4j.LogManager.getLogger(LogManager.java:228)
	at org.apache.log4j.Logger.getLogger(Logger.java:104)
	at azkaban.execapp.FlowRunner.createLogger(FlowRunner.java:362)
	at azkaban.execapp.FlowRunner.&lt;init&gt;(FlowRunner.java:201)
	at azkaban.execapp.FlowRunner.&lt;init&gt;(FlowRunner.java:165)
	at azkaban.execapp.FlowRunnerManager.createFlowRunner(FlowRunnerManager.java:449)
	at azkaban.execapp.FlowRunnerManager.submitFlow(FlowRunnerManager.java:347)
	at azkaban.execapp.ExecutorServlet.handleAjaxExecute(ExecutorServlet.java:288)
	at azkaban.execapp.ExecutorServlet.handleRequest(ExecutorServlet.java:136)
	at azkaban.execapp.ExecutorServlet.doPost(ExecutorServlet.java:93)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
</pre>
<hr /><i><small>Powered by Jetty://</small></i><br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                
<br/>                                                

</body>
</html>

	at azkaban.executor.ExecutorApiClient.parseResponse(ExecutorApiClient.java:52)
	at azkaban.executor.ExecutorApiClient.parseResponse(ExecutorApiClient.java:31)
	at azkaban.utils.RestfulApiClient.sendAndReturn(RestfulApiClient.java:133)
	at azkaban.utils.RestfulApiClient.httpPost(RestfulApiClient.java:125)
	at azkaban.executor.ExecutorApiGateway.callForJsonString(ExecutorApiGateway.java:125)
	at azkaban.executor.ExecutorApiGateway.callForJsonObjectMap(ExecutorApiGateway.java:102)
	at azkaban.executor.ExecutorApiGateway.callWithExecutionId(ExecutorApiGateway.java:78)
	... 6 more
2020/12/02 14:06:45.390 +0800 WARN [ExecutorManager] [Server] Executor sm-nj-baremetal-htrw-2:12321 (id: 11), active=true responded with exception for exec: 4087964
azkaban.executor.ExecutorManagerException: azkaban.executor.ExecutorManagerException: org.apache.http.client.HttpResponseException: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/>
<title>Error 500 Java heap space</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /executor. Reason:
<pre>    Java heap space</pre></p><h3>Caused by:</h3><pre>java.lang.OutOfMemoryError: Java heap space

**Comment by mjh568412187** [comment]
I have the same problem as you, azkaban version is: 3.47.0
