### ISSUE TITLE
executor became inactive before setting up the flow

### ISSUE THREAD

**Issue by saibalpatra** [azkaban/azkaban#2712]
I am having the following issues with both tag 3.89.0 & 3.90.0, so I am not sure what the issue could be. 

This is happening for the first ever project and first run after setting up the single executor and the web-server (on the same host). 

The executor is active and running as well.

`2021/01/11 22:20:03.276 +0000  INFO [ExecutorServlet] [372469954@qtp-825962150-0] [Azkaban] User  has called action execute on 5
2021/01/11 22:20:03.284 +0000 ERROR [ExecutorServlet] [372469954@qtp-825962150-0] [Azkaban] executor became inactive before setting up the flow 5
azkaban.executor.ExecutorManagerException: executor became inactive before setting up the flow 5
	at azkaban.execapp.FlowRunnerManager.createFlowRunner(FlowRunnerManager.java:444)
	at azkaban.execapp.FlowRunnerManager.submitFlow(FlowRunnerManager.java:393)
	at azkaban.execapp.ExecutorServlet.handleAjaxExecute(ExecutorServlet.java:288)
	at azkaban.execapp.ExecutorServlet.handleRequest(ExecutorServlet.java:136)
	at azkaban.execapp.ExecutorServlet.doPost(ExecutorServlet.java:93)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)`

Creating a issue, because i haven't found any solution of this online.

**Comment by saibalpatra** [comment]
curl http://<executor-hostname>:<executor-port>/executor?action=activate fixes it. However I think this is a hack.
