### ISSUE TITLE
Job suck in preparing phase

### ISSUE THREAD

**Issue by TNorden** [azkaban/azkaban#276]
We have an issue that comes pretty regularly where a scheduled job gets stuck in the preparing phase and never executes.  We recently upgraded to 2.6.1,  the issue began when we upgraded from 2.1 to 2.5.
![job stuck in preparing phase](https://cloud.githubusercontent.com/assets/805182/3509907/eb3bfa56-06a0-11e4-8d36-674599d4f8bb.png)

To work around this we have another job that looks for jobs that are stuck in preparing phase and manually kick them off again.

Here's what I see in the logs
web-server

```
2014/07/07 12:50:16.674 -0400 INFO [ExecutorServlet] [Azkaban] User null has called action execute on 240745
2014/07/07 12:50:16.678 -0400 ERROR [ExecutorServlet] [Azkaban] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2014/07/07 12:50:16.682 -0400 ERROR [TriggerManager] [Azkaban] Failed to do action Execute flow camus_json from project dactar
java.lang.RuntimeException: azkaban.executor.ExecutorManagerException: java.io.IOException: Index: 0, Size: 0
        at azkaban.trigger.builtin.ExecuteFlowAction.doAction(ExecuteFlowAction.java:249)
        at azkaban.trigger.TriggerManager$TriggerScannerThread.onTriggerTrigger(TriggerManager.java:314)
        at azkaban.trigger.TriggerManager$TriggerScannerThread.checkAllTriggers(TriggerManager.java:295)
        at azkaban.trigger.TriggerManager$TriggerScannerThread.run(TriggerManager.java:234)
Caused by: azkaban.executor.ExecutorManagerException: java.io.IOException: Index: 0, Size: 0
        at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:631)
        at azkaban.executor.ExecutorManager.submitExecutableFlow(ExecutorManager.java:600)
        at azkaban.trigger.builtin.ExecuteFlowAction.doAction(ExecuteFlowAction.java:243)
        ... 3 more
Caused by: java.io.IOException: Index: 0, Size: 0
        at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:715)
        at azkaban.executor.ExecutorManager.callExecutorServer(ExecutorManager.java:628)
        ... 5 more
```

exec-server

```
2014-07-07_16:50:16.67499 2014/07/07 12:50:16.674 -0400 INFO [ExecutorServlet] [Azkaban] User null has called action execute on 240745
2014-07-07_16:50:16.67901 2014/07/07 12:50:16.678 -0400 ERROR [ExecutorServlet] [Azkaban] java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
2014-07-07_16:50:16.67902 12:50:16.678 [1946560634@qtp-1832330838-126 - /executor?action=execute&execid=240745] DEBUG org.mortbay.log - RESPONSE /executor  200
2014-07-07_16:50:16.67928 12:50:16.679 [1946560634@qtp-1832330838-126] DEBUG org.mortbay.log - EOF
```

Has anyone run into this before?

Thanks

**Comment by danybenjamin** [comment]
I am seeing a similar issue. 

Azkaban will not let me submit more than 10 jobs. However, it is not doing anything with the jobs in "Preparing" state. It did kill one job eventually - saying it was unresponsive and evicted it. 

Is there a way to kill these executions while in "Preparing" stage? Even if it's manually from the DB. 

![image](https://cloud.githubusercontent.com/assets/16887748/18460995/b7736cf8-793b-11e6-9bc7-f9fa5d244aaa.png)

**Comment by zhangys-lucky** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/8286834/190442893-ecf7bc28-f202-4cdf-b06b-de0c812fc10c.png">
I have solved this by delete rows in EXECUTION_JOBS table in h2.mv.db manually
