### ISSUE TITLE
Unable to start azkaban on openJDK 11

### ISSUE THREAD

**Issue by mvineza** [azkaban/azkaban#2865]
I'm facing this issue when starting the UI part.

```
2021/05/27 10:29:27.122 +0900 INFO [TriggerManager] [Azkaban] TriggerManager loaded.
2021/05/27 10:29:27.126 +0900 INFO [AzkabanWebServerModule] [Azkaban] Loading user manager class azkaban.user.XmlUserManager
2021/05/27 10:29:27.147 +0900 ERROR [AzkabanWebServerModule] [Azkaban] Could not instantiate UserManager azkaban.user.XmlUserManager
2021/05/27 10:29:27.184 +0900 ERROR [StdOutErrRedirect] [Azkaban] Exception in thread "main"
2021/05/27 10:29:27.189 +0900 ERROR [StdOutErrRedirect] [Azkaban] com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error in custom provider, java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:80)
  at azkaban.webapp.AzkabanWebServerModule.createUserManager(AzkabanWebServerModule.java:80)
  while locating azkaban.user.UserManager
    for the 8th parameter of azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:165)
  at azkaban.webapp.AzkabanWebServer.class(AzkabanWebServer.java:122)
  while locating azkaban.webapp.AzkabanWebServer

1 error
2021/05/27 10:29:27.190 +0900 ERROR [StdOutErrRedirect] [Azkaban]       at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
2021/05/27 10:29:27.190 +0900 ERROR [StdOutErrRedirect] [Azkaban]       at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
```

The executor starts fine.

```
...
2021/05/25 15:51:14.524 +0900 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
2021/05/25 15:51:14.525 +0900 INFO [FlowRunnerManager] [Azkaban] Cleaning recently finished
2021/05/25 15:52:14.525 +0900 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
2021/05/25 15:52:14.526 +0900 INFO [FlowRunnerManager] [Azkaban] Cleaning old projects
2021/05/25 15:53:14.526 +0900 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
2021/05/25 15:53:14.526 +0900 INFO [FlowRunnerManager] [Azkaban] Cleaning recently finished
2021/05/25 15:54:14.527 +0900 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
2021/05/25 15:55:14.527 +0900 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
2021/05/25 15:55:14.528 +0900 INFO [FlowRunnerManager] [Azkaban] Cleaning recently finished
2021/05/25 15:56:14.528 +0900 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
2021/05/25 15:57:14.528 +0900 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
2021/05/25 15:57:14.529 +0900 INFO [FlowRunnerManager] [Azkaban] Cleaning recently finished
2021/05/25 15:57:14.529 +0900 INFO [FlowRunnerManager] [Azkaban] Cleaning old projects
2021/05/25 15:58:14.529 +0900 INFO [FlowRunnerManager] [Azkaban] # of executing flows: 0
```

Here are the versions:

Azkaban: 3.57.0/3.81.2
openJDK: 11

We have multiple azkaban installations (using same versions I mentioned above) on openJDK 1.8. They work without any issues.

This is the fist time we are trying with openJDK 11. I'm not sure if it s supported. Kindly help with this. Thank you.

**Comment by mvineza** [comment]
It appeared that the user running azkaban has extra class paths via HIVE_HOME. When I unexport it and start the UI, it works perfectly.

```
unset HIVE_HOME
bin/start-web.sh
```
