### ISSUE TITLE
[/] [Azkaban] unavailable com.google.inject.ConfigurationException: Guice configuration errors:

### ISSUE THREAD

**Issue by harryus10** [azkaban/azkaban#3031]
I'm using azkaban 4.0.0 version of code.
I'm getting the below error while azkaban web server start up and unable to schedule event as well.

[/] [Azkaban] unavailable
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for azkaban.imagemgmt.services.ImageRampupService was bound.
  while locating azkaban.imagemgmt.services.ImageRampupService

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1045)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at azkaban.ServiceProvider.getInstance(ServiceProvider.java:54)
	at azkaban.webapp.AzkabanWebServer.getImageRampupService(AzkabanWebServer.java:752)
	at azkaban.imagemgmt.servlets.ImageRampupServlet.init(ImageRampupServlet.java:78)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:736)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at azkaban.webapp.AzkabanWebServer.prepareAndStartServer(AzkabanWebServer.java:530)
	at azkaban.webapp.AzkabanWebServer.launch(AzkabanWebServer.java:258)
	at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:249)
2022/01/11 17:36:35.932 -0600 ERROR [/] [Azkaban] unavailable
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for azkaban.imagemgmt.services.ImageTypeService was bound.
  while locating azkaban.imagemgmt.services.ImageTypeService

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1045)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at azkaban.ServiceProvider.getInstance(ServiceProvider.java:54)
	at azkaban.webapp.AzkabanWebServer.getImageTypeService(AzkabanWebServer.java:744)
	at azkaban.imagemgmt.servlets.ImageTypeServlet.init(ImageTypeServlet.java:67)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:736)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at azkaban.webapp.AzkabanWebServer.prepareAndStartServer(AzkabanWebServer.java:530)
	at azkaban.webapp.AzkabanWebServer.launch(AzkabanWebServer.java:258)
	at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:249)
2022/01/11 17:36:35.933 -0600 ERROR [/] [Azkaban] unavailable
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for azkaban.imagemgmt.services.ImageVersionService was bound.
  while locating azkaban.imagemgmt.services.ImageVersionService

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1045)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
	at azkaban.ServiceProvider.getInstance(ServiceProvider.java:54)
	at azkaban.webapp.AzkabanWebServer.getImageVersionsService(AzkabanWebServer.java:748)
	at azkaban.imagemgmt.servlets.ImageVersionServlet.init(ImageVersionServlet.java:78)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:736)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:518)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at azkaban.webapp.AzkabanWebServer.prepareAndStartServer(AzkabanWebServer.java:530)
	at azkaban.webapp.AzkabanWebServer.launch(AzkabanWebServer.java:258)
	at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:249)

Please let me know is there any cnfiguration missing ?

**Comment by wmtbnbo** [comment]
Please,Have you solved this problem?

**Comment by sewenc** [comment]
how to fix it?
