### ISSUE TITLE
How can I  use Hive-0.13.1 with azkaban?

### ISSUE THREAD

**Issue by alexBJW** [azkaban/azkaban#305]
I  installed the jobtypes,but the hive job does not work well, the errors like this :
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.hadoop.hive.shims.HadoopShims.usesJobShell()Z
14-08-2014 15:13:19 CST hive-demo ERROR -     at azkaban.jobtype.HadoopSecureHiveWrapper.runHive(HadoopSecureHiveWrapper.java:148)
14-08-2014 15:13:19 CST hive-demo ERROR -     at azkaban.jobtype.HadoopSecureHiveWrapper.main(HadoopSecureHiveWrapper.java:115)

and I find this:https://issues.apache.org/jira/browse/HIVE-5786

How can I resolve the problem and use hive-0.13.1?

**Comment by mkanchwala** [comment]
Any updates on the same? I am also facing the same issue, Please help!

I am using Azkaban 3.0

**Comment by mkanchwala** [comment]
Any updates on the same?

**Comment by xibeilijp** [comment]
Hi,everyone.
I want to ask a question.
when I use hive-1.2.1 and zeppelin-0.5.6,I got an error like blow:
nosuchmethor: org.apache.hadoop.hive.shims.HadoopShims.isSecurityEnabled()Z()
Is this a hive bug?
Thk

**Comment by xibeilijp** [comment]
when I see blow the information.It is dead code.
https://issues.apache.org/jira/browse/HIVE-5786
