### ISSUE TITLE
Flow throws exception but doesn't fail

### ISSUE THREAD

**Issue by markgrover** [azkaban/azkaban#313]
I had a validate.job that looked like:
type=command
command=bash validate.sh

And, validate.sh looked like (note this bad json, there is an extra double quote after the first single quote right after echo):
# !/bin/bash

echo '"{"validate-errors":"true"}' > $JOB_OUTPUT_PROP_FILE

The job threw a class cast exception:
03-09-2014 12:30:35 PDT validate INFO - Starting job validate at 1409772635984
03-09-2014 12:30:35 PDT validate INFO - Building command job executor. 
03-09-2014 12:30:35 PDT validate INFO - 1 commands to execute.
03-09-2014 12:30:36 PDT validate INFO - Command: bash validate.sh
03-09-2014 12:30:36 PDT validate INFO - Environment variables: {JOB_NAME=validate, JOB_PROP_FILE=/root/azkaban-executor-2.5.0/executions/32/capture-and-decide/validate_props_3255351895462800573_tmp, JOB_OUTPUT_PROP_FILE=/root/azkaban-executor-2.5.0/executions/32/capture-and-decide/validate_output_5993816385795606192_tmp}
03-09-2014 12:30:36 PDT validate INFO - Working directory: /root/azkaban-executor-2.5.0/executions/32/capture-and-decide
03-09-2014 12:30:36 PDT validate INFO - Process completed successfully in 0 seconds.
03-09-2014 12:30:36 PDT validate ERROR - Exception thrown when trying to load output file props.  Returning empty Props instead of failing.  Is this really the best thing to do?
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
    at azkaban.jobExecutor.AbstractProcessJob.loadOutputFileProps(AbstractProcessJob.java:139)
    at azkaban.jobExecutor.AbstractProcessJob.generateProperties(AbstractProcessJob.java:191)
    at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:103)
    at azkaban.execapp.JobRunner.runJob(JobRunner.java:516)
    at azkaban.execapp.JobRunner.run(JobRunner.java:436)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
03-09-2014 12:30:36 PDT validate INFO - Finishing job validate at 1409772636006 with status SUCCEEDED

But ended up succeeding. Shouldn't it fail if there was an exception involved?

**Comment by sanaayakurup** [comment]
Were you able to solve this?
