### ISSUE TITLE
global.properties global variables not working. Could not find variable substitution for variable(s)

### ISSUE THREAD

**Issue by ismailsimsek** [azkaban/azkaban#320]
I have some global variables defined in the azkaban installation /conf/ directory 
azkaban/execserver/conf/global.properties
but when i run a job using this global variable having following error. 
Could not find variable substitution for variable(s)
same for 2.6.2, 2.6.1, 2.6.0

Working ok in 2.5  version which is from
http://azkaban.github.io/downloads.html
https://s3.amazonaws.com/azkaban2/azkaban2/2.5.0/azkaban-executor-server-2.5.0.tar.gz

11-09-2014 12:57:28 CEST bob_myjob ERROR - Failed to build job executor for job bob_myjobCould not find variable substitution for variable(s) [command->test]

11-09-2014 12:57:28 CEST bob_myjob INFO - Starting job bob_myjob at 1410433048297
11-09-2014 12:57:28 CEST bob_myjob INFO - azkaban.webserver.url property was not set
11-09-2014 12:57:28 CEST bob_myjob INFO - job JVM args: -Dazkaban.flowid=bob_myjob -Dazkaban.execid=22 -Dazkaban.jobid=bob_myjob
11-09-2014 12:57:28 CEST bob_myjob INFO - Building command job executor. 
11-09-2014 12:57:28 CEST bob_myjob ERROR - Failed to build job executor for job bob_myjobCould not find variable substitution for variable(s) [command->test]
11-09-2014 12:57:28 CEST bob_myjob ERROR - Failed to build job type
azkaban.jobtype.JobTypeManagerException: Failed to build job executor for job bob_myjob
    at azkaban.jobtype.JobTypeManager.buildJobExecutor(JobTypeManager.java:366)
    at azkaban.execapp.JobRunner.prepareJob(JobRunner.java:518)
    at azkaban.execapp.JobRunner.run(JobRunner.java:439)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: azkaban.utils.UndefinedPropertyException: Could not find variable substitution for variable(s) [command->test]
    at azkaban.utils.PropsUtils.resolveVariableReplacement(PropsUtils.java:196)
    at azkaban.utils.PropsUtils.resolveProps(PropsUtils.java:156)
    at azkaban.jobtype.JobTypeManager.buildJobExecutor(JobTypeManager.java:351)
    ... 7 more
11-09-2014 12:57:28 CEST bob_myjob ERROR - Job run failed preparing the job.
11-09-2014 12:57:28 CEST bob_myjob INFO - Finishing job bob_myjob at 1410433048303 with status FAILED

**Comment by vikramkone** [comment]
+1 I'm also seeing the same issue. I want to define some system level static variables in the global.properties file, which I can then reference in the .job file. Looks like this doesn't work?
Only variables defined in the *.properties files that are part of the zip package are working correctly.

**Comment by aslotnick** [comment]
I'm running into a similar issue in version 3.1.0.  This functionality was working on 2.5.0 but I can't get it to work with the later version. 

I have defined a property in the file "azkaban-exec-server-3.1.0/conf/global.properties".  And I have set "executor.global.properties=conf/global.properties" in the file "azkaban-exec-server-3.1.0/conf/global.properties".  

However, command jobs are not picking up the property from this file.

Any idea what I might be doing wrong? Or, should this feature be removed from the 3.x documentation?

Thank you.

**Comment by gladmon** [comment]
I was able to get this to work, but only by looking through source and how the properties are loaded. You need to do the following from the azkaban-exec-server-3.8.0/ folder (thats the version we are using):
`    mkdir -p plugins/jobtypes/command
    touch plugins/jobtypes/common.properties
    touch plugins/jobtypes/command/plugin.properties
    echo 'jobtype.class=azkaban.jobExecutor.ProcessJob' > plugins/jobtypes/command/private.properties`

**Comment by trentgerman** [comment]
@gladmon does this solution only work for jobs of type command? Or will it work for all job types?
