### ISSUE TITLE
VelocityException if no Viewer Plugin

### ISSUE THREAD

**Issue by threeseed** [azkaban/azkaban#327]
If there is a viewer plugin directory e.g. /opt/azkaban/plugins/viewer but there are no viewer plugins installed then the following exception is thrown:

`
java.lang.RuntimeException: JarResourceLoader : JAR path must start with jar: -> see java.net.JarURLConnection for information
    at org.apache.velocity.runtime.resource.loader.JarResourceLoader.loadJar(JarResourceLoader.java:143)
    at org.apache.velocity.runtime.resource.loader.JarResourceLoader.init(JarResourceLoader.java:118)
    at org.apache.velocity.runtime.resource.ResourceManagerImpl.initialize(ResourceManagerImpl.java:143)
    at org.apache.velocity.runtime.RuntimeInstance.initializeResourceManager(RuntimeInstance.java:730)
    at org.apache.velocity.runtime.RuntimeInstance.init(RuntimeInstance.java:263)
    at org.apache.velocity.runtime.RuntimeInstance.requireInitialization(RuntimeInstance.java:302)
    at org.apache.velocity.runtime.RuntimeInstance.getTemplate(RuntimeInstance.java:1531)
    at org.apache.velocity.app.VelocityEngine.mergeTemplate(VelocityEngine.java:343)
    at azkaban.webapp.servlet.Page.render(Page.java:67)
`

**Comment by zuzeep** [comment]
in version 3.50, if path azkaban-webserver/plugins/triggers is empty, it will the same exception.
