### ISSUE TITLE
Error on trying to run example job

### ISSUE THREAD

**Issue by afarnoosh** [azkaban/azkaban#367]
Solo Setup is done, 
azkaban-jobtype-2.5.0 and azkaban-reportal-2.5.0 added to plugins.

On downloading and running the example jobs in the documentation, I get the following error on the UI:

Installation Failed. /51838945/java-wc.zip (No such file or directory)

And the following error in the logs:

2014/12/05 06:59:17.143 +0000 INFO [ProjectManagerServlet] [Azkaban] Uploading file java-wc.zip
2014/12/05 06:59:17.144 +0000 INFO [ProjectManagerServlet] [Azkaban] Installation Failed.
java.io.FileNotFoundException: /51838945/java-wc.zip (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:145)
    at azkaban.webapp.servlet.ProjectManagerServlet.ajaxHandleUpload(ProjectManagerServlet.java:1385)
    at azkaban.webapp.servlet.ProjectManagerServlet.handleUpload(ProjectManagerServlet.java:1414)
    at azkaban.webapp.servlet.ProjectManagerServlet.handleMultiformPost(ProjectManagerServlet.java:163)
    at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.doPost(LoginAbstractAzkabanServlet.java:240)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
2014/12/05 06:59:17.415 +0000 INFO [LoginAbstractAzkabanServlet] [Azkaban] Session id fc351312-4e5c-49f6-9a3b-2fdf7a7fc552
2014/12/05 06:59:17.415 +0000 INFO [LoginAbstractAzkabanServlet] [Azkaban] Found session admin: [azkaban,]
2014/12/05 07:00:15.707 +0000 INFO [FlowRunnerManager] [Azkaban] Cleaning recently finished
2014/12/05 07:00:15.708 +0000 INFO [FlowRunnerManager] [Azkaban] Cleaning old projects

**Comment by karanluthra** [comment]
I faced the same error message when uploading a project zip to a project (both via the WebUI and the AJAX API) and I found that starting the server like
`./bin/azkaban-solo-start.sh`
instead of
`sh bin/azkaban-solo-start.sh`
helps solve my case. Haven't thought yet why this happens though.

**Comment by PaniniGelato** [comment]
got the same error while uploading..

the comment of @karanluthra saved my life

i am using azkaban v3.0
