### ISSUE TITLE
Server failed to handle advanced filter using datetime interval in the history view

### ISSUE THREAD

**Issue by geterns** [azkaban/azkaban#384]
Query URL generated by the filter like this __https://myhost:8443/history?advfilter=true&projcontain=test&flowcontain=d&usercontain=&status=0&begin=01/10/2015%206:46%20AM&end=01/10/2015%206:46%20PM__ triggers this issue, in which case the server returns the following ERROR message. I read the piece of code and it seems that changing my time zone to __Asia/Chongqing__ will cause the parseDateTime function to throw an exception. But have no idea how to fix this yet, can you guys have a look at this? Thank you.

HTTP ERROR 500

Problem accessing /history. Reason:

    Invalid format: "01/10/2015 6:46 AM" is malformed at " 6:46 AM"
Caused by:

java.lang.IllegalArgumentException: Invalid format: "01/10/2015 6:46 AM" is malformed at " 6:46 AM"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:866)
	at azkaban.webapp.servlet.HistoryServlet.handleHistoryPage(HistoryServlet.java:127)
	at azkaban.webapp.servlet.HistoryServlet.handleGet(HistoryServlet.java:71)
	at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.doGet(LoginAbstractAzkabanServlet.java:106)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.jetty.security.SslSocketConnector$SslConnection.run(SslSocketConnector.java:713)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Powered by Jetty://

**Comment by tmwilder** [comment]
I'm able to reproduce this for all time ranges I try to filter on for Azkaban solo 2.5.0.
