### ISSUE TITLE
log4j issues when launching azkaban 2.7

### ISSUE THREAD

**Issue by eualin** [azkaban/azkaban#531]
I have successfully build azkaban 2.7 (solo-server) yet I get the following error when I try to lunch the service. Any ideas?

```
$ ./bin/azkaban-solo-start.sh
Error: HADOOP_HOME is not set. Hadoop job types will not run properly.
./bin/..
:./bin/../lib/azkaban-common-2.7.0.jar:./bin/../lib/azkaban-execserver-2.7.0.jar:./bin/../lib/azkaban-soloserver-2.7.0.jar:./bin/../lib/azkaban-webserver-2.7.0.jar:./bin/../lib/commons-codec-1.9.jar:./bin/../lib/commons-collections-3.2.1.jar:./bin/../lib/commons-configuration-1.8.jar:./bin/../lib/commons-dbcp-1.4.jar:./bin/../lib/commons-dbutils-1.5.jar:./bin/../lib/commons-email-1.2.jar:./bin/../lib/commons-fileupload-1.2.1.jar:./bin/../lib/commons-io-2.4.jar:./bin/../lib/commons-jexl-2.1.1.jar:./bin/../lib/commons-lang-2.6.jar:./bin/../lib/commons-logging-1.1.1.jar:./bin/../lib/commons-math3-3.0.jar:./bin/../lib/commons-pool-1.6.jar:./bin/../lib/data-1.15.7.jar:./bin/../lib/gradle-plugins-1.15.7.jar:./bin/../lib/guava-13.0.1.jar:./bin/../lib/h2-1.3.170.jar:./bin/../lib/httpclient-4.3.1.jar:./bin/../lib/httpcore-4.3.jar:./bin/../lib/jackson-core-2.3.2.jar:./bin/../lib/jackson-core-asl-1.9.5.jar:./bin/../lib/jackson-mapper-asl-1.9.5.jar:./bin/../lib/jetty-6.1.26.jar:./bin/../lib/jetty-util-6.1.26.jar:./bin/../lib/joda-time-2.0.jar:./bin/../lib/jopt-simple-4.3.jar:./bin/../lib/li-jersey-uri-1.15.7.jar:./bin/../lib/log4j-1.2.16.jar:./bin/../lib/mail-1.4.5.jar:./bin/../lib/mysql-connector-java-5.1.28.jar:./bin/../lib/parseq-1.3.7.jar:./bin/../lib/pegasus-common-1.15.7.jar:./bin/../lib/r2-1.15.7.jar:./bin/../lib/restli-common-1.15.7.jar:./bin/../lib/restli-server-1.15.7.jar:./bin/../lib/servlet-api-2.5.jar:./bin/../lib/slf4j-api-1.6.1.jar:./bin/../lib/velocity-1.7.jar:./bin/../lib/velocity-tools-2.0.jar:./bin/../extlib/*.jar:./bin/../plugins/*/*.jar

$ log4j:WARN No such property [maxBackupIndex] in org.apache.log4j.DailyRollingFileAppender.
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /azkaban-execserver.log (Permission denied)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
    at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
    at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
    at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
    at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
    at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
    at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
    at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:809)
    at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:735)
    at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:615)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:502)
    at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:547)
    at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
    at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
    at org.apache.log4j.Logger.getLogger(Logger.java:117)
    at azkaban.soloserver.AzkabanSingleServer.<clinit>(AzkabanSingleServer.java:29)
log4j:ERROR Either File or DatePattern options are not set for appender [ExecServer].
Exception in thread "main" joptsimple.UnrecognizedOptionException: 'debug' is not a recognized option
    at joptsimple.OptionException.unrecognizedOption(OptionException.java:88)
    at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:403)
    at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:54)
    at joptsimple.OptionParser.parse(OptionParser.java:379)
    at azkaban.server.AzkabanServer.loadProps(AzkabanServer.java:62)
    at azkaban.server.AzkabanServer.loadProps(AzkabanServer.java:44)
    at azkaban.soloserver.AzkabanSingleServer.main(AzkabanSingleServer.java:34)
```

**Comment by jdkanani** [comment]
+1 Facing same issue.
