### ISSUE TITLE
How to use "export" is command job type in azkaban

### ISSUE THREAD

**Issue by vikramkone** [azkaban/azkaban#550]
Hi,
I have written a simple job config as follows , ie supposed to show the maven version number

#my.job
command="export foo=$9mvn -v)"
command.1=echo $foo

Azkaban doesn't seem to like this as its not able to interpret the shell command correctly.. what's the right way to execute shell commands inline in the command jobtype w/o resorting to writing a shell script for this purpose?

21-10-2015 15:01:11 PDT test ERROR - Failed to build job executor for job testExpression "export foo=$(mvn -v)" not well formed. b@1:23 parsing error near '... t, missing ...'
21-10-2015 15:01:11 PDT test ERROR - Failed to build job type
azkaban.jobtype.JobTypeManagerException: Failed to build job executor for job test
	at azkaban.jobtype.JobTypeManager.buildJobExecutor(JobTypeManager.java:366)
	at azkaban.execapp.JobRunner.prepareJob(JobRunner.java:520)
	at azkaban.execapp.JobRunner.run(JobRunner.java:439)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Expression "

**Comment by davidzchen** [comment]
Hi @vikramkone, it looks like the `$()` syntax is clashing with some post-processing that Azkaban is doing to the properties files. I'll take a look.

**Comment by vikramkone** [comment]
Thanks David. Basically, I want to know how to pass output of a command to another command.
I know that we can pass outputs between jobs by writing to JOB_PROP_OUTPUT_FILE.
But, is it possible to pass data between commands?
ex:
#myjob.job
command=export foo=bar
command1.=echo $foo

Also, it would be great if I can do something like
command=bash script1.sh
command1=bash script2.sh ${command1.stdout}

Hope it makes sense

**Comment by sundy-li** [comment]
I found that command `source` is also not work in azkaban, is that any way to pass some properties dynamically? such as `from=`date -d "-1 days" "+%Y-%m-%dT00"`` but i could not use `${from}` cause azkaban will look up into the .properties file to replace ${}

**Comment by aupadhyay0606** [comment]
Any update on this issue?

**Comment by ismailsimsek** [comment]
+1

**Comment by Shubhirb** [comment]
Any update on how to pass parameters dynamically?

**Comment by yjmeng** [comment]
any update on this issue???

**Comment by mahmoudmahdi24** [comment]
any updates ?

**Comment by belbis** [comment]
Doesn't seem like this was ever resolved, but I was working with a similar issue working with time based 

example storing variable:
```command='export dt=`date -d "- 1 hours"`; echo $dt'```

example executing subshell:
```command='echo `date -d "- 1 hours"`'```

example if you need to use variables across commands:
```bash
command='echo `date -d "-1 hours"` > /tmp/date_persist.txt;'
command.1='export dt=`cat /tmp/date_persist.txt`; echo $dt;'
command.2='echo `cat /tmp/date_persist.txt`;'
command.3='rm /tmp/date_persist.txt;'
```

of course you can try to leverage JOB_OUTPUT_PROP_FILE for doing this, but I found the shell commands easier to navigate.

hope this helps future stuck people.
