### ISSUE TITLE
Can't no upload a job with dependece

### ISSUE THREAD

**Issue by sowe** [azkaban/azkaban#568]
I try to create a basic dependency, but i can't . i'm using a *azkaban-solo-2.5.0* with MySQL. attached  the job.  

This is a log trace:
2015/11/13 15:06:13.828 +0100 ERROR [ProjectManager] [Azkaban] Error found in upload to Oleg. Cleaning up.
2015/11/13 15:06:13.829 +0100 INFO [ProjectManagerServlet] [Azkaban] Installation Failed.
azkaban.project.ProjectManagerException: Error found in upload. Cannot upload.
basic_2nd_command cannot find dependency basic_1st_command *<< this is the label azkaban show me ¡¡¡¡¡¡*
	at azkaban.project.ProjectManager.uploadProject(ProjectManager.java:341)
	at azkaban.webapp.servlet.ProjectManagerServlet.ajaxHandleUpload(ProjectManagerServlet.java:1389)
	at azkaban.webapp.servlet.ProjectManagerServlet.handleUpload(ProjectManagerServlet.java:1414)
	at azkaban.webapp.servlet.ProjectManagerServlet.handleMultiformPost(ProjectManagerServlet.java:163)
	at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.doPost(LoginAbstractAzkabanServlet.java:240)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:945)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

The flow is :
[job1] --> [job2]
and the jobs :
file name : basic_1st_command.job
job1:
type=command
command=echo "basic_1st_command.job"
file name :basic_2st_command.job
job2:
type=command
command=echo "basic_2nd_command.job"
dependencies=basic_1st_command

**Comment by davidzchen** [comment]
Hi @sowe - what are the file names you are using for your job files?

**Comment by vikramkone** [comment]
@sowe Your dependencies should match the name of the job file. So Job1.job dependeds on Job2.job then dependencies=job2

**Comment by sowe** [comment]
Hi @davidzchen and @vikramkone  thanks for your comments 
zip name for first job -> basic_1st_command.job.zip
zip name for second job -> basic_2nd_command.job.zip or basic_2nd_command.zip
any problem for that ?

**Comment by davidzchen** [comment]
@sowe Both jobs should be in the same zip file. Your zip file would contain the following files:

* `basic_1st_comand.job`
* `basic_2nd_command.job`

**Comment by sowe** [comment]
Hi @davidzchen  
OK, I got it , i thought i could to upload a single file with a new job .
