### ISSUE TITLE
java.sql.SQLException: Unknown column 'ex.executor_id' in 'on clause' 

### ISSUE THREAD

**Issue by jeroenvlek** [azkaban/azkaban#582]
This is a cross-post from the Google group. I reckoned it's more appropriate here:

We get an exception right off the bat after starting the webserver:

Exception in thread "main" azkaban.executor.ExecutorManagerException: Error fetching active flows 
       at azkaban.executor.JdbcExecutorLoader.fetchActiveFlows(JdbcExecutorLoader.java:216) 
       at azkaban.executor.ExecutorManager.loadRunningFlows(ExecutorManager.java:431) 
       at azkaban.executor.ExecutorManager.<init>(ExecutorManager.java:126) 
       at azkaban.webapp.AzkabanWebServer.loadExecutorManager(AzkabanWebServer.java:261) 
       at azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:197) 
       at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:739) 
Caused by: java.sql.SQLException: Unknown column 'ex.executor_id' in 'on clause' Query: SELECT ex.exec_id exec_id, ex.enc_type enc_type, ex.flow_data flow_data, et.host host, et.port port, ax.update_time axUpdateTime, et.id executorId, 
et.active executorStatus FROM execution_flows ex INNER JOIN  active_executing_flows ax ON ex.exec_id = ax.exec_id INNER JOIN  executors et ON ex.executor_id = et.id Parameters: [] 
       at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:363) 
       at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:350) 
       at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:306) 
       at azkaban.executor.JdbcExecutorLoader.fetchActiveFlows(JdbcExecutorLoader.java:212)

Shouldn't that column name be 'exec_id' instead of 'executor_id'? The conflicting line would be JdbcExecutorLoader line 1333.

**Comment by jeroenvlek** [comment]
On further inspection, it seems that the following is simply missing from create.execution_flows.sql:

executor_id INT NOT NULL

**Comment by logiclord** [comment]
Please update db schema as per http://azkaban.github.io/azkaban/docs/latest/#upgrade-27

**Comment by jeroenvlek** [comment]
Thanks for updating the online docs to 3.0!

**Comment by jeroenvlek** [comment]
PS: This was a vanilla install, not an upgrade from 2.7. You might want to clarify that in the documentation.

**Comment by logiclord** [comment]
Good catch. Can you please file another bug for documentation update ?

**Comment by juhoautio** [comment]
#591 has the required sql scripts.
