### ISSUE TITLE
 kerberos integration  problem

### ISSUE THREAD

**Issue by wanbin2014** [azkaban/azkaban#611]
I am trying to use azkanban to start job in my  company cluster. The cluster is security cluster,surpport kerberos authentication. and the cluster version is CDH5.5.0 .we use mapreduce 2.0

I started a hadoop shell job.  I met a problem.  the following is log:

23-02-2016 15:35:12 CST test INFO - Starting job test at 1456212912016
23-02-2016 15:35:12 CST test INFO - job JVM args: -Dazkaban.flowid=test -Dazkaban.execid=463 -Dazkaban.jobid=test
23-02-2016 15:35:12 CST test INFO - Building hadoopShell job executor. 
23-02-2016 15:35:12 CST test INFO - Initiating hadoop security manager.
23-02-2016 15:35:12 CST test INFO - Loading hadoop security manager azkaban.security.HadoopSecurityManager_H_2_0
23-02-2016 15:35:12 CST test INFO - Need to proxy. Getting tokens.
23-02-2016 15:35:12 CST test INFO - Getting hadoop tokens based on props for az3
23-02-2016 15:35:12 CST test INFO - Here is the props for obtain.namenode.token: true
23-02-2016 15:35:12 CST test INFO - Getting DFS token from hdfs://m1.cdh.host.dxy:8020
23-02-2016 15:35:12 CST test INFO - Created DFS token: Kind: HDFS_DELEGATION_TOKEN, Service: 192.168.200.35:8020, Ident: (HDFS_DELEGATION_TOKEN token 221162 for az3)
23-02-2016 15:35:12 CST test INFO - Token kind: HDFS_DELEGATION_TOKEN
23-02-2016 15:35:12 CST test INFO - Token id: [B@42ec798c
23-02-2016 15:35:12 CST test INFO - Token service: 192.168.200.35:8020
23-02-2016 15:35:12 CST test INFO - other_namenodes was not configured
23-02-2016 15:35:12 CST test INFO - Pre-fetching JT token from JobTracker
23-02-2016 15:35:12 CST test ERROR - Failed to fetch JT token
23-02-2016 15:35:12 CST test ERROR - Job run failed!
azkaban.security.commons.HadoopSecurityManagerException: Failed to get hadoop tokens! nullazkaban.security.commons.HadoopSecurityManagerException: Failed to fetch JT token for az3
	at azkaban.security.HadoopSecurityManager_H_2_0.prefetchToken(HadoopSecurityManager_H_2_0.java:724)
	at azkaban.jobtype.HadoopJobUtils.getHadoopTokens(HadoopJobUtils.java:162)
	at azkaban.jobtype.HadoopShell.run(HadoopShell.java:82)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:590)
	at azkaban.execapp.JobRunner.run(JobRunner.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

---------------------------

The following is commonprivate.properties:
hadoop.security.manager.class=azkaban.security.HadoopSecurityManager_H_2_0

## hadoop security related settings
proxy.keytab.location=/tmp/az3.keytab
proxy.user=az3

azkaban.should.proxy=true
obtain.binary.token=true
obtain.namenode.token=true
obtain.jobtracker.token=true
-----------------------------

I puzzle why can't get delegation token from resourcemanager? 
Does it has problem about configuration file or does azkaban have bugs about security cluster?
Thank you!

**Comment by moranrr** [comment]
I also encountered this problem, Does anyone know how to solve this problem?

**Comment by wmy1997** [comment]
not only hadoop,but alse hive shell ..this is i'm meeting. it's about kerberos . so , if someone know that how to solve this problem.i'll think ~
