### ISSUE TITLE
hadoop-inject.azkaban.link.execution.url is null?

### ISSUE THREAD

**Issue by bigyou** [azkaban/azkaban#628]
Azkaban's code is cloned from master branch .
 when  I run the hive job it throws Exception as follows.
The reason is the  value of "hadoop-inject.azkaban.link.execution.url" is null, 
and how can i config the hadoop-inject.xml file to fix the problem and to   run the azkaban hive job  correctly?

sincerely Thanks .

key:hadoop-inject.azkaban.link.execution.url value=null,

java.lang.Exception: Bad property definition! null
	at azkaban.jobExecutor.ProcessJob.handleError(ProcessJob.java:253)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:73)
	at azkaban.jobtype.HadoopHiveJob.run(HadoopHiveJob.java:100)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:590)
	at azkaban.execapp.JobRunner.run(JobRunner.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at azkaban.utils.PropsUtils.resolveVariableExpression(PropsUtils.java:234)
	at azkaban.utils.PropsUtils.resolveProps(PropsUtils.java:179)
	at azkaban.jobExecutor.AbstractProcessJob.resolveProps(AbstractProcessJob.java:84)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:71)

**Comment by radimk** [comment]
Same here: using Azkaban 3.0.0 with plugin I see this exception caused by missing property value for key hadoop-inject.azkaban.link.execution.url. It seems there is some missing configuration step that break these plugins (hadoopJava, hive).
