### ISSUE TITLE
Azkaban-3.1.0 web server running sql failed 

### ISSUE THREAD

**Issue by mycFelix** [azkaban/azkaban#705]
Hi~

I tried to run azkaban-web-server-3.1.0 but failed in two server mode

The log's following:
````
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" azkaban.executor.ExecutorManagerException: Error fetching active flows
	at azkaban.executor.JdbcExecutorLoader.fetchActiveFlows(JdbcExecutorLoader.java:216)
	at azkaban.executor.ExecutorManager.loadRunningFlows(ExecutorManager.java:431)
	at azkaban.executor.ExecutorManager.<init>(ExecutorManager.java:126)
	at azkaban.webapp.AzkabanWebServer.loadExecutorManager(AzkabanWebServer.java:261)
	at azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:197)
	at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:739)
Caused by: java.sql.SQLException: Unknown column 'ex.executor_id' in 'on clause' Query: SELECT ex.exec_id exec_id, ex.enc_type enc_type, ex.flow_data flow_data, et.host host, et.port port, ax.update_time axUpdateTime, et.id executorId, et.active executorStatus FROM execution_flows ex INNER JOIN  active_executing_flows ax ON ex.exec_id = ax.exec_id INNER JOIN  executors et ON ex.executor_id = et.id Parameters: []
	at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:363)
	at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:350)
	at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:306)
	at azkaban.executor.JdbcExecutorLoader.fetchActiveFlows(JdbcExecutorLoader.java:212)
	... 5 more
````

There might be running a wrong sql cause `ex.executor_id` doesn't exist in the table execution_flows,and it should be `ex.exec_id`?
````
mysql> desc execution_flows;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| exec_id     | int(11)      | NO   | PRI | NULL    | auto_increment |
| project_id  | int(11)      | NO   | MUL | NULL    |                |
| version     | int(11)      | NO   |     | NULL    |                |
| flow_id     | varchar(128) | NO   |     | NULL    |                |
| status      | tinyint(4)   | YES  |     | NULL    |                |
| submit_user | varchar(64)  | YES  |     | NULL    |                |
| submit_time | bigint(20)   | YES  |     | NULL    |                |
| update_time | bigint(20)   | YES  |     | NULL    |                |
| start_time  | bigint(20)   | YES  | MUL | NULL    |                |
| end_time    | bigint(20)   | YES  | MUL | NULL    |                |
| enc_type    | tinyint(4)   | YES  |     | NULL    |                |
| flow_data   | longblob     | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
````

**Comment by mycFelix** [comment]
I run `create-all-sql-3.1.0.sql` to create all tables,but failed to find the `executor_id` column.

**Comment by alaleiwang** [comment]
something wrong with JdbcExecutorLoader.java,attach is a simple patch
[JdbcExecutorLoader.patch.txt](https://github.com/azkaban/azkaban/files/415230/JdbcExecutorLoader.patch.txt)

**Comment by sillycow886** [comment]
you should run update.execution_flows.3.0.sql

**Comment by fsi206914** [comment]
@binhnv Please use the last two files () in azkaban-sql folder. https://github.com/azkaban/azkaban/blob/master/azkaban-sql/src/sql/update.execution_flows.3.0.sql

Currently we have to keep the original sql clauses to protect backward compatibility. some people might be using older version of azksban

**Comment by binhnv** [comment]
@fsi206914 Do you use create-all script for upgrading?

**Comment by fsi206914** [comment]
@binhnv I used once. Will update create-all script to handle the new change.

**Comment by mycFelix** [comment]
@fsi206914 - Thank you for your tips
