### ISSUE TITLE
When the server memory is less than 3G performing tasks error

### ISSUE THREAD

**Issue by wanglifengwf** [azkaban/azkaban#711]
### version
- 3.0.0  
- This version has increased control of the server resources  
### Problem
- Performing tasks error  

```
java.lang.Exception: java.lang.Exception: Cannot request memory (Xms 64 kb, Xmx 65536 kb) from system for job testjava
    at azkaban.jobtype.HadoopJavaJob.run(HadoopJavaJob.java:190)
    at azkaban.execapp.JobRunner.runJob(JobRunner.java:590)
    at azkaban.execapp.JobRunner.run(JobRunner.java:443)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Cannot request memory (Xms 64 kb, Xmx 65536 kb) from system for job testjava
    at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:86)
    at azkaban.jobtype.HadoopJavaJob.run(HadoopJavaJob.java:187)
    ... 7 more
```

**azkaban-exec-server** Requires that the server memory free must be greater than 3 g or any task error, and does not support parameter configuration   

```
public synchronized static boolean canSystemGrantMemory(long xms, long xmx, long freeMemDecrAmt) {
    if (!memCheckEnabled) {
      return true;
    }

    //too small amount of memory left, reject
    if (freeMemAmount < LOW_MEM_THRESHOLD) {
      logger.info(String.format("Free memory amount (%d kb) is less than low mem threshold (%d kb),  memory request declined.",
              freeMemAmount, LOW_MEM_THRESHOLD));
      return false;
    }
```

```
boolean isMemGranted =
          SystemMemoryInfo.canSystemGrantMemory(memPair.getFirst(),
              memPair.getSecond(), freeMemDecrAmt);
      if (!isMemGranted) {
        throw new Exception(
            String
                .format(
                    "Cannot request memory (Xms %d kb, Xmx %d kb) from system for job %s",
                    memPair.getFirst(), memPair.getSecond(), getId()));
      }
```

**Comment by fsi206914** [comment]
Hi @wanglifengwf , thanks for reporting this incident. LOW_MEM_THRESHOLD can not be configured currently. If you can contribute the this change and add some tests, that would be great. Thank you for looking into this!

**Comment by Codefor** [comment]
But my question is why azkaban executor require 3G RAM? It actually doesn't need that more

**Comment by fsi206914** [comment]
@Codefor It actually need more for some certain jobs.

**Comment by PaniniGelato** [comment]
memCheck.enabled=false
azkaban.memory.check=false
try add these config to skip memCheck @Codefor

**Comment by vickysirwani** [comment]
the above is not working

**Comment by ameyamk** [comment]
Default solo server now runs with 500MB memmoery
