### ISSUE TITLE
java.lang.stackoverflowerror while uploading a zip file

### ISSUE THREAD

**Issue by prachi94** [azkaban/azkaban#744]
Hello Team,

I am trying yo upload a zip file through java code and it was not successful.
I tried to upload it manually and then the error trace came which says
-
Problem accessing /manager. Reason:

    INTERNAL_SERVER_ERROR
Caused by:

java.lang.StackOverflowError
	at java.util.HashMap$KeySet.iterator(HashMap.java:1002)
	at java.util.HashSet.iterator(HashSet.java:170)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:93)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
	at azkaban.flow.Flow.recursiveSetLevels(Flow.java:102)
Please help.

**Comment by fsi206914** [comment]
Have you checked your flow? Is there a recycled job dependency?
