### ISSUE TITLE
 ERROR - Bad property definition! null

### ISSUE THREAD

**Issue by idelin** [azkaban/azkaban#802]
run logs
==============================================================
10-11-2016 11:22:49 CST hive-demo INFO - Starting job hive-demo at 1478748169716
10-11-2016 11:22:49 CST hive-demo INFO - azkaban.webserver.url property was not set
10-11-2016 11:22:49 CST hive-demo INFO - job JVM args: -Dazkaban.flowid=hive-demo -Dazkaban.execid=51 -Dazkaban.jobid=hive-demo
10-11-2016 11:22:49 CST hive-demo INFO - Building hive job executor. 
10-11-2016 11:22:49 CST hive-demo ERROR - Bad property definition! null
10-11-2016 11:22:49 CST hive-demo ERROR - caught error running the job
10-11-2016 11:22:49 CST hive-demo ERROR - Job run failed!
java.lang.Exception: java.lang.Exception: Bad property definition! null
	at azkaban.jobtype.HadoopHiveJob.run(HadoopHiveJob.java:104)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:590)
	at azkaban.execapp.JobRunner.run(JobRunner.java:443)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Bad property definition! null
	at azkaban.jobExecutor.ProcessJob.handleError(ProcessJob.java:253)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:73)
	at azkaban.jobtype.HadoopHiveJob.run(HadoopHiveJob.java:100)
	... 7 more
Caused by: java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at azkaban.utils.PropsUtils.resolveVariableReplacement(PropsUtils.java:182)
	at azkaban.utils.PropsUtils.resolveProps(PropsUtils.java:162)
	at azkaban.jobExecutor.AbstractProcessJob.resolveProps(AbstractProcessJob.java:84)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:71)
	... 8 more
10-11-2016 11:22:49 CST hive-demo ERROR - java.lang.Exception: Bad property definition! null cause: java.lang.Exception: Bad property definition! null
10-11-2016 11:22:49 CST hive-demo INFO - Finishing job hive-demo attempt: 0 at 1478748169741 with status FAILED
===========================================================

我使用3.0版本的plugins jobtype,使用jobtype=hive的时候，出现error，help me！

**Comment by zouzou6321** [comment]
me too, do you find the way to fix it?

**Comment by idelin** [comment]
@zouzou6321 我没有解决这个问题，然后我使用2.6版本的jobtype插件可以跑，暂时是使用2.6版本的插件，当然我也奇怪为什么2.6版本的插件可以在3.0的azkaban上跑。

**Comment by aranelofdoriath** [comment]
I have the same issue but caused by Spark plugin:

java.lang.Exception: java.lang.Exception: Bad property definition! null
	at azkaban.jobtype.HadoopSparkJob.run(HadoopSparkJob.java:230)

Any updates on this?
