### ISSUE TITLE
Schedule job failed due to "azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'"

### ISSUE THREAD

**Issue by ldzhjn** [azkaban/azkaban#818]
17-11-2016 01:13:13 PST foo INFO - 1 commands to execute.
17-11-2016 01:13:13 PST foo INFO - effective user is: azkaban
17-11-2016 01:13:13 PST foo ERROR - Job run failed!
azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'
at azkaban.utils.Props.getString(Props.java:478)
at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:120)
at azkaban.execapp.JobRunner.runJob(JobRunner.java:595)
at azkaban.execapp.JobRunner.run(JobRunner.java:446)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
17-11-2016 01:13:13 PST foo ERROR - Missing required property 'azkaban.native.lib' cause: null
17-11-2016 01:13:13 PST foo INFO - Finishing job foo attempt: 0 at 1479373993806 with status FAILED

This is the error log when I try to schedule a simple command job on solo server.
I tried adding azkaban.native.lib in the job file and azkaban.properties file, the error is the same.

**Comment by ldzhjn** [comment]
I was following this guide to setup the solo server and I didn't install any plugins
http://azkaban.github.io/azkaban/docs/latest/#solo-setup

**Comment by hderms** [comment]
I have the same issue

**Comment by hderms** [comment]
I was trying to evaluate whether to use Azkaban versus another workflow management tool but the fact that the example doesn't work is disconcerting

**Comment by fsi206914** [comment]
@hderms This issue is fixed by #827, and is under review now.

**Comment by rajivchodisetti** [comment]
Am not using Solo server mode but trying to install stand alone executor and webserver , but am also running into the same issue , I haven't installed any plugins 


29-11-2016 17:02:49 IST dim_date ERROR - Job run failed!
azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'
	at azkaban.utils.Props.getString(Props.java:478)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:120)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:685)
	at azkaban.execapp.JobRunner.run(JobRunner.java:537)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
29-11-2016 17:02:49 IST dim_date ERROR - Missing required property 'azkaban.native.lib' cause: null
29-11-2016 17:02:49 IST dim_date INFO - Finishing job dim_date attempt: 0 at 1480419169261 with status FAILED
