### ISSUE TITLE
Missing required property 'azkaban.native.lib'

### ISSUE THREAD

**Issue by pnats** [azkaban/azkaban#832]
I see this issue was fixed but error still there after fresh download.

(Download git clone as of 7:00pm mtn time)

Does someone have a detailed way to fix ?

azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'
	at azkaban.utils.Props.getString(Props.java:478)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:120)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:595)
	at azkaban.execapp.JobRunner.run(JobRunner.java:446)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
22-11-2016 18:56:58 MST test ERROR - Missing required property 'azkaban.native.lib' cause: null
22-11-2016 18:56:58 MST test INFO - Finishing job test attempt: 0 at 1479866218014 with status FAILED

**Comment by lpe234** [comment]
see this pull request. [pull/827](https://github.com/azkaban/azkaban/pull/827/commits/6b38f78f40e216dd9ad1d99d3f821b59ed692039)

**Comment by pnats** [comment]
Im not using the solo server download. I am using tar from the build off the directory azkaban-master/azkaban-exec-server/build/distributions

which I copied to another host to run as my executor.

**Comment by pnats** [comment]
Correct that fixed it.
