### ISSUE TITLE
newest code, web-server StackOverflowError

### ISSUE THREAD

**Issue by ld00000** [azkaban/azkaban#860]
RUN bin/azkaban-web-start.sh    error

log:
```
Error: HADOOP_HOME is not set. Hadoop job types will not run properly.
bin/..
.:/home/ld000/dev/jdk1.8.0_65/lib:/home/ld000/dev/jdk1.8.0_65/jre/lib:bin/../lib/activation-1.1.jar:bin/../lib/antlr-2.7.2.jar:bin/../lib/azkaban-common-3.13.0-9-gbb54dcd.jar:bin/../lib/azkaban-web-server-3.13.0-9-gbb54dcd.jar:bin/../lib/c3p0-0.9.1.1.jar:bin/../lib/cglib-nodep-2.2.jar:bin/../lib/commons-beanutils-1.7.0.jar:bin/../lib/commons-chain-1.1.jar:bin/../lib/commons-codec-1.6.jar:bin/../lib/commons-collections-3.2.2.jar:bin/../lib/commons-compress-1.2.jar:bin/../lib/commons-dbcp-1.4.jar:bin/../lib/commons-dbutils-1.5.jar:bin/../lib/commons-digester-1.8.jar:bin/../lib/commons-fileupload-1.2.1.jar:bin/../lib/commons-io-2.4.jar:bin/../lib/commons-jexl-2.1.1.jar:bin/../lib/commons-lang-2.6.jar:bin/../lib/commons-logging-1.1.3.jar:bin/../lib/commons-math3-3.0.jar:bin/../lib/commons-pool-1.5.4.jar:bin/../lib/commons-validator-1.3.1.jar:bin/../lib/data-1.15.7.jar:bin/../lib/data-transform-1.15.7.jar:bin/../lib/dom4j-1.1.jar:bin/../lib/guava-13.0.1.jar:bin/../lib/httpclient-4.3.1.jar:bin/../lib/httpcore-4.3.jar:bin/../lib/jackson-core-2.2.2.jar:bin/../lib/jackson-core-asl-1.9.5.jar:bin/../lib/jackson-mapper-asl-1.9.5.jar:bin/../lib/javax.inject-1.jar:bin/../lib/javax.servlet-api-3.0.1.jar:bin/../lib/jetty-6.1.26.jar:bin/../lib/jetty-util-6.1.26.jar:bin/../lib/joda-time-2.0.jar:bin/../lib/jopt-simple-4.3.jar:bin/../lib/json-20070829.jar:bin/../lib/li-jersey-uri-1.15.7.jar:bin/../lib/log4j-1.2.16.jar:bin/../lib/mail-1.4.5.jar:bin/../lib/metrics-core-3.1.0.jar:bin/../lib/metrics-jvm-3.1.0.jar:bin/../lib/mina-core-1.1.7.jar:bin/../lib/mysql-connector-java-5.1.28.jar:bin/../lib/netty-3.2.3.Final.jar:bin/../lib/oro-2.0.8.jar:bin/../lib/parseq-1.3.6.jar:bin/../lib/pegasus-common-1.15.7.jar:bin/../lib/quartz-2.2.1.jar:bin/../lib/r2-1.15.7.jar:bin/../lib/restli-common-1.15.7.jar:bin/../lib/restli-server-1.15.7.jar:bin/../lib/servlet-api-2.5-20081211.jar:bin/../lib/servlet-api-2.5.jar:bin/../lib/slf4j-api-1.7.7.jar:bin/../lib/snappy-0.3.jar:bin/../lib/sslext-1.2-0.jar:bin/../lib/struts-core-1.3.8.jar:bin/../lib/struts-taglib-1.3.8.jar:bin/../lib/struts-tiles-1.3.8.jar:bin/../lib/velocity-1.7.jar:bin/../lib/velocity-tools-2.0.jar:bin/../extlib/mysql-connector-java-5.1.40-bin.jar:bin/../plugins/*/*.jar

Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by ld00000** [comment]
and i want know where the config files? It's not in the tar.gz package

**Comment by 1102845913** [comment]
I met the same problem

**Comment by Petasoft** [comment]
I met the same problem

**Comment by FrommyMind** [comment]
I met the same problem, and cannot find more log about this error.

**Comment by kunkun-tang** [comment]
This error is thrown to indicate that the application’s stack was exhausted, due to deep recursion in most cases. Anybody in this thread has more investigation and fixed?

**Comment by hikoz** [comment]
create conf dir

**Comment by FrommyMind** [comment]
@hikoz  we have created conf dir  with azkaban.properties file in it

**Comment by hikoz** [comment]
put conf/log4j.properties
```
log4j.rootLogger=INFO,C
log4j.appender.C=org.apache.log4j.ConsoleAppender
log4j.appender.C.Target=System.err
log4j.appender.C.layout=org.apache.log4j.PatternLayout
log4j.appender.C.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
```

**Comment by FrommyMind** [comment]
@hikoz  yes, when I and this file, the java.lang.StackOverflowError exception dispeared. Thanks

**Comment by kunkun-tang** [comment]
Thanks @hikoz

**Comment by abigbigbird** [comment]
linux version:CentOS Linux release 7.2.1511 (Core)
jdk version:1.8.0_121
i got the same error,but when i put conf/log4j.properties,got a new error
`2017-04-26 20:49:32 INFO  AzkabanServer:65 - Loading azkaban settings file from ./azkaban-web-server/bin/../conf
2017-04-26 20:49:32 INFO  AzkabanServer:112 - Loading azkaban properties file
2017-04-26 20:49:32 INFO  WebServerProvider:47 - Setting up connector with stats on: true
2017-04-26 20:49:32 INFO  WebServerProvider:56 - Setting up Jetty Https Server with port:8443 and numThreads:25
2017-04-26 20:49:32 INFO  WebServerProvider:70 - Excluded Cipher Suites: []
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - SLF4J: Defaulting to no-operation (NOP) logger implementation
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2017-04-26 20:49:32 INFO  WebServerProvider:90 - Starting SSL server on port: 8443
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - Exception in thread "main" 
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, azkaban.utils.UndefinedPropertyException: Missing required property 'user.manager.xml.file'
  at azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:185)
  at azkaban.webapp.AzkabanWebServerModule.configure(AzkabanWebServerModule.java:33)
  while locating azkaban.webapp.AzkabanWebServer

1 error
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at azkaban.ServiceProvider.getInstance(ServiceProvider.java:52)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at azkaban.webapp.AzkabanWebServer.launch(AzkabanWebServer.java:692)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at azkaban.webapp.AzkabanWebServer.main(AzkabanWebServer.java:687)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - Caused by: azkaban.utils.UndefinedPropertyException: Missing required property 'user.manager.xml.file'
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at azkaban.utils.Props.getString(Props.java:478)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at azkaban.user.XmlUserManager.<init>(XmlUserManager.java:82)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at azkaban.webapp.AzkabanWebServer.loadUserManager(AzkabanWebServer.java:269)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at azkaban.webapp.AzkabanWebServer.<init>(AzkabanWebServer.java:191)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at azkaban.webapp.AzkabanWebServer$$FastClassByGuice$$81e0dd4a.newInstance(<generated>)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
2017-04-26 20:49:32 ERROR StdOutErrRedirect:55 - 	... 4 more`

**Comment by lx308033262** [comment]
@hikoz  thanks ,problem solved

**Comment by nikshe** [comment]
> @hikoz thanks ,problem solved

how did you fix it?

**Comment by FrommyMind** [comment]
> > @hikoz thanks ,problem solved
> 
> how did you fix it?


as @hikoz said

put conf/log4j.properties

log4j.rootLogger=INFO,C
log4j.appender.C=org.apache.log4j.ConsoleAppender
log4j.appender.C.Target=System.err
log4j.appender.C.layout=org.apache.log4j.PatternLayout
log4j.appender.C.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

**Comment by REIGE** [comment]
I met the same problem with newest code
Run: azkaban.webapp.AzkabanWebServer#main
Exception: java.lang.StackOverflowError thrown from the UncaughtExceptionHandler in thread "main"

I tried put conf/log4j.properties but not work
log4j.rootLogger=INFO,C
log4j.appender.C=org.apache.log4j.ConsoleAppender
log4j.appender.C.Target=System.err
log4j.appender.C.layout=org.apache.log4j.PatternLayout
log4j.appender.C.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n
