### ISSUE TITLE
"Advanced Filter" doesn't work

### ISSUE THREAD

**Issue by wyukawa** [azkaban/azkaban#886]
Hi

I use azkaban 3.14.0-4-g506426c

I push "Advanced Filter" button

![](https://gyazo.com/a193769f0e935e0ea8d630772a4c999c.png)

and then I push "Filter button"
![](https://gyazo.com/e5e6fb442689a542e1e1f43ad8d2e18e.png)

 but it doesn't work!
![](https://gyazo.com/e23ecf425bcfeca443fa1f97aa5a52df.png)

log
```
java.lang.IllegalArgumentException: Invalid format: ""
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:866)
        at azkaban.webapp.servlet.HistoryServlet.handleHistoryPage(HistoryServlet.java:112)
        at azkaban.webapp.servlet.HistoryServlet.handleGet(HistoryServlet.java:66)
        at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.doGet(LoginAbstractAzkabanServlet.java:122)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:584)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:534)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by wyukawa** [comment]
I confirmed that this problem was resolved in azkaban-solo-server-3.15.0-1-g77411d7.
