### ISSUE TITLE
azkaban web /stats url doesn't work

### ISSUE THREAD

**Issue by wyukawa** [azkaban/azkaban#889]
If I access to /stats, the following error occurs.

![](https://gyazo.com/7ee5c1a3a6bcedc4f0405679f9c99ffe.png)

**Comment by suvodeep-pyne** [comment]
Hey @wyukawa ! Thanks for reporting.
What are the steps to reproduce this?

**Comment by wyukawa** [comment]
If you access http://localhost:8081/stats, you can confirm.

/stats endpoint is the following.
https://github.com/azkaban/azkaban/blob/master/azkaban-web-server/src/main/java/azkaban/webapp/AzkabanWebServer.java#L810

**Comment by suvodeep-pyne** [comment]
I assume this is when you bring up the solo-server. correct?

**Comment by wyukawa** [comment]
No, I confirm at azkaban-web and azkaban-executor mode.

**Comment by wyukawa** [comment]
If I check log after adding https://github.com/azkaban/azkaban/pull/890, there is the following stacktrace.

```
java.io.IOException: MetricReportManager is not available
	at azkaban.executor.ExecutorManager.callExecutorForJsonObject(ExecutorManager.java:1144)
	at azkaban.executor.ExecutorManager.callExecutorStats(ExecutorManager.java:1193)
	at azkaban.webapp.servlet.StatsServlet.handleStatePageLoad(StatsServlet.java:195)
	at azkaban.webapp.servlet.StatsServlet.handleGet(StatsServlet.java:70)
	at azkaban.webapp.servlet.LoginAbstractAzkabanServlet.doGet(LoginAbstractAzkabanServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

fail to access to executor /stats
```
$ curl http://localhost:12321/stats?action=getAllMetricNames
{
  "error" : "MetricReportManager is not available"
}
```

**Comment by armisael** [comment]
Did you set `executor.metric.reports=true` (and `executor.metric.milisecinterval.default`) in your `azkaban.properties` as stated [in the documentation](http://azkaban.github.io/azkaban/docs/latest/#system-stats)?

**Comment by wyukawa** [comment]
ah, I see. Thanks!
