### ISSUE TITLE
Azkaban 3.0 leaks NioProcessor threads and over time they consume all the CPU available

### ISSUE THREAD

**Issue by JabbaTheCoder** [azkaban/azkaban#893]
I am currently running Azkaban 3.0 in a pre-production environment and I have a cron job that bounces the Azkaban web server once it consumes all the CPU available on the box and slows everything down. There is clearly a bug that causes gradual increase in CPU consumption over time. I enabled the JMX on the Azkaban web server, connected jvisualvm and was found out the following:

Over time the number of NioProcessor threads grows from 0 to about 10. These threads are constantly consuming CPU eventually consuming all of it and requiring a restart of the Azkaban Web server.

The thread dump for these threads looks something like this:

java.lang.Thread.State: RUNNABLE
at sun.nio.ch.IOUtil.drain(Native Method)
at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:90)
- locked <3e5de8a8> (a java.lang.Object)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
- locked <1b60bc70> (a sun.nio.ch.Util$2)
- locked <3c55e39e> (a java.util.Collections$UnmodifiableSet)
- locked <1f30b1fa> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
at org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:97)
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1074)
at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

Locked ownable synchronizers:
- locked <7945192> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"NioProcessor-1" - Thread t@74
java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
- locked <28189547> (a sun.nio.ch.Util$2)
- locked <77adfc> (a java.util.Collections$UnmodifiableSet)
- locked <3f0eda24> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
at org.apache.mina.transport.socket.nio.NioProcessor.select(NioProcessor.java:97)
at org.apache.mina.core.polling.AbstractPollingIoProcessor$Processor.run(AbstractPollingIoProcessor.java:1074)
at org.apache.mina.util.NamePreservingRunnable.run(NamePreservingRunnable.java:64)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

Locked ownable synchronizers:
- locked <4ca4266d> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by JabbaTheCoder** [comment]
I think the issue may be related to azkaban-ldap-usermanager plugin. It uses org.apache.directory which in turn uses org.apache.mina. I will need to dig deeper to understand whether the bug is in the LDAP user manager or in the org.apache.mina library.

**Comment by JabbaTheCoder** [comment]
It appears that LDAP user manager plugin opens a LDAP connection inside a try block that has no matching finally block. The block is question is NOT a "try with resources" block, so even though the LdapConnection is AutoCloseable it doesn't do us  any good in this case. Essentially, every time an exception happens in getUser() or validateUser() methods a LDAP connection is leaked. This probably explains why the machine burns too much CPU running org.apache.mina code that is invoked by LDAP user manager via org.apache.directory.

**Comment by HappyRay** [comment]
Are you referring to this project https://github.com/researchgate/azkaban-ldap-usermanager?
If so, could you file a bug against that project?
Thanks

**Comment by JabbaTheCoder** [comment]
Yes, I am referring to that project. I am testing a fix, if it works out I will contribute it. Otherwise I'll file a bug. In any event, I agree that this issue belongs in that project. When I filed the bug I didn't realize that the problem was caused by the plugin and not by Azkaban itself. I realized that that was the case after reading the code which took a little bit of time.

**Comment by HappyRay** [comment]
Thanks for reporting and debugging this issue!

**Comment by JabbaTheCoder** [comment]
The fix seems to be working fine for me. I have not seen spurious high CPU consumption by NioProcessor threads after the fix was applied. I created the issue #8 in azkaban-ldap-plugin project, contributed the code and created a pull request.

**Comment by JabbaTheCoder** [comment]
I think we can close this issue.
