### ISSUE TITLE
azkaban's Flow SLA Rules not work

### ISSUE THREAD

**Issue by iCoolchar** [azkaban/azkaban#942]
I followed the instructions here 
[http://azkaban.github.io/azkaban/docs/latest/](http://azkaban.github.io/azkaban/docs/latest/)

and my settings like this:
![image](https://cloud.githubusercontent.com/assets/18082563/23940714/0435025e-09a1-11e7-8fd7-5b3e2e1d286d.png)

but nothing happens when the job has run for more than 3 minutes.

Do I loose anything else? Or do I have to restart the Azkaban service? Thanks!

**Comment by kunkun-tang** [comment]
Have you checked logs? Is there any interesting observation? @iCoolchar 

@jamiesjc any inputs?

**Comment by ameyamk** [comment]
Yes this is a bug - @chengren311 has started working on fixing this bug.

**Comment by chengren311** [comment]
@iCoolchar how long have you waited?

**Comment by Codefor** [comment]
same to me.

I want Azkaban alert when a job takes too long to finish, but it don't work.

**Comment by chengren311** [comment]
@Codefor thanks for reporting this issue. How often does this happen? Does it happen intermittently?

**Comment by iCoolchar** [comment]
@chengren311  It never works. No matter how long I set the duration and how long I have waited. I think you can 100% reproduce it...

**Comment by keiki1120** [comment]
@chengren311 Has this bug been fixed?  My Azakaban version is 3.25.0.  It never works too.

**Comment by chengren311** [comment]
@keiki1120 can you share the screenshot of your sla setup?

**Comment by keiki1120** [comment]
@chengren311 ![image](https://user-images.githubusercontent.com/7676763/28652746-3ef212cc-72bc-11e7-9701-e443de80d6fa.png)

**Comment by chengren311** [comment]
@keiki1120 i doubt the feature is not working. Is your email setup correct? Can you receive emails from azkaban on flow failure if you enable email notification? If you change SLA action to kill from email, would your flow be killed when the flow is killed?

**Comment by keiki1120** [comment]
@chengren311 I can receive emails on flow failure. So I think my email setup is correct . I just test the kill function, the flow can be killed . But I still can't receive the email. If I enable email notification,, I can receive the failure email not the SLA email , when the flow has been killed.

**Comment by chengren311** [comment]
@keiki1120 does your azkaban executor's azkaban property file also contain email setting ?

**Comment by keiki1120** [comment]
![image](https://user-images.githubusercontent.com/7676763/29053892-44f359a2-7c25-11e7-9679-d7e1f0b91a26.png)
I didn't configure the email setting in job file.

**Comment by chengren311** [comment]
@keiki1120 no, i mean azkaban executor's property file:  azkaban.properties

**Comment by keiki1120** [comment]
I didn't configure this file.

**Comment by chengren311** [comment]
@keiki1120 you need to do that too. can you try add following properties to that file?
mail.sender
mail.host
mail.user

**Comment by keiki1120** [comment]
@chengren311  I just checked this file . I configured these properties already. .

**Comment by madhavihande** [comment]
java.lang.RuntimeException: From address not set.
	at azkaban.utils.EmailMessage.checkSettings(EmailMessage.java:153)
	at azkaban.utils.EmailMessage.sendEmail(EmailMessage.java:166)
	at azkaban.utils.Emailer.sendEmail(Emailer.java:244)
	at azkaban.utils.Emailer.sendEmail(Emailer.java:102)
	at azkaban.utils.Emailer.alertOnSla(Emailer.java:113)
	at azkaban.trigger.builtin.SlaAlertAction.doAction(SlaAlertAction.java:110)
	getting this error

**Comment by mvineza** [comment]
I also face same issue. In our case, we are using azkaban 3.57.0.

**Comment by mvineza** [comment]
> I also face same issue (sla email action doesn't send any email). In our case, we are using azkaban 3.57.0.

As noted by @burgerkingeater , the email settings must also be set inside the executors `azkaban.properties` also.
