### ISSUE TITLE
 Missing required property 'azkaban.native.lib'

### ISSUE THREAD

**Issue by lhcg** [azkaban/azkaban#948]
21-03-2017 14:53:26 CST foo INFO - Starting job foo at 1490079206245
21-03-2017 14:53:26 CST foo INFO - azkaban.webserver.url property was not set
21-03-2017 14:53:26 CST foo INFO - job JVM args: -Dazkaban.flowid=bar -Dazkaban.execid=21 -Dazkaban.jobid=foo
21-03-2017 14:53:26 CST foo INFO - Building command job executor. 
21-03-2017 14:53:26 CST foo INFO - 1 commands to execute.
21-03-2017 14:53:26 CST foo INFO - effective user is: azkaban
21-03-2017 14:53:26 CST foo ERROR - Job run failed!
azkaban.utils.UndefinedPropertyException: Missing required property 'azkaban.native.lib'
	at azkaban.utils.Props.getString(Props.java:478)
	at azkaban.jobExecutor.ProcessJob.run(ProcessJob.java:120)
	at azkaban.execapp.JobRunner.runJob(JobRunner.java:693)
	at azkaban.execapp.JobRunner.run(JobRunner.java:545)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
21-03-2017 14:53:26 CST foo ERROR - Missing required property 'azkaban.native.lib' cause: null
21-03-2017 14:53:26 CST foo INFO - Finishing job foo attempt: 0 at 1490079206268 with status FAILED

I use the 3.16.0, and deploy webserver and two ExecutorServer nodes.  I have create plugins/jobtypes in ExecutorServer dir,  but it can't reslove
@kunkun-tang  Kind Regards

**Comment by HappyRay** [comment]
Pls search for Execute-As-User in the main doc
http://azkaban.github.io/azkaban/docs/latest/

**Comment by kunkun-tang** [comment]
@lhcg Have you resolved this issue yet? You must define some properties inside plugin/.
